### ISSUE TITLE
[11주차_수요일] 물병

### ISSUE THREAD

**Issue by yeongleej** [GreatAlgorithm-Study/AlgorithmStudy#145]
- 사이트 : 백준(BOJ)
- 문제: [물병](https://www.acmicpc.net/problem/1052)
- 번호: 1052

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- N <= 10^7
- K <= 1,000
- 완전탐색 불가

### 💡 풀이 아이디어
- 처음 아이디어
   - 만들어야할 묶음 수 구하기(t): 2*K
   - N/t 후 나머지가 생기면 물병이 더 필요한 것으로 (t*나머지)에 따라 필요한 물병 수 구하기
   > 이 방법은 t가 2의제곱꼴일 경우만 사용 가능 (예시 3처럼 K가 2배수 아니면 사용 불가) → 2의제곱 형태를 더 활용하기
- `비트 활용`
   - N을 이진수, 즉 비트형태로 표현했을때 각 자리의 1은 2의 제곱꼴에 해당
      - 1은 뭉쳐진 물병을 나타내고, 1의 개수는 총 뭉쳐진 물병의 수를 나타냄
   - 1의 개수가 K개가 될때까지 물병 추가해나가기
      - 이때 물병추가는 가장 낮은 자리의 비트부터 추가하기
      - 추가된 값이 곧 추가한 물병의 수
   - 비트 연산
      - `Integer.bitCount(N)` : 현재 숫자의 비트에서 1의 수 구하기
         - 해당 함수의 시간복잡도는 `O(logN)`
      - `int lowPos = N & -N;` : 가장 낮은 자리 비트 구하기
         - `-N`은 N을 보수연산한 것으로 가장 낮은 자리 번호를 제외하고 0과 1뒤바뀜.
         - 해당 특징을 이용해 기존 N과 &연산을 해 가장 낮은 자리비트 구함

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 수학 추론 문제라서 고려하지 않음

### 💡 풀이 아이디어
- `2^x + 2^y + ...` 의 항의 개수가 `k개 이하`여야 합쳐서 옮기는 것이 가능
- 따라서 비트 연산으로 `1의 비트가 k개 이하`가 되도록 연산
- 최소의 물병을 더해야 하므로 최소 비트를 더해줌
  - `Integer.bitCount(n)`: n이 갖는 1의비트 수
  - `Integer.lowestOneBit(n)`: n의 마지막 1의 비트의 값
```java
while (Integer.bitCount(n) > k) {
    // 최소한의 수를 더하여 비트 줄이기
    cnt += Integer.lowestOneBit(n);
    n += Integer.lowestOneBit(n);
}
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 10,000,000
- K <= 1,000

=> O(N)으로 생각해보기

### 💡 풀이 아이디어

- N의 값은 (2^0, 2^1, ....들의 합)이 되어야 함
- K >= N이라면 한번에 모든 물병 들 수 있으므로 0

- **내가 푼 과정**

1. K-1개의 물병 담기
    - N에서 `2^i`을 계속 빼줘서 물병 사용하기
    - `2^i`는 N보다 작은 최대 2의 제곱수
    - 이떄 N이 0이되면 0 출력
2. 1번에서 N이 0이 되지 않았다면, 마지막 물병을 만들기 위한 구매해야 하는 최소 물병 개수 구하기
    -  `2^i` > N인 값 구하기
    - `2^i` - N == N이 `2^i`가 되기 위해 구매햐야 하는 물병 수

- **비트마스킹 활용하기**
- N은 (2^0, 2^1, ....들의 합)이 되어야 한다
    - 즉, N을 2진수로 표현했을 때, **1의 개수가 K가 되야 함**
- `Integer.bitCount(N)` : N(10)을 2진수로 나타낸 후 1의 개수
```java
- N의 2진수에서 1의 개수를 카운트
    - 개수가 K보다 작거나 같다면 stop
- 개수가 K보다 크다면, N++, 필요한 물병수++

int ans = 0;
while(true) {
    int bc = Integer.bitCount(N);
    if(bc <= K) break;
			
    N++;
    ans++;
 }
```

> 비트연산 쉽지않네요 ㅜㅜㅠㅠ 😢

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 그리디
- 시간복잡도: ` N은 10^7` `K는 10^3` 으로 최대 `O(N)` 이내로 풀이가능

### 💡 풀이 아이디어
- 기본 물의 양은 1, 물 2개를 계속해서 합치면 2의 제곱이 됨
- `N보다 작은 2의 최대 제곱 수`가 합친 최대 물의 양 으로 1개의 물병을 만들 수가 있음
   - `K-1` 개 만큼 반복하면서 물병을 만들고, 물병이 0이 된다면 ~~K개 이내로 물병을 만들 수 있다는 뜻으로~~
   K 개 만큼 물병을 만들지 못한다는 뜻으로 반복문을 탈출한다. (상점에서 물병을 사도 K를 못만드니까 -1 출력)
   ``` java
   for(int i=0; i<K-1; i++){
      int count = 0;
      while(Math.pow(2,count) < N){  //N개의 물병을 넘지 않는 최대 제곱
         count++;
      }
      N -= (int) Math.pow(2,count-1);   //물병 1개를 만들 수 있는 최대양
      if(N == 0) {
         break;
      }
   }
   ```
- `K-1` 개 반복 후 N 이 남아있다면 상점에서 물병을 사서 보충하기
   -  `Math.pow(2,count) < N` 2의 제곱만큼 순회를 통해 N 보다 작은 최대 물의 양의 제곱(`count`)을 구한 후,
   - `(int) Math.pow(2,count) - N` 출력

> 그런데 `10 3` 를 입력하면 `0` 으로 출력 되던데, 정답으로 넘어가더라구요?
0개는 -1 로 출력해야 하는것 아닌가요..??? (그런데 0일 경우 -1 로 변환해서 출력하게 하면 오답으로 돼요)
>> 수빈님께서 답변 주셔서 이해 됐습니다 ㅎㅎ
"상점에서 물병을 추가로 사도 정답을 못만들 경우" 가 K 개 만큼 물병을 만들지 못하는 경우도 포함되는거였습니다!
(문제에서 "물병의 물을 적절히 재분배해서, K개를 넘지 않는 비어있지 않은 물병" 이라고 적혀있어서 저는 K개 이내로만 물병을 만들면 된다! 로 이해했어요)

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- Integer.bitCount * (물병 개수) : `O(log N) * K`


### 💡 풀이 아이디어
- 제약 조건 : 같은 양의 물을 합쳐야 함 -> 짝수로 줄어듬 -> 물을 `이진수`로 표현
- `N` : 비어 있지 않은 병의 개수 
- `bitCount` : 현재 병의 개수 알 수 있음

```java
        while(true) {
        	int cnt = Integer.bitCount(N); // 2^n 리터 단위로 병 합칠 수 있음
     	
        	if(cnt<=K) { // K개를 넘으면 멈춤
        		break;
        	}
        	N++; // 물병 사기
        	ans++; // 
        }
        System.out.println(ans);
```

> 비트바스킹 아이디어 못 떠올렸습니다

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* `0 < N < 10_000_000`
* 시간 초과를 고려한다면, O(N)까지 고려해보기



### 💡 풀이 아이디어

* n을 2진수로 나타낼 때, 1의 개수를 k개 이하로 만들기 위한 최소 턴의 수를 구하는 문제로 이해해서 풀이하면 됨

```java
while(Integer.bitCount(n) > k) { // 1의 개수 세기
    answer += 1; // 물병을 삼
    n += 1; // n의 값을 1씩 증가
}
```
