### ISSUE TITLE
[11주차_금요일] 준표의 조약돌

### ISSUE THREAD

**Issue by yeongleej** [GreatAlgorithm-Study/AlgorithmStudy#148]
- 사이트 : 백준(BOJ)
- 문제: [준표의 조약돌](https://www.acmicpc.net/problem/15831)
- 번호: 15831

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 300,000 &rarr; 3 x 10^5 이므로 O(N logN) 까지

### 💡 풀이 아이디어
- 특정 조건을 만족하는 범위 찾기 &rarr; `슬라이딩 윈도우`, `투 포인터`
  - 이 문제는 범위가 정해져 있지 않으므로 `투 포인터`
- 현재 포인터 범위 안에 검은색 돌의 수가 조건에 맞으면 오른쪽 인덱스 증가
- 조건에 맞지 않으면 왼쪽 인덱스 증가
- 루프가 끝나기 전에 현재 상태가 조건에 맞는다면 최대 길이 계산
```java
while (r < n) {
    // 주운 검은돌(pb)이 주워야하는 검은돌(b)이하라면
    // 오른쪽 인덱스 증가할 수 있음
    if (pb <= b) {
        if (stones[r])
            pw++;
        else
            pb++;
        r++;
    // 아니라면 왼쪽 인덱스 증가
    } else {
        if (stones[l])
            pw--;
        else
            pb--;
        l++;
    }
    // 현재 상태가 조건을 만족하면 최대 길이 갱신
    if (pb <= b && pw >= w) {
        maxLen = Math.max(maxLen, r - l);
    }
}
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 300,000

=> O(N^2)은 불가
=> O(N) or O(N log N)으로 생각해보기

### 💡 풀이 아이디어

- **투포인터** 활용
- `시작점 s` : 구간내의 검은 돌의 개수가 B보다 많으면 증가해서 구간 감소시키기
- `끝점 e` : 게속 증가해서 구간 늘리기
- (s , e) 구간중 조건에 만족하는 조약돌의 개수를 가지고 있으면 정답 저장
```java
while(e < N) {
	// 조약돌 개수 카운트
	if(srr.charAt(e) == 'B') bc++;
	else wc++;

	// 검은 조약돌이 B개 보다 많으면 시작점 증가로 구간 감소시키기
	if(bc > B) {
		if(srr.charAt(s)=='B') bc--;
		else wc--;
		s++;
	}	
			
	// 준표가 만족하는 조약돌 개수
	if(wc >= W && bc <= B) {
		ans = Math.max(ans, (e-s)+1);
	}
			
	e++;
}
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 300,000
- O(NlogN)이하


### 💡 풀이 아이디어
- `투포인터`
   - 특정지점으로부터 조건만족하는 가장 긴 구간 구하기
- 초기화
   - pebb[] : 조약돌 담을 배열, (흰돌:0, 검정돌:1)
   - walks[]: 주어진 산책길
   > 계산 쉽게하기위해 W:0, B:1로 숫자로 치환해서 저장
- 우선 right 증가로, 돌주으면서 계속 걷기
- 걷다가 검정돌 조건 만족못하면, 만족할때까지 left빼기
- 그 후, 흰돌 조건 만족하면 거리 갱신
```java
  int left = 0;
  int right = 0;
  while (right < N) {
      pebb[walks[right]]++;                         // 오른쪽에 해당하는 색의 돌++

      while (pebb[1]>B){                            // 더이상 못갈경우 조건만족할때까지 left빼기
          pebb[walks[left]]--;
          left++;
      }

      if (pebb[0] >= W){                            // 흰돌 만족하면 거리 갱신
          mx = Math.max(mx, right - left + 1);
      }
      right++;
  }
  System.out.println(mx);
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 ≤ N ≤ 300,000
* 0 ≤ B, W, B+W ≤ N
* O(NlogN) 이하로 풀이해야 될 것
  * 투포인터: O(N)



### 💡 풀이 아이디어

* 하얀 조약돌과 검정 조약돌의 개수에 따라 산책로의 길이가 변경되는 것을 이용하여 투포인터로 구현

```java
while(e < N) {
    if(B < bCnt) { // 검정 조약돌의 개수가 크다면 start 지점 오른쪽으로
        if(str.charAt(s) == 'B') bCnt -= 1;
        else wCnt -= 1;
        s += 1;
    } else { // 하얀 조약돌의 개수가 작다면 end 지점 오른쪽으로
        if(str.charAt(e) == 'B') bCnt += 1;
        else wCnt += 1;
        e += 1;
    }

    if(bCnt <= B && wCnt >= W) answer = Math.max(answer, e - s);
}
```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 투포인터
- 시간복잡도: `1 ≤ N ≤ 300,000` 투포인터 풀이 시 `O(N)` 가능

### 💡 풀이 아이디어
- 주운 검정돌 갯수와 흰색 돌 갯수를 카운팅하며 산책하기
- 투포인터를 활용 해 start 와 end 를 2가지 방법으로 나눠서 전진
   - 주운 검정돌의 갯수를 초과한 경우
      - 현재 위치의 돌의 색을 확인하고 해당 돌 갯수 감소(주운돌 버리기) > start 움직이기 
   - 그렇지 않은 경우 (주운 검정돌의 갯수가 작거나 같을 경우), 
      - 현재 위치의 돌의 색을 확인하고 해당 돌 갯수 증가(돌 줍기) >end 움직이기 
- 만약 현재 주운돌의 갯수가 요구사항의 조건에 맞다면 (검정돌 이하, 흰색돌 이상)
   - `Math.max(result, end - start);` 산책길 길이 갱신하기

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- N<=300,000 O(N^2) 불가
- 투 포인터로 `O(N) `

### 💡 풀이 아이디어
- 조약돌 String으로 입력 -> toCharArray() 
- start, end = 0 초기화 후 조건에 따른 구간 축소, 확장
- 제약 조건 : bCnt(흑돌) < B, wCnt(백돌) >W
```java
        while(e<N){
            if(stones[e]=='B') bCnt++;
            if(stones[e]=='W') wCnt++;

            while(bCnt>B){ // 흑돌 초과한 경우 구간 축소
                if(stones[s]=='B') bCnt--;
                if(stones[s]=='W') wCnt--;
                s++;
            }
            if(wCnt >=M){ // 백돌 최소 조건 만족 시
                length = Math.max(length, e-s+1);
            }
            e++;
        }
```
