### ISSUE TITLE
[11주차_금요일] 박 터뜨리기

### ISSUE THREAD

**Issue by yeongleej** [GreatAlgorithm-Study/AlgorithmStudy#149]
- 사이트 : 백준(BOJ)
- 문제: [박 터뜨리기](https://www.acmicpc.net/problem/19939)
- 번호: 19939

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 100,000
- K <= 1,000

=> O(N) or O(NlogN)으로 생각해보기

### 💡 풀이 아이디어

- "최소와 최대의 차이가 가장 작게 나야 함" : K개의 바구니에 각각 1차이가 나도록  차례대로 담기
    - 예) K = 5, arr=[1, 2, 3, 4, 5]
```java
// 초기값 : 1부터 K개까지 분배
for(int i=0; i<K; i++) {
	arr[i] = (i+1);
	cnt += arr[i];
}
```
- 위에서 초기 값으로 담은 값이 N보다 크다면 조건대로 나눠 담을 수 없으므로 -1출력
- 나머지는 N개에서 초기값 설정에 사용된 공의 개수를 뺸 `N-(sum(arr))`를 동등하게 K로 나눠서 담기
- 이때 K로 나누어 떨어지지 않는다면, 나머지 값을 맨 뒤에 바구니부터 나눠 갖기
    - 공의 개수를 첫번쨰 바구니부터 1씩 차이나도록 담았는데 맨 앞 바구니부터 나머지를 채우면 "각 바구니에 담긴 공의 개수는 모두 달라야함"의 조건에 어긋나기 때문에 맨 뒤의 바구니부터 차례로 증가
```java
// 불가능	
if(cnt > N) {
	System.out.println(-1);
	return;
}
		
N -= cnt;
int val = N / K;                  // 몫
for(int i=0; i<K; i++) {
	arr[i] += val;
}
if(N % K != 0) {
	int re = N % K;          // 나머지
			
	// 맨 뒤부터 1씩 증가하기
	int idx = K-1;
	while(re > 0) {
		arr[idx]++;
		idx--;
		re--;
	}
}
		
```

> 골드4인줄알고 선택했는데 실버4였네요,,,, ㅎㅎㅎㅎ 그치만 초심으로 돌아가서 그리디!!

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 <= N <= 100,000
* 2 <= K <= 1,000
* N, K 값에 의해 순열이나 조합을 사용하면 시간 초과가 발생할 것. 그리디적 & 수학적으로 해결



### 💡 풀이 아이디어
<img src="https://github.com/user-attachments/assets/ba2c829b-a1e9-4dab-81e5-b0a55d96d499" width = "50%">

* 연속적으로 붙어있는 숫자들의 합부터 시작해서, 맨 뒤에서부터 1씩 더해주면서 최솟값과 최댓값의 차이를 구해줌


```java
int sum = K * (K + 1) / 2; // 1부터 K까지의 합
int min = 1, max = K, answer = 0;
if(N < sum) return -1;

while(N > sum) N -= K;

answer = max - min;
if(sum != N) answer += 1;

return answer;
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 &le; N &le; 100,000
- 2 &le; K &le; 1,000
- 완전 탐색으로도 충분히 가능할 것 같지만 수학적으로 계산 가능 &rarr; O(1)

### 💡 풀이 아이디어
- `최소 차이를 만들기`는 고르게 나누어주면 됨 &rarr; `그리디`
- `1의 차이`가 나도록 고르게 나누어주려면 최소 `k * (k+1) / 2`개가 필요
- `k * (k+1) / 2`개로 고르게 나누어주고 나머지가 남는다면 최댓값+1
```java
int min = n / need, max = min + k - 1;
int remain = (n - need) % k;
if (remain != 0) {
    max++;
}
```
- 최댓값 - 최솟값으로 최소 차이 출력

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 100,000
- 2 ≤ K ≤ 1,000
- 수학으로 계산

### 💡 풀이 아이디어
- 차이가 최소로, 모든 공의 수 다르게 분배하기 (K묶음으로)
  - `[0, 1, 2, ... K-1]` 형태로 묶어야함
  - 즉, 모든 공을 조건에 맞게 분배하려면 `0~K-1`까지의 합 보다 N-K뺀 값이 커야함
- `T = N - need` (최소 1개씩 배분 후 남은 공 T)
  - T%K==0이면, 0~K-1로 분배할 수 있고, 이때 최소 차는 (K-1)-0으로 K-1
  - T%K!=0이면, 분배에 1씩 추가하게되고, 최소와 최대차가 1늘어나기에 K

```java
    int need = K * (K - 1) / 2;

    if ((N-K) < need) {
        System.out.println(-1);
        return;
    }

    // 최소 1개씩 배분 후 남은 공 T
    int T = N - need;

    if (T%K==0) System.out.println(K - 1);      // 나눠떨어지면 0~K-1로 분배할 수 있고, 이때 최소 차는 (K-1)-0으로 K-1
    else System.out.println(K);                 // 나눠떨어지지 않으면, 분배에 1씩 추가하게되고, 최소와 최대차가 1늘어남
```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 누적합 + 수학
- 시간복잡도: 2 <= N <= `10^5` 으로 누적합 풀이 시 `O(N)` 으로 풀이가능

### 💡 풀이 아이디어
- 각 바구니에 담긴 공의 개수는 모두 다르고, 가장 많이 담긴 바구니와 가장 적게 담긴 바구니의 공의 개수 차이가 최소가 되려면
K가 3일 때 `1 2 3` 와 같이 바구니에 공이 들어가야 함
   - K 가 5일 때 문제의 요구사항을 충족하려면 `최소 1+2+3 = 6개의 공이 필요` > `누적합` 연산
   - 따라서 주어진 공(N)이 최소 공 갯수 미만일 경우 나눠 담을 수 없으므로 -1 출력
- 주어진 공(N)이 최소 공 갯수 이상일 경우 나머지(%) 연산으로 분기처리
   ```java
	int minCount = dp[K];
	if(N < minCount){
		System.out.println(-1);
	}else{
		int result = (N-minCount) % K;	//(차등 분배 후 남은 공 갯수) % K 
		if(result == 0){
			//모두 1개씩 차등분배가 된 경우(모든 사람이 동일한 개수의 공을 가지는 경우)		
			System.out.println(K-1);
		}else{		
			//모두 차등분배가 불가능한 경우 가장 큰수(K)에게 분배하고, 분배한 만큼 최소값(1)에게도 할당
			System.out.println(K);   //K+result - (result*1)
		}
	}
   ```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
`O(1)`


### 💡 풀이 아이디어
- 처음 접근 : 상자 칸 마다 1, 1, 1, ..... 1개씩 넣어주는 경우 생각 -> 서로 다르게 만들기 위한 추가 작업 필요(같은 개수가 생기거나..)
- 최선의 선택 : 서로 다른 공의 개수 분배하기
```java
 int sum = K*(K+1)/2; // 1+2+3 이렇게 서로 다른 공을 분배

        if(N<sum){
            System.out.println(-1);
            return;
        }

        int extra = N - sum; // 나머지 공

        int min = 1 + extra/K; // 공이 가장 적은 바구니
        int max = K + extra/K; // 공이 가장 많은 바구니

        if(extra %K>0){
            max++;
        }
```
> 그리디..그리디...
