### ISSUE TITLE
[12주차_월요일] 생명과학부 랩 인턴

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#157]
- 사이트 : 코드트리(CT)
- 문제: [생명과학부 랩 인턴](https://www.codetree.ai/training-field/frequent-problems/problems/biology-lab-intern/description?page=3&pageSize=20)
- 년도: 2019

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ n, m ≤ 100
- 0 ≤ k ≤ n*m
- 보드크기 1000이고 구현으로 크게 고려않음


### 💡 풀이 아이디어
- 핵심 아이디어
   - 보드 한칸에 곰팡이 한개씩 존재(중간 겹칠때 빼고)
   - 곰팡이는 크기로 제거 (곰팡이의 크기는 고유함)
- 곰팡이 다루기
   -  board 배열 : 곰팡이들이 크기로 위치
   - live 큐: 살이있는 곰팡이들 관리
   - dieList 리스트: 죽은 곰팡이들 관리 
 1. 해당 열의 곰팡이 채취
     - dieList에 곰팡이 담고, 채취 카운트++ 후, board 0으로 비운 후, break
 2. 곰팡이 이동 `moveMold()`
      - 곰팡이 한명씩 뽑아서 dieList에 포함되면 패쓰
      - 곰팡이 움직이기
         - 이동거리 최적화 : `cur.s %= (cur.d < 2 ? 2 * (N - 1) : 2 * (M - 1));`
         - cur.s만큼 이동하며 벽에 닿으면 방향전환
            ```java
              if (!isValid(nx, ny)) {                  // 벽에 닿으면 방향 전환 후 이동
                      cur.d = (cur.d % 2 == 0) ? cur.d + 1 : cur.d - 1;  // 방향 바꾸기
                      nx = cur.x + dx[cur.d];
                      ny = cur.y + dy[cur.d];
                  }
            ``` 
         - 새로운 보드에 **곰팡이 최종자리 위치**한 후 live에 다시 넣기 (**이때 잡아먹기 같이 진행**)
            ```java
                 if (tmpBoard[cur.x][cur.y]!=0) {        // 만약 최종 움직인 위치에 곰팡이 겹치면
                      tmpDie.add(Math.min(tmpBoard[cur.x][cur.y], cur.b));                // 작은 곰팡이는 다이리스트 행
                      tmpBoard[cur.x][cur.y] = Math.max(tmpBoard[cur.x][cur.y], cur.b);   // 큰 곰팡이는 자리 차지
                  }else tmpBoard[cur.x][cur.y] = cur.b;   // 빈자리면 지금 곰팡이 차지
            ``` 
     - board와 dieList 갱신 (움직임 진행할땐 tmpBoard, tmpDie로 진행했음)

> 처음에 틀렸던 이유는 곰팡이 최종자리 위치 시킬때 max로 큰 곰팡이로 업데이트한 후에 작은 곰팡이 넣어줘서 보드가 변형되었습니다! 그래서 둘의 위치만 수정해줬습니다..! 이런 보드변형 조심하기!!

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ n, m ≤ 100
- 0 ≤ k ≤ n*m
- 구현 문제라 크게 신경쓰지 않음

### 💡 풀이 아이디어
- 모든 열에서 바이러스 채취가 끝나면 종료
- 3차원 List를 이용해서 바이러스의 위치를 저장
- 바이러스가 이동할 때, 유효한 범위를 넘어가면 반대 방향으로 바꿔서 진행
  - 한번에 여러번 방향이 바뀔 수 있음
  ```java
  // 유효한 범위가 될 때까지 반대쪽으로 이동
  while (!isValid(nr, nc)) {
      d = nextDir(d); // 다음 방향
      int over = 0;   // 넘어간 칸
      // 방향에 따라 반대쪽으로 이동
      if (d == 1 || d == 2) {
          if (nr < 1) {
              over = 1 - nr;
              nr = 1 + over;
          } else if (nr > n) {
              over = nr - n;
              nr = n - over;
          }
      } else {
          if (nc < 1) {
              over = 1 - nc;
              nc = 1 + over;
          } else if (nc > m) {
              over = nc - m;
              nc = m - over;
          }
      }
  }
  ```
- 한 칸에 바이러스가 2개 이상이라면 크기를 비교해서 바꿔주기!
  ```java
  Virus other = nextBoard.get(nr).get(nc).get(0);
  // 현재 바이러스와 비교하여 큰 값을 저장
  if (other.b < virus.b) {
      nextBoard.get(nr).get(nc).set(0, new Virus(virus.s, d, virus.b));
  }
  ```
> 바이러스 비교하는 것만 잘해주면 오케이~

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 2<= n, m <= 100 (n*m = 100 * 100)
- k <= 100 * 1000
바로 구현

### 💡 풀이 아이디어
- 구하는 것 : 인턴이 채취한 곰팡이 크기의 총 합을 출력
- 기본 아이디어 : `List<Node>[][] grid`
  - 곰팡이 크기가 가변적 -> `ArrayList`
  - 2차원 배열 ->  null값 방지 -> ArrayList로 초기화 과정
- 핵심 아이디어 : 열(m) 기준 탐색, 곰팡이 이동(벽에 부딪힐 시 방향 전환), 충돌 시 가장 큰 곰팡이만 남김
1. 곰팡이 채취 : `collect()`
- 열(c) 기준 위에서 아래로 곰팡이가 있는지 탐색
- 곰팡이 O -> `Node mold = grid[r][c].get(0)` 해당 칸의 첫번째 곰팡이를 가져옴
- 채취한 곰팡이 크기는 `ans` 누적 -> 채취한 곰팡이 제거 `grid[r][c].clear()` -> 종료(return)

2. 곰팡이 이동 : `move()`
- `속도 처리` : 속도만큼 반복문 처리
- `충돌 처리` : 상<->하, 좌<->우 경우 나눠서 처리
```java
if(nx<0 || nx>=n){ // 상 or 하
       d = (d==0) ? 1 : 0;
       nx = x + dx[d]; // 반대 방향으로 이동
}
if (ny<0 || ny>=m) {
       d = (d==2) ? 3 : 2;
       ny = y + dy[d]; // 반대 방향으로 이동
}
```
3. 곰팡이 충돌(잡아먹기) : `collision()`
- 곰팡이 이동 후 한칸에 두개 이상 곰팡이가 있을 경우 찾아서
- 잡아 먹고 크기 가장 큰 곰팡이만 남겨둠

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- n, m <= 100, n*m = 10,000
- k <= 10,000(n*m)

=> 완전 탐색 완전 가능 ^O^

### 💡 풀이 아이디어
- `mList` : 곰팡이 리스트
    - 각 곰팡이에 번호 부여
    - 곰팡이 객체 선언
    ```java
	static class Mold implements Comparable<Mold> {
		int num, x, y, s, d, size;

		public Mold(int num, int x, int y, int s, int d, int size) {
			super();
			this.num = num;
			this.x = x;
			this.y = y;
			this.s = s;
			this.d = d;
			this.size = size;
		}
		@Override
		public int compareTo(Mold other) {
			// 열 -> 행의 오름차순
			if(this.y == other.y) {
				return this.x - other.x;
			}
			return this.y - other.y;
		}
       }
    ```
    - 가장 위에 있는 곰팡이 찾기 위해서 : 열 -> 행 순으로 정렬되도록 설정
- `isDied` : 죽은 곰팡이 관리 배열
- `selectMold(col)` : 곰팡이 채취하기
    - 곰팡이들 정렬
    - col과 같은 열인 맨 위의 곰팡이 채취
- `moveMold()` : 곰팡이 움직이기
    - visited 배열로 곰팡이 번호 기록후, 같은 위치에 곰팡이 도달 시 크기 비교 후 곰팡이 잡아먹기 와앙 🤑 
- `aliveMold()` : 살아있는 곰팡이 재정비
    - isDied가 false인 곰팡이만 살리기

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

- 2 ≤ n, m ≤ 100
- 0 ≤ k ≤ n ⨉ m
- 1 ≤ x ≤ n, 1 ≤ y ≤ m, 0 ≤ s ≤ 1000, 1 ≤ d ≤ 4, 1 ≤ b ≤ 10000
- 격자의 크기가 크기 않고, 주어진 대로 구현했을 때, 시간 초과는 발생하지 않지만, s가 길어질 때 중복되는 연산이 발생하므로 이를 처리해주는게 좋을듯



### 💡 풀이 아이디어

* `Node`: 곰팡이에 대한 정보 저장
  * `int` 변수 - `r`: 행 좌표, `c`: 열 좌표, `s`: 속력, `d`: 이동 방향, `b`: 곰팡이의 크기
  * `boolean` 변수 -  `isDie`: 곰팡이가 잡혔으면 `true`, 아니라면 `false`  
* `ArrayList<Node> list`: 입력받은 곰팡이들의 정보 저장
* `int[][] map`: 곰팡이 `idx`의 `+ 1` 저장
  * `ArrayList`의 `idx`는 `0`부터 시작하므로 빈 칸과 구분해주기 위해 `idx + 1` 을 저장함 
  * 각 좌표 당, 곰팡이는 한 마리만 있을 수 있으므로 `int`형 2차원 배열로 만듦
* `solution()`
  * 승용이가 왼쪽에서부터 탐색
  * `step1(c)`: 승용이가 현재 있는 열 위치를 기준으로 곰팡이 채취
  * `step2()`: 곰팡이 이동
    1. `map` 초기화
       * 곰팡이들이 움직이고, 위치를 갱신해주기 위해 초기화함
    2. `idx`크기 순서대로면서,  `isDie == true`가 아닌 모든 곰팡이 이동
       * 곰팡이가 움직이기 전, 나아가야되는 거리를 모드 연산을 해서 중복 최대한 줄여주기
       * 위 아래 방향으로 움직인다면 `전체 가야되는 거리 % 2 * 행 길이 - 2`
       * 좌 우 방향으로 움직인다면 `전체 가야되는 거리 % 2 * 열 길이 - 2`
       * 움직이기
    3. 움직일 위치에 이미 곰팡이의 `idx`가 저장되어 있다면, 크기 비교해서 먹고 먹히기

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 구현 (완전탐색)
- 시간복잡도:
2 ≤ n, m ≤ 100 > `10^4`
0 ≤ k ≤ n*m > `10^4 개 이하`

### 💡 풀이 아이디어
- `Mold[][] lab` : 곰팡이들 위치 저장
- `List<Mold> inventory` : 인턴이 채취한 곰팡이들 저장
- `lab` 에 곰팡이들을 저장할 때 이동거리(s) 를 사전에 최적화 해서 이동거리를 낮추기
(규칙성 공식을 만드는 시도는 했으나.. 포기하고 해설참고 했어요🤯😡)
   ``` java
   //원리: (2*n-2) 또는 (2*m-2) 크기를 넘어가게 되면 결국 같은 이동거리가 반환시켜서 이동거리 최적화 하기
   //ex) s = 1,11,21,31 .. 는 결국 s = 1 과 같음
        private int calculateS(int s, int d){
            if(d<=1){
                return s % (2*n-2);
            }else{
                return s % (2*m-2);
            }
        }
   ```
- 곰팡이 채취
   - 하나의 열(j)에서 행(i)을 순회하며 제일 빨리 발견한 곰팡이를 채취 (`inventory`에 저장 후 `lab`에서 없애기)
- 곰팡이 이동
   - 곰팡이가 가진 이동거리만큼 한칸 씩 이동하며 격자를 벗어날 경우 방향을 전환해줌
- 이동한 곰팡이는 새로운 공간에 임시저장
   - 기존의 `lab` 에서 이동시킨 곰팡이를 다시 저장하면 중복 이동이 발생할 수도 있음
   - 이동된 공간에 아무도 없거나, 이미 다른 곰팡이가 있으면 크기 비교 후 갱신 
   - 모든 곰팡이들이 이동을 완료했다면 임시 저장된 공간을 기존의 `lab` 으로 이동
