### ISSUE TITLE
[12주차_화요일] 배열 정렬

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#158]
- 사이트 : 백준(BOJ)
- 문제: [배열 정렬](https://www.acmicpc.net/problem/28707)
- 번호: 28707
- 레벨: 골드1

> 백준 25001 ~ 30000 폴더가 없어서, 우선 30000-35000폴더에 올려놓아주시면 수정하겠습니다!(수빈)
```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 8
- 1 ≤ M ≤ 10
- 이번 문제는 시간 복잡도를 어떻게 고려해야 할까요...
- 일단 넉넉해보여서 신경 쓰지 않았습니다

### 💡 풀이 아이디어
- 배열 혹은 문자열(정수)를 노드로 가져야 하는 문제
  - 각 노드의 최소 비용은 `HashMap`을 이용하여 저장
  ```java
  HashMap<Integer, Integer> hm = new HashMap<>(); // 노드 별 최단거리를 저장할 맵
  ```
- 노드에서 다른 노드로의 최단거리 &rarr; `다익스트라`
- `HashMap`에 저장되어 있는 비용과 현재 노드에서 스왑한 비용을 비교
```java
while (!pq.isEmpty()) {
    int[] cur = pq.poll();
    int key = arrToInt(cur);  // key 생성 (배열 → 정수)
    for (int[] command : commands) {
        int[] next = swap(cur, command[0], command[1]); // 커맨드 적용
        int nextKey = arrToInt(next);                   // 커맨드 적용한 배열을 키로 변환
        // 더 적은 비용이 발생했을 때
        if (hm.get(key) + command[2] < hm.getOrDefault(nextKey, Integer.MAX_VALUE)) {
            // 값 갱신
            hm.put(nextKey, hm.get(key) + command[2]);
            pq.offer(next);
        }
    }
}
```
- `arrToInt()`: 배열을 정수로 변환해주는 함수

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 다익스트라
- 시간복잡도: 
   - `2 <= N <= 8` 으로 최대 모든 조합 경우의 수는 8! > 40320개 으로 모든 조합 만들 수 있음
   - 간선 탐색 `O(V+E)` > 최대 `10^8`?
   - 우선순위 큐 비용 정렬 `O(logV)`

### 💡 풀이 아이디어
- 비내림차순(=오름차순) 정렬된 배열을 만들기 위해서 `순서가 교체된 배열` 자체를 하나의 노드로 생각해야 함
- 비내림차순 정렬된 배열과 같아질 때까지 **순서가 교체되는 모든 배열을 노드로 저장**하고, 이때 **각 노드 별 최소비용을 구할 때 다익스트라를 활용**
- `List<Controller> list = new ArrayList<>()`
조작 방법을 저장한 리스트
- `Map<Integer,Integer> table = new HashMap<>()`
<배열,최단거리> 각 노드(`순서가 교체된 배열`) 별 최소 비용 저장 테이블
- `PriorityQueue<Node> pq = new PriorityQueue<>()`
조합한 각 노드(`순서가 교체된 배열`) 를 만들기 위해 발생한 최소비용을 저장 (비용이 다른 중복된 노드 존재가능)

``` java
    public static void dijkstra(){
        while(!pq.isEmpty()){
            Node node = pq.poll();
            if(answer == node.v){
                break;
            }
            //신규 비용이 기존 비용보다 더 클 경우 갱신불가
            if(table.containsKey(node.v) && table.get(node.v) < node.c){
                continue;
            }
            for(Controller controller : list){
                int next = swap(node.v, controller);
                int cost = node.c + controller.c;
                if(table.containsKey(next) && table.get(next) <= cost){
                    continue;
                }
                //기존 비용+이동비용 이 기존의 최소 비용보다 더 작을 경우 최단거리(비용) 갱신
                table.put(next,cost);
                pq.offer(new Node(next,cost));
            }
        }
    }
```
- 순서를 변경할 때 각 자릿수를 계산 해주는 연산 필요 
   - 단순히 문자열로 변환해서 순서를 변경하면 런타임 에러가 발생
   ``` java
        // 배열 길이 최대 8, 원소 최대10 이기 떄문에 10101010101010101010 와 같은 수가 온다면 런타임에러 발생
        String data = v+"";
        for(int i=0; i <data.length(); i++){
            arr[i] = Character.getNumericValue(data.charAt(i));
        }
   ```
- 주의사항
   - int 타입일 경우 String > int 변환 시 int 범위 초과로 `NumberFormatException: For input string: "101010101010"` 런타임에러 발생

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 8
- 1 ≤ M ≤ 10
- 완전탐색 시 8!*2^10...? 암튼 완전탐색 불가
   > 완전탐색 불가에도 불구하고 처음에 dfs로 진행함...ㅎㅎ 좀 더 시간복잡도 잘 생각하기
- 가능한 모든 순열 8!

### 💡 풀이 아이디어
- (처음 도전) dfs를 통한 완전탐색
   - 답이 없을 경우(-1) 종료 조건 만들기 까다로움
   - 시간복잡도 터짐
- 각 배열의 상태로 하나의 노드로 생각하기(`변형된 BFS`)
   > 다른 분들 이슈 설명 보고 `배열 상태를 하나의 노드`로 생각해야한다는걸 알게되었는데, 풀고나니 다익스트라가 아닌 변형된 bfs로 푼걸 알게되었습니다..!
   - 일반적인 다익스트라 → 탐색 순서가 중요
      - 가장 비용이 작은 상태부터 탐색하면서 모든 노드를 탐색하지 않음
   - 이번 문제는 모든 상태를 탐색해봐야 최단 경로를 찾을 수 있음 → 탐색 순서가 중요X
      - 그리고 이때 그냥 큐를 사용해도 비용이 적을때만 갱신해서 큐에 담기때문에 불필요한 탐색하지 않음
      - 즉, **비용이 작을때만 큐에 넣는** 조건이 우선순위 큐 역할을 대신하기에 다익스트라처럼 동작
   ```java
     private static void bfs(int[] start) {     // 각 배열의 상태를 노드로 보는 다익스트라 진행
        Queue<int[]> que = new ArrayDeque<>();      // 배열 스왑을 진행해야하기에 큐 값은 배열로 가짐
        que.add(start);

        while (!que.isEmpty()) {
            int[] cur = que.poll();
            int curNum = arr2int(cur);              // 현재 배열을 숫자로 변경한 값
            for (Node cm : cmd) {
                int[] nxt = swap(cm.u, cm.v, cur);  // 스왑 진행
                int nxtNum = arr2int(nxt);
                if (map.containsKey(nxtNum)){       // 이미 해당 배열 상태가 존재할 경우
                    if (map.get(nxtNum) > map.get(curNum) + cm.c) {     // 비용이 더 적으면 업데이트
                        map.put(nxtNum, map.get(curNum) + cm.c);
                        que.add(nxt);
                    }
                } else {                            // 존재하지 않으면 새롭게 값 추가
                    map.put(nxtNum, map.get(curNum) + cm.c);
                    que.add(nxt);
                }
            }
        }
    }
   ```

> 우선 **배열 상태를 하나로 노드로 보고 푼다**는 아이디어도 신박했는데, 풀고 보니 우선순위큐가 아닌 그냥 큐로 풀었다는 사실을 깨닫고 왜 이것도 되지 하면서 정리해봤는데,, 잘정리됐는지 모르겠네요...ㅎㅎㅎㅎ

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 2 <= A의 길이 <= 8
* 1 <= 각 원소 <= 10
* 1 <= 조작의 개수 <= 10
* 최악의 경우 배열 경우의 수: 8!이므로 문제에 대한 시간 복잡도는 정확하지 않지만, `8! (40320) + α` 정도라고 생각



### 💡 풀이 아이디어

* 초기 배열에서 어떤 조작을 거치느냐에 따라 배열의  상태가 달라짐 
  * 어떤 상태까지 도달할 때, 최소 거리 구하기 (다익스트라)
* `HashSet<String, Integer> cost`
  * `key`: `Arrays.toString(int[] arr)`
  * `value`: `int[] arr`을 만들 때 까지의 비용
* `ArrayList<Calculator> cal`: 조작에 대한 정보 저장

```java
while(!pq.isEmpty()) {
    Node current = pq.poll();
    if(A.equals(Arrays.toString(current.arr))) break;

    for(Calculator ca: cal) {
        int[] copyArr = current.arr.clone();
        int l = ca.l, r = ca.r, c = ca.c;

        int tmp = copyArr[l];
        copyArr[l] = copyArr[r];
        copyArr[r] = tmp;

        String nextKey = Arrays.toString(copyArr);

        int nextCost = current.c + c;
        if(!cost.containsKey(nextKey)) cost.put(nextKey, INF);
        if(nextCost < cost.get(nextKey)) {
            cost.put(nextKey, nextCost);
            pq.add(new Node(copyArr, nextCost));
        }
    }
}
```

> `clone()`: 자신을 복제하여 **새로운 인스턴스 생성** (얕은 복사)

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N<= 8

=> 최대 노드의 개수 : T = 8! (약, 40,000)
=> 다익스트라 풀이 :  O(T log T)

### 💡 풀이 아이디어

- 배열을 노드로 생각하기
    - 각 배열의 상태를 정확히 or 빠르게 파악하기 위해서 배열 -> 정수로 변환하기
    ```java
	static class Node implements Comparable<Node> {
		int[] arr;
		int num, cost;
		
		public Node(int[] arr, int num, int cost) {
			super();
			this.arr = arr;
			this.num = num;
			this.cost = cost;
		}

		@Override
		public int compareTo(Node other) {
			return this.cost - other.cost;
		}
	}
    ```
- `arrayToInt(brr)` : 각 배열의 상태를 정확히 or 빠르게 파악하고, Map의 key값으로 사용하기 위한 정수 변환
    - 예) [1, 4, 3, 2] -> 1432
- `Map<Integer, Integer>  cMap` : 입력된 원본 배열에서 각 배열로 가는 최소 비용을 저장하기 위한 해쉬맵
    - 예) [1, 4, 3, 2] => cMap.get(1432) = 0(비용)
- `dijkstra()` : **다익스트라**를 활용해서 가능한 배열들(노드)을 최소 비용으로 만들기
    - 주의) 원본 배열을 swap한 다른 배열을 만들기 위해서는 copyArray가 필요함!

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- `시간복잡도` : N<=8, 8!=40,320
- `다익스트라` : 배열 상태 변경 비용 주어진 것 보고 그래프 아이디어 -> 최소 비용 -> 다익스트라

### 💡 풀이 아이디어
- 배열 A를 `비내림차순`으로 정렬하기 위해 필요한 비용 총합의 최솟값을 출력
  - 불가능할 경우 -1 출력
- `Node` : 배열 자체를 노드로 정의
- `public Node(int[] arr, int cost)` : arr(배열 상태), cost(발생한 비용), 비용 기준으로 오름차순 정렬
- `PriorityQueue<Node> queue = new PriorityQueue<>()` : 방문할 노드, 비용 관리
  - 비용이 가장 작은 노드를 꺼내며 최소 비용 찾기
-  `HashMap<String, Integer> visit = new HashMap<>()` : 배열 상태 중복을 방지하기 위해 HashMap 사용
- `새로운 비용 갱신` : 아직 방문 안했거나 새로 계산한 비용이 최소 비용일 경우 큐에 삽입 후 방문 처리 갱신
```java 
 if(!visit.containsKey(newNode)|| visit.get(newNode) > newCost){ // 새로운 비용이 더 작으면 갱신
        queue.offer(new Node(cloneArr, newCost));
        visit.put(newNode, newCost); // 방문처리
}
```
