### ISSUE TITLE
[12주차_수요일] 불량 사용자

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#159]
- 사이트 : 프로그래머스(PG)
- 문제: [불량 사용자](https://school.programmers.co.kr/learn/courses/30/lessons/64064)
- 번호: 64064
- 레벨: level3

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 <= user_id[] <=8
-1 <=  user_id 배열 각 원소들의 값은 길이  <=8
- 8^8 (10^8)
- 완전탐색 간당하게 가능


### 💡 풀이 아이디어
- dfs 완전탐색 이용
   - 각 `밴 아이디`에 대해 모든 사용자들을 다 돌면서 해당 밴 아이디에 해당되는지 확인
- `dfs(0, visited, tmp)`
   - (종료 조건) 모든 밴 길이를 다 돌았을 경우, 사용자를 다 모았다면 정렬해서 정답 Set에 넣기
   - (함수 수행) 모든 사용자를 돌아보면서, 밴아디이 해당 체크(`check()`) 후 해당하면 dfs 진행
- `check(String user, int idx)`
   - 특정 사용자 아이디가 특정 밴 아이디에 일치하는지 확인
   - 길이가 다르면 false
   - 글자 하나씩 비교하면서 *일땐 continue, 서로 다른 글자면 false
- 최종적으로 정답 set의 길이 반환

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 배열의 크기 <= 8
- 문자열의 길이 <= 8

=> 최대 탐색 시간 : 8^8 = 약 1천만
=> 완전탐색 가능

### 💡 풀이 아이디어

- `Set<Set<String>>  uSet` : 정답 목록들의 집합
- `Set<String> bSet` : 목록을 찾기 위한 서브 집합
- dfs 활용
    - `dfs(depth, user_id, banned_id)`
    - depth가 brr의 길이와 같아지면, uSet에 동일한 목록이 있는지 체크 후 없다면 삽입
        - `set.containsAll()`을 사용하여 같은 집합이 있는지 판단
    - 모든 user_id를 탐색하면서, 
        - 현재 목록인 `bSet`에 user_id가 포함되지 않고,
        - 현재 depth에 해당하는 banned_id[depth] 와 일치한다면
        - bSet에 삽입 후 다음 깊이 탐색
    ```java
    public static void dfs(int depth, String[] urr, String[] brr) {
        if(depth == brr.length) {
            boolean isOk = true;
            for(Set<String> sub : uSet) {
                if(sub.containsAll(bSet)) {
                    isOk = false;
                    break;
                }
            }
            
            // copy bSet 생략
            
            return;
        }
        
        for(String s : urr) {
            // 현재 제재 아이디 목록에 있지 않고 && 불량 사용자 아이디와 매핑 된다면
            if(!bSet.contains(s) && findId(s, brr[depth])) {
                bSet.add(s);
                dfs(depth+1, urr, brr);
                bSet.remove(s);
            }
        }
    }
    ```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 순열(dfs), Set
- 시간복잡도: user_id 배열의 크기 1 이상 8 이하
순열로 풀 경우 8! > `O(8!)` 
> 문자열의 길이는 왜 고려해야 하는 부분인가요!?
>> 모든 문자열 연산은 1:1 매칭으로 O(n) 시간복잡도를 발생하기 때문에 값이 큰 경우 시간초과가 발생할 수도 있음

### 💡 풀이 아이디어
- 제재 아이디 목록과 일치하고, 기존의 제재 아이디 목록과 순서 상관없이 원소가 중복되지 않는다면 카운팅 하기
- 유저 아이디가 제재목록의 아이디와 일치하는지 확인하기
   - String `matches` 메소드을 사용 해 정규식으로 문자열 일치 한지 확인
   정규식 표현 `.` 은 임의의 한 문자를 표현
   ex) `.rodo` 는 임의의 한 문자로 시작하고, 그 다음에 "rodo"가 오는 문자열과 매치됨
- 순열로 모든 경우에 대해 `제재아이디 목록 문자열` 만들기
   - 특정 유저 아이디가 제재 목록에서 1개 이상 같을 경우가 있기 때문에 조합이 아닌 순열로 모든 경우를 만들기
   - 매칭된 제재아이디들을 하나의 문자열로 연결 (ex. `"frodo crodo abc123 frodoc"`)
- 기존의 `제재아이디 목록 문자열`과 일치할 경우 `HashSet`으로 중복 제거하기
   - `제재아이디 목록 문자열`을 `String[]` 로 만든 후 중복 제거를 위해 정렬
   ``` java
    if(index == bannedIds.length){
        String[] combination = ids.split("\\s");
        Arrays.sort(combination);

        StringBuilder sb = new StringBuilder();
        for (String id : combination) {
             sb .append(id);
        }
        set.add(sb .toString());
        return;
    }
   ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- `user_id 배열의 크기는 1 이상 8 이하입니다.` &rarr; 재귀

### 💡 풀이 아이디어
- 모든 경우를 확인해야 하므로 `완전 탐색` &rarr; `재귀`를 이용해서 풀이
  - `banned_id`의 길이가 최대 깊이
- 문자열의 비교를 위해 `banned_id`배열의 요소에서 `*`를 `.`로 변환 &rarr; `정규표현식`으로 비교
- `아이디들이 나열된 순서와 관계없이 아이디 목록의 내용이 동일하다면 같은 것으로 처리하여 하나`라는 조건을 처리해야 함
  - 중복을 처리하기 위한 Set을 이용해야 함,  `방문 처리`
  - 비트 마스킹을 이용해서 사용한 유저들을 표시 &rarr; 순서에 상관 없이 모든 조합을 체크할 수 있음
```java
for (int i = 0; i < n; i++) {
    // 방문하지 않은 유저들 중에서 정규표현식과 일치하는 경우
    if ((visited & (1 << i)) == 0 && user_id[i].matches(banned_id[depth])) {
        // 방문 처리 후 다음 재귀 진행
        recursive(user_id, banned_id, depth + 1, visited | (1 << i));
    }
}
```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
배열 크기 <= 8, 문자열 길이 <=8 -> `완전 탐색` 가능


### 💡 풀이 아이디어
banned_id와 매칭되는 user_id의 모든 조합 수 찾기
1. 패턴 매칭 : 정규식 + ArrayList + 반복문
* 제외 나머지 문자 일치할 경우 matched list에 추가 
```java
 String regex = banned_id[i].replace("*", "."); 
            for (int j = 0; j < user_id.length; j++) {
                if (user_id[j].matches(regex)) { // 정규식으로 매칭 확인
                    matched.add(user_id[j]);
                }
            }
```
2. 가능한 조합 생성 : 백트래킹
- `Set<Set<String>> ` : banned_id에 매칭된 user_id, 중복 선택되지 않게 
- 모든 banned_id를 처리(depth == banned_id.length)하면 현재까지 선택된 조합을 결과 집합(resultSet)에 추가

> 출제 의도는 정규식이었습니다! 제가 출제 해놓고 까먹고 DFS로 풀었다가 정규식으로 다시 풀어서 올렸습니다..

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 <= `user_id` 배열의 크기 <= 8
* 1 <= `banned_id` 배열의 크기 <= `user_id` 배열의 크기
* O(n) = 8 ^ 8



### 💡 풀이 아이디어


* 정규식과 단순한 DFS 만으로 이용해서 불량 사용자 list를 구했을 때, **_중복되는 회원들의 list_**가 생길 수 있음 (회원 내역은 똑같으나, 내용은 같은)
  * 이것을 구분할 수 있는 요소가 필요함 → `Set`, `boolean` 배열을 통해 확인할 수 있으나, 비트마스킹을 이용했음


> **`banned_id`에서 `*`를 `[a-z0-9]`로 바꿔서 `String.matches`를 통해 불량 사용자인지 확인할 수 있도록 함**

```java
for(int i = 0; i < banned_id.length; i++) banned_id[i] = banned_id[i].replaceAll("\\*", "[a-z0-9]");

```

<br>



> **DFS와 비트마스킹을 통해 `banned_id`에 해당되는 불량 회원을 구함**

```java
static void func(int depth, int idx, int status, String[] userId, String[] bannedId, int bannedLength) {
    if(depth == bannedLength) {
        if(!set.contains(status)) {
            set.add(status);
            answer += 1;
        }
        return;
    }

    for(int i = idx; i < userId.length; i++) {
        if((status & (1 << i)) > 0) continue; // 이미 불량 사용자 리스트에 있는 회원이라면 continue
        if(!userId[i].matches(bannedId[depth])) continue;

        status |= (1 << i); // i 번째 회원 비트 키기

        int nextIdx = 0;

        // banned_id[depth]와 banned_id[depth + 1]가 같은 경우
        if(depth < bannedId.length - 1 && bannedId[depth].equals(bannedId[depth + 1])) nextIdx = i + 1;

        func(depth + 1, nextIdx, status, userId, bannedId, bannedLength);
        status &= ~(1 << i); // i번째 회원 비트 끄기
    }
}
```

* 불량 사용자들의 리스트가 중복되는 경우를 방지하기 위해 `if(depth < bannedId.length - 1 && bannedId[depth].equals(bannedId[depth + 1])) nextIdx = i + 1;` 코드와 `nextIdx`를 사용했으나, 근복적으로 해결하지 못함
  * 비트마스킹을 통해 불량 사용자 리스트 중복을 방지했기 떄문에, 위 코드는 삭제해도 됨
