### ISSUE TITLE
[12주차_수요일] 반도체 설계

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#160]
- 사이트 : 백준(BOJ)
- 문제: [반도체 설계](https://www.acmicpc.net/problem/2352)
- 번호: 2352
- 레벨: 골드2
```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ n ≤ 40,000
- 각 노드별 완전탐색 불가
- 이분탐색 이용(`O(logN)`)


### 💡 풀이 아이디어
- 연결선이 꼬이지 않으려면 역순으로 향하면 안됨 → 정렬된 개수 찾기 → `최장 증가 부분 수열`문제
- 이분탐색을 통한 최장 증가 부분 수열 구하기
   - 포트 번호 리스트: `arr`
   - 최장 부분 증가 수열을 담을 리스트: `ans`
   1. 첫번째 원소 리스트(`ans`)에 넣기
   2. for문을 통해 배열요소(`arr`)를 보면서(두번째 인덱스 부터)
       - ans의 마지막 원소보다 크면 바로 ans에 붙이기
       - ans보다 작으면 이분탐색(`findIdx()`)를 통해 해당 원소가 리스트에 들어갈 자리를 찾고, 찾은 자리(`idx`)로 값 변경
   ```java
     ans.add(arr[0]);                                             // 첫번째 원소 넣기
      for (int i = 1; i < N; i++) {
          if (arr[i] > ans.get(ans.size()-1)) ans.add(arr[i]);    // 리스트의 마지막 원소보다 큰 값이면 바로 붙이기
          int idx = findIdx(arr[i]);                              // 작을 경우 해당 원소가 들어갈 위치 찾아서 값 변경
          ans.set(idx, arr[i]);
      }
      System.out.println(ans.size());
   ```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 40,000

=> 완전탐색 예) dfs : O(N^3) 불가능
=> O(N^2) or O(NlogN)으로 생각해보기 

### 💡 풀이 아이디어

- LIS 풀이 : 가장 긴 증가하는 부분 수열을 구하면됨
- N<=40,000이므로 1) dp활용(O(N^2)), 2) 이분탐색 활용(O(NlogN)) 모두 가능
- 이분 탐색으로 가장 긴 증가하는 부분 수열의 길이 찾기
```java
lines = new ArrayList<>();
lines.add(arr[0]);
		
for(int i=1; i<N; i++) {
	if(lines.get(lines.size()-1) < arr[i]) {
		lines.add(arr[i]);
	} else {
		// 이분 탐색으로 적절한 위치 찾고 삽입
		int idx = findPos(arr[i]);
		lines.set(idx, arr[i]);
	}
}
```

> 오랜만에 이분탐색 보니깐 반갑네요~~ ^O^

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 이분탐색 (LIS)
- 시간복잡도: `1 ≤ n ≤ 40,000` 
이분탐색으로 풀이 시 `O(logN)`

### 💡 풀이 아이디어
- 최장 증가 수열을 활용한 이분탐색
- 최대한 많은 포트를 설치하기 위해 선이 겹치지 않도록 설치해야 함
   - 최장 증가 수열의 순서를 따르면 선이 겹치치 않게 됨
- 선이 겹치게 된다면 적절한 최장 증가 수열의 위치를 이분탐색으로 찾아줌
   - 이미 설계된 포트 중 현재 포트와 가장 가까우면서 큰 포트를 찾기 위해 이분탐색
   - 현재 포트와 가장 가까우면서 큰 포트의 위치가 현재 포트를 설계할 수 있는 가장 적절한 지점!
- `List<Integer> lis` : 겹치치 않는 최장 증가 수열을 저장하는 리스트 (= 설치 가능한 포트들 저장)
 ``` java
lis.add(0);
for(int i = 1; i<connection.length; i++){
	if(lis.get(lis.size()-1) < connection[i]){
		lis.add(connection[i]); //최장 증가 원소 추가
	}else{
		int index = binarySearch(lis.size()-1, connection[i]);
		lis.set(index, connection[i]);  //원소가 들어갈 위치를 찾았다면 현재 원소와 가장 가깝고 큰 원소를 제거
	}
}
```

> 처음에는 그리디로 접근했는데, (순회를 돌면서 연결 간격이 좁은 것 부터 최대로 많이 연결하기)
그리디로 풀게 되면 순회를 하면서 이전의 연결선이 최적의 경로가 아닐 때 갱신하는 과정이 필요하기 때문에 최적의 경로를 찾기 어려움
>> 최장증가수열을 DP 로만 풀어봐서 이분탐색을 활용할 수 있는지 몰랐네요!

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 <= 포트 개수 <= 40,000
* nLogn ≈ 611508 이므로 4,000 * nLogn 이내로 해야될 것 
* 기본적인 DP 방법
  * O(n * n) = 1,600,000,000
* LIS를 사용한 방법
  * O(nLogn) 


### 💡 풀이 아이디어

* 선들이 교차하지 않으면서 가장 길게 연결할 때, 최대 연결 개수 구하기
  * 최장증가부분수열 구하는 문제임! 
* 첫번째 풀이 방법: 기본적인 DP 사용
  ```java
  for(int i = 0; i < arr.length; i++) {
      dp[i] = 1;
  
      for(int j = 0; j < i; j++) {
          if(dp[i] < dp[j] + 1 && arr[j] < arr[i]) {
              dp[i] = dp[j] + 1;
          }
      }
  
      result = Math.max(result, dp[i]);
  }
  ```
  > 걸린 시간이 4104ms 인데, 통과가 됐습니다!

<br>



* 두번째 풀이 방법: 이분탐색을 통해 LIS의 길이 구하기
  ```java
  // 이분탐색을 통해 LIS의 길이 구하기
  static int getResultByBinarySearch(int[] arr) {
      int[] lis = new int[arr.length];
  
      int cnt = 1; // LIS 길이를 구할 변수
  
      lis[0] = arr[0];
  
      for(int i = 1; i < arr.length; i++) {
          if(lis[cnt - 1] < arr[i]) lis[cnt++] = arr[i];
          else {
              int idx = binarySearch(lis, arr[i], 0, cnt);
              lis[idx] = arr[i];
          }
      }
  
      return cnt;
  }
  ```
  > 저번에는 이분탐색으로 LIS의 길이를 구하는 방법이 잘 이해되지 않았는데, 다시 관련 문제를 풀어보니 이해가 되었습니다!!

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ n ≤ 40,000 &rarr; 4 x 10^4에 2초이므로 2 x  O(N^2)까지 가능할 듯

### 💡 풀이 아이디어
- 꼬이거나 겹치면 안되게 연결하기 &rarr; 가장 긴 증가하는 부분 수열(LIS)
- O(N^2)으로도 계산할 수 있지만 `이분탐색`을 이용해서 최적화
```java
int[] lis = new int[n];
int len = 0;
for (int i = 0; i < n; i++) {
    int idx = Arrays.binarySearch(lis, 0, len, arr[i]);
    if (idx < 0)
        idx = ~idx;
    lis[idx] = arr[i];
    if (idx == len)
        len++;
}
```

> 문제가 전형적인 LIS문제였습니다!

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
1 ≤ n ≤ 40,000 -> `O(N^2)`


### 💡 풀이 아이디어
- 연결선이 서로 꼬이지(겹치지, 교차하지) 않도록 하면서 최대 몇 개까지 연결할 수 있는지 구하기
- 연결할 수 있는 선들을 입력 받음 -> 배열의 일부가 이미 순서대로 정렬된 상태를 유지하고 싶다는 목표 O → LIS(최장 증가 부분 수열)
  - Arrays.fill(dp, 1) : 최소 1개 선은 연결 가능 
- LIS : dp[] 사용
```java
  for(int i=1; i<n; i++){ // LIS
           for(int j=0; j<i; j++){
               if(arr[i] > arr[j]){
                   dp[i] = Math.max(dp[i] , dp[j]+1);
               }
           }
        }

        int LIS = 0;
        for(int i=0; i<n; i++){
            LIS = Math.max(LIS, dp[i]);
        }
```
