### ISSUE TITLE
[12주차_목요일] 외벽 점검

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#161]
- 사이트 : 프로그래머스(PG)
- 문제: [외벽 점검](https://school.programmers.co.kr/learn/courses/30/lessons/60062)
- 번호: 60062
- 레벨: level3
```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 <= n <= 200
- 1 <= weak <= 15
- 1 <= dist <= 8
- `O(8!*15)`
   - 취약지점 리스트의 가능한 모든 지점에 대해 순열로 살핌
   - 최대 친구 수 만큼 재귀 호출 진행

### 💡 풀이 아이디어
- 기존 배열 확장하기
   - 반시계도 방향도 일자로 진행하기 위해 기존 배열 확장
- 1명부터 최대 친구수까지 데려갈 친구 수에 대한 순열 구하기
- 순열 `perm(int depth, int cnt, boolean[] visited, int[] take)`
   - 데려갈 친구를 담는 take배열과 방문 여부 visited를 통해 순열 구함
   - 데려갈 친구를 다 구하면 `check()` 진행
- `check()` : 데려간 친구 조합으로 모든 부분 커버할 수 있는지 확인 및 갱신
   - 첫번째 취약지점부터 시작, 각 친구별 시작 위치 설정
   - 현재 친구가 모든 취약 지점을 커버할 수 있다면 최소값 갱신
   - 모두 커버 못해서 다음 친구 필요하면, 현재 친구가 시작한 취약점 다음 취약점부터 조사 진행
   > 이 check함수부분이 뭔가 잘못된거같아서 답이 완벽하게 안나오고 있는것 같습니다...

> ㅠㅠ check함수 뭔가 좀만 더 보면 될거같긴한데... 새벽이라 머리 안돌아감 이슈 내일 아침에 한번 더 확인해보겠습니다... 우선 여기까지...

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- ~~weak의 길이는 1 이상 15 이하~~
- dist의 길이는 1 이상 8 이하
- dist를 기준으로 모든 조합 체크 &rarr; 8! 충분히 가능

### 💡 풀이 아이디어
- `그리디` + `재귀`를 이용한 풀이
- `그리디`: 탐색을 가장 멀리 할 수 있는 친구부터 탐색 보내기
  - 움직이는 방향은 한 방향으로 움직이면 됨 &rarr; 어차피 똑같음..! 
- `재귀`: 탐색되지 않은 곳으로 탐색 보내기
  - 깊이 = 탐색 보낸 친구의 수
- 모든 지점을 수리했는지 확인하기 위해서도 추가 연산이 필요하므로 `비트 마스킹`으로 방문처리
  ```java
  // 모든 외벽을 수리 했다면 갱신
  if (visited == (1 << w) - 1) {
      answer = Math.min(answer, depth);
      return;
  }
  ```
- 해당 탐색이 최선이 아닐 경우 탐색 종료
  ```java
  // 종료 조건
  // 깊이가 최대거나 최선의 선택이 아닐 경우
  if (depth == d || depth >= answer - 1) {
      return;
  }
  ```
- 많이 움직일 수 있는 친구부터 시계방향(인덱스가 증가하는 방향)으로 수리
- 다음 친구는 마지막으로 수리된 곳부터 수리 시작
  ```java
  // 많이 움직이는 친구부터 선택
  int move = dist[d - 1 - depth];
  for (int i = p; i < w; i++) {
      int next = visited;             // 다음 방문 배열
      int l = weak[i], r = l + move;  // 해당 친구가 탐색하는 범위
      int idx = i;
      // 수리가 가능한 범위까지 탐색
      while (isPossible(l, r, weak[idx], weak[idx] + n)) {
          // 이미 수리를 한 곳이라면 종료
          if ((next & (1 << idx)) == 1)
              break;
          next |= (1 << idx);
          idx++;
          // 원형 배열이므로 인덱스 초기화
          if (idx >= w)
              idx %= w;
      }
      // 다음 친구를 사용하여 탐색 진행
      judge(depth + 1, idx, next, n, weak, dist);
  }
  ```
> 캐빡세네요.. 별 방법을 다 써서 최적화 했습니다.. 
정답률 0.1%인게 이해갑니다

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
1<n<200, weak<=15, dist<=8 -> 구현


### 💡 풀이 아이디어
1. exteanedeWeak : 원형 배열 -> 선형 배열로 변환 (*2)
2. 취약 지점을 시작점으로 설정하여 점검 가능한 범위 계산
- 취약 지점을 순회 -> 점검 불가능한 지점 발견 -> 투입된 친구 수(count)를 증가 

구현하지 못한 것 
1. 친구의 이동 거리를 고려하지 못함
2. 점검 범위 갱신
>  프로그래머스 정답률 31% 이길래 평범한 문제인줄 알았습니다.. 제가 왜 그랬을까요..ㅠ_ㅠ

**Comment by KodaHye** [comment]
* dist 길이로 외벽을 설치할 수 있는 곳의 시작점(weak)들 고르기 

![image](https://github.com/user-attachments/assets/09e04bfb-781f-48fa-8f9b-c295380bab74)
```java
import java.util.*;

class Solution {
	static boolean[] v;
	static int[] sel;
	static int result;
	static HashSet<Integer> weakSet;
	
	static int solution(int n, int[] weak, int[] dist) {

		result = Integer.MAX_VALUE;
		weakSet = new HashSet<Integer>();
		sel = new int[dist.length];
		v = new boolean[weak.length];
		
		Arrays.sort(dist);
		
		for(int w: weak) weakSet.add(w);
		
		// 1 ~ weak개수 중에서 dist개 순서 고르기(순열)
		perm(0, 1, weak, dist, n);
		
		return result == Integer.MAX_VALUE? -1: result;
	}
	
	static void perm(int depth, int idx, int[] weak, int[] dist, int n) {
		if(depth == dist.length) {
			// sel에서는 각각 dist에 대한 idx가 어디에서 시작되는지 저장하고 있음
			
			HashSet<Integer> copySet = (HashSet<Integer>) weakSet.clone();
			
			for(int i = dist.length - 1; i >= 0; i--) {
				int start = sel[i];
				int end = start + dist[i];
				
				for(int s = start; s < start + end + 1; s++) {
					s %= n;
					
					if(copySet.contains(s)) {
						copySet.remove(s);
					}
					
					if(copySet.size() == 0) {
//						System.out.println(Arrays.toString(sel) + " " + (dist.length - (i)));
						result = Math.min(result, dist.length - (i));
						break;
					}
				}
			}
			
			return;
		}
		
		for(int i = 0; i < weak.length; i++) {
			if(v[i]) continue;
			v[i] = true;
			sel[depth] = i;
			perm(depth + 1, i + 1, weak, dist, n);
			v[i] = false;
		}
	}
	public static void main(String[] args) {
		int n = 12;
		int[] weak = {1, 3, 4, 9, 10};
		int[] dist = {3, 5, 7};
		
		System.out.println(solution(n, weak, dist));
	}
}

```
