### ISSUE TITLE
[12주차_금요일] 사회망 서비스(SNS)

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#162]
- 사이트 : 백준(BOJ)
- 문제: [사회망 서비스(SNS)](https://www.acmicpc.net/problem/2533)
- 번호: 2533
- 레벨: 골드3

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 1,000,000 (10^7)
- 완전탐색불가
- dp시 모든 노드들을 한번씩 탐색하므로 O(N)


### 💡 풀이 아이디어
- `DP이용`
   - 하위 노드 값에 따라 상위 노드 값이 정해짐
   - 어답터일때, 아닐대 2가지 상태로 나타낼 수 있음
- 초기화
   - 각 노드는 자신이 x로 `setAdaptor()`가 호출될때, 자신이 어답터인경우 1값을 초기화함.
- 자식 노드 탐색
   - 시작은 루트노드로 호출되나, 자신(x)의 값이 정해지는건 자식들에 의해서임
   - 따라서 자식들을 다 돌면서 자식의 값을 세팅(`dp[x][1] = 1`) 해준 후, 그 값을 바탕으로 자신의 값 결정
- 점화식
   - 내가 어답터X → 자식이 어답터야함
   - 내가 어답터O → 자식이 뭐든 상관없음(최소값 사용)
   ```java
   private static void setAdaptor(int x) {
        visited[x] = true;                      // 현재 값 방문 처리
        dp[x][1] = 1;                           // 자신의 얼리어답터 수 1 설정 (자신의 dp에서 얼리어답터일때 값 초기화)

        for (int nxt : adj.get(x)) {            // 일단 리프노드까지 자식들 탐색
            if (visited[nxt]) continue;         // 부모 노드일 경우 패쓰
            setAdaptor(nxt);                    // 자식들을 탐색하는 과정에서 자식들의 얼리어답터 값 1로 세팅 됨

            // x(자신)의 dp비용은 자식들에 의해서 정해짐 (딸린 자식들의 경우들에 따라 정해짐)
            dp[x][0] += dp[nxt][1];             // 내가 얼리어답터가 아니려면 자식이 어답터여 함
            dp[x][1] += Math.min(dp[nxt][1], dp[nxt][0]);       // 내가 얼리어답터면, 자식이 뭐든 상관없기에 최소값 사용
        }
    }
   ```
- 최종적으로 정해진 루트 1값의 최소값 반환
- 주의해야할 점
   - 그래프는 양방향으로 설정. (주어지는 입력이 부모 자식 관계가 확실하지 않음)
   - visited는 자식노드 탐색 시 부모노드를 걸러주는 역할

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 2 ≤ N ≤ 1,000,000

=> 완전탐색 불가
=> O(N)으로 생각해보기

### 💡 풀이 아이디어

- DP 활용
    - 얼리어답터인 경우 or 얼리어답터가 아닌 경우
    - dp[i][0] : i번쨰(부모)가 얼리어답터가 아님 => 자식들이 모두 얼리어답터
    - dp[i][1] : i번쨰(부모)가 얼리어답터임 => 자식들이 얼리어답터인지는 상관X, 최소 얼리어답터 구하기
   - 초기화 => 얼리어답터인 dp[][1]을 1로 초기화
    ```java
		// dp[p][0] : 부모가 얼리어답터 X
		// dp[p][1] : 부모가 얼리어답터 O
		dp = new int[N+1][2];
		for(int i=0; i<N+1; i++) {
			dp[i][1] = 1;
		}
    ```
- dfs로 자식 얼리어답터 탐색하기
```java
	public static void dfs(int now) {
		for(int next: g[now]) {
			if(visited[next]) continue;
			visited[next] = true;
			dfs(next);
			// now가 얼리어답터가 아니라면 자식들이 모두 얼리어답터
			dp[now][0] += dp[next][1];
			// now가 얼리어답터라면 자식들 중 최소 얼리어답터 구하기
			dp[now][1] += Math.min(dp[next][0], dp[next][1]);
		}
	}
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 2 ≤ 트리 정점의 개수(n) ≤ 1,000,000
* 양방향 그래프이므로 간선의 개수: 2 * (n - 1) = 약 3,000,000
* 100 * O(N + V) 이내로 문제 풀이 해야됨



### 💡 풀이 아이디어

* 모든 리프노드의 부모는 무조건 얼리어답터가 됨!
  * 그래프를 변형해가면서 리프노드를 만들어가고, 얼리어답터를 찾아나가기 (BFS)
* `Queue<Integer> q`: 리프노드를 저장할 변수
* `boolean[] v` : 어떤 노드인지 확인 과정을 거쳤는지 체크하는 변수


![image](https://github.com/user-attachments/assets/f7133192-a3eb-43a9-8a6d-2915782f6d54)

1. 초기 그래프에서 리프노드들을 큐에 넣어줌
   * 리프노드는 `adj[].size() == 1`인 노드임
2. 큐가 빌 때까지 얼리어답터 찾아주기
   * 리프노트는 그냥 확인해줬다는 표시만 해주기
     * `v[current] = true`
   * 리프노드와 이어져 있는 노드(부모) 찾기
     * 리프노드와 이어져 있는 노드(부모)는 무조건 얼리어답터가 됨
   * 부모노드에 들어오는 간선 없애기
     * 간선의 시작점이 되는 노드의 간선이 1개가 된다면, 해당 노드는 다시 리프노드가 됨 → 큐에 넣어주기

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- n<=1,000,000, 사이클 없는 그래프 간선 n-1개
- O(V+E) = O(2n-1) = `O(N)`


### 💡 풀이 아이디어
- 구하는 것 : 최소한의 얼리어 답터로 모든 노드 아이디어 수용 
- DFS로 자신이 얼리어 답터 O or X 경우 모두 탐색
- 루트 노드 두 가지 상태 중 최솟값을 출력
- `dp[node][0]` : 자신이 얼리어 답터X -> 모든 자식 노드가 얼리어 답터O
```java
dp[node][0] = dp[node][0] + dp[c][1]; // 자식이 얼리어 답터
```
 - `dp[node][1]` : 자신이 얼리어 답터O -> 모든 자식 노드 아이디어 수용O  
```java
dp[node][1] = dp[node][1] + Math.min(dp[c][0], dp[c][1]); // 얼리어답터O or 얼리어답터X
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 1,000,000 &rarr; 10^6 &rarr; O(n logn)으로 풀이

### 💡 풀이 아이디어
- `트리에서의 DP`를 이용
- 부모 노드가 얼리 아답터임: 자식이 얼리 아답터가 아니어도 상관 없음
- 부모 노드가 얼리 아답터가 아님: 자식들은 무조건 얼리 아답터이어야 함
- `dp[i][0]`: i노드가 얼리 아답터가 아닐 경우의 경우의 수
- `dp[i][1]`: i노드가 얼리 아답터일 경우의 수
```java
dp[u][0] += dp[v][1]; // u가 얼리 어답터가 아닐 때, 자식 노드는 반드시 얼리 어답터여야 함
dp[u][1] += Math.min(dp[v][0], dp[v][1]); // u가 얼리 어답터일 때, 자식 노드는 얼리 어답터일 수도 아닐 수도 있음
```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: dfs + 트리 + dp
- 시간복잡도: `2 ≤ N ≤ 10^6`

### 💡 풀이 아이디어
- 얼리 아답터가 아닌 사람들은 자신의 모든 친구가 얼리 아답터이기 때문에 새로운 아이디어를 받아들인다
   - ~~자식이 얼리어답터라면 부모도 얼리어답터가 된다~~
- 자식은 얼리어답터 일 수도 있고, 얼리어답터가 아닐 수도 있다.
   > 근데 왜 이부분에서 최소값을 통해서 결정하는지 이해가 안돼요 ㅜㅜ..
1. 루트 노드에서 출발하여 모든 노드를 DFS 탐색하면서 얼리어답터일 경우(`dp[i][1] = 1`)와와 아닌 경우(`dp[i][0] = 0`)를 dp 초기값으로 셋팅한다
2. dfs 탐색을 리턴하면서 최소 얼리어답터 노드수 계산하기
