### ISSUE TITLE
[12주차_금요일] 파일명 정렬

### ISSUE THREAD

**Issue by icegosimperson** [GreatAlgorithm-Study/AlgorithmStudy#163]
- 사이트 : 프로그래머스(PG)
- 문제: [파일명 정렬](https://school.programmers.co.kr/learn/courses/30/lessons/17686)
- 번호: 17686
- 레벨: level2

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- files 1000 개 이하
- 구현으로 딱히 고려하지 않음


### 💡 풀이 아이디어
- 문제 조건대로 설계하기
- 각 파일을 File객체로 만들기
  - `String head, String num, String tail, int order`를 필드 값으로 가짐
  - `compareTo()` : 파일 정렬 시 사용
  - `toString()` : 파일 객체를 다시 문자열로 반환
- **파일 String을 객체로 만들기**
   - head 찾기
      - idx가 숫자 만날때까지 움직인 후 `head = f.substring(0, idx);`
   - num 찾기
     - 최대 5글자이나 이보다 작을 수 있음 `idx < Math.min(stN + 5, cf.length)`
     - 문자 만날때까지 움직인 후 `num = f.substring(stN, idx)`
     - **예외처리**
        - 문자를 만날때 num이 확정되는데 끝까지 숫자로 이뤄질 경우 num을 설정하지 못함
        - 따라서 `if (num == null) num = f.substring(stN, idx);` 조건으로 예외 처리 진행
   - tail 찾기
     > tail이 빌 수 있다는 조건 까먹지 말기
     - `tail = ""` : 비었을 수 있기에 빈 문자열로 초기화
     - 최종적으로 움직인 idx가 범위를 넘지 않는다면 남은 부분이 있는 것임 `f.substring(idx);`
- **파일 정렬**
   - head 사전순 비교
      - `int headCmp = this.head.compareToIgnoreCase(o.head);`
      - 대소문자 구분 안하는 `compareToIgnoreCase()`이용
   - num 숫자 변환 후 비교
      - `int numCmp = Integer.compare(Integer.parseInt(num), Integer.parseInt(o.num));`
   - 마지막 입력 순으로 정렬 
      - `return this.order - o.order;`

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* files: 1000(n)개 이하의 파일명을 포함하는 문자열 배열
* n ^ 2 이하가 되도록 해야될 것 이라고 생각함



### 💡 풀이 아이디어

* 문제에서 주어진 조건대로 정렬을 수행하면 될 것 이라고 생각
  1. HEAD 부분을 우선으로 고려하며 정렬
     * 대소문자를 비교하지 않으며, 문자열이 같을 때, 입력 순서를 유지할 것
  2. NUMBER 비교
     * 숫자 앞에 0이 있으면 무시하고, 그냥 일반적인 정수라고 생각해서 순서를 고려할 것
  3. HEAD, NUMBER가 비교되었으면, 그 이후는 입력 순서를 유지할 것

> HEAD와 NUMBER를 통해 순서를 비교하면 되므로, TAIL은 고려하지 않아도 됨!

<br>



* `FileInfo` 클래스
  * `int idx`: `files` 배열에서 몇 번째인지
  * `String head`: `files[i]`의 `head` 저장(숫자 전까지의 문자열)
  * `int number`: `head` 이후 나오는 숫자
  * 문제 조건에 제시된 대로 `compareTo` 설정
    ```java
    @Override
    public int compareTo(FileInfo o) {
        if(this.head.equals(o.head)) return Integer.compare(this.number, o.number);
        return this.head.compareTo(o.head);
    }
    ```
* `ArrayList<FileInfo> fileList`
  * `String[] files`에서 각각의 파일에 대해 `FileInfo`정보 (`idx`, `head`, `number`) 구하기
    ```java
    String file = files[idx];
    
    // HEAD 구성하기
    int currentIdx = 0;
    for(int i = 0; i < file.length(); i++) {
        char ch = file.charAt(i);
        if(ch - '0' >= 0 && ch - '0' < 10) break;
        currentIdx += 1;
    }
    
    String head = file.substring(0, currentIdx);
    
    // NUMBER 구성하기
    int startIdx = currentIdx;
    for(int i = currentIdx; i < file.length(); i++) {
        char ch = file.charAt(i);
        if(ch - '0' < 0 || ch - '0' >= 10) break;
        currentIdx += 1;
    }
    
    String number = file.substring(startIdx, currentIdx);
    
    fileList.add(new FileInfo(idx, head, number));
    ```
* `fileList`에 파일들의 정보를 모두 입력했다면 정렬한 이후, `String[] answer`에 정렬된 순서의 파일 정보 담기

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- files 배열 길이 <= 1000
- file 문자열 길이 <= 100

=> 완전탐색 가능

### 💡 풀이 아이디어
- File 객체를 선언해서 Compareble로 우선순위 정하기
```java
    static class File implements Comparable<File> {
        String name, head, tail;
        int number, idx;
        public File(String name, String head, int number, String tail, int idx) {
            this.name = name;
            this.head = head;
            this.number = number;
            this.tail = tail;
            this.idx = idx;
        }
        
        @Override
        public int compareTo(File other) {
            if(this.head.equals(other.head)) {
                if(this.number == other.number) {
                    // 3) 입력 순(인덱스)
                    return this.idx - other.idx;
                }
                // 2) 숫자 순
                return this.number - other.number;
            }
            // 1) head 사전순
            return this.head.compareTo(other.head);
        }
```
- `Charater.isDigit(ch)` : 문자 ch가 숫자인지 판단
    - ch가 숫자라면 number로 저장
    - number의 개수가 5개 이상이라면 tail로 넘어가기

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리: 문자열, 정규식
- 시간복잡도: files는 1000 개 이하로 고려하지 않음

### 💡 풀이 아이디어
- 파일명 조건에 따른 정규식 HEAD/NUM/TAIL 별로 만들기
   - ([`a-zA-Z` `\\s` `\\-` ]+)(`[0-9]` `{1,5}`)( `.*` )
   - 영문 _대소문자_, _숫자_, 공백(" "), _마침표(".")_, _빼기 부호("-")_만으로 이루어지고, 
   - 파일명은 영문자로 시작하며, 숫자를 하나 이상 포함
   - HEAD는 숫자가 아닌 문자로 이루어져 있으며, 최소한 한 글자 이상이다.
   - NUMBER는 한 글자에서 _최대 다섯 글자_ 사이의 _연속된 숫자 (0~9)_
- 정규식 `find` 메소드를 통해 각 정규식이 맞는지 확인하고 `group` 별로 꺼내기
- 정렬
   ``` java
     @Override
     public int compareTo(File o) {
         //1. HEAD 사전순으로 정렬, 대소문자 구분X 2. NUMBER의 숫자 순으로 정렬
         int order = this.head.toLowerCase().compareTo(o.head.toLowerCase());
         return order == 0 ? Integer.parseInt(this.num) - Integer.parseInt(o.num) : order;
     }
   ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- files는 1000 개 이하의 파일명을 포함하는 문자열 배열 &rarr; 10^3이므로 O(N^3) 이하로 풀이

### 💡 풀이 아이디어
- 정규표현식을 이용하여 그룹으로 나누기
  ```java
  String regex = "^([^0-9]+)([0-9]{1,5}).*$";
  ```
- 해당 그룹을 기준으로 배열을 만들어서 문제에 맞게 정렬
  ```java
  Arrays.sort(strArr, (s1, s2) -> !s1[1].equals(s2[1]) ? s1[1].compareTo(s2[1])
                                            : Integer.parseInt(s1[2]) - Integer.parseInt(s2[2]));
  ```
- 입력 순서도 보장해야 하므로 안정 정렬을 이용

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 파일 1000개 이내 : 고려X


### 💡 풀이 아이디어
- 정규식으로 HEAD, NUMBER, TAIL 부분 나눠서 정렬하기
```java
String regex = "^([^0-9]+)([0-9]{1,5}).*$";
```
- `([^0-9]+)` : HEAD 숫자가 아닌 문자로 구성
- `([0-9]{1,5})` : NUMBER 1~5자리의 연속된 숫자
- `(.*)` :TAIL 나머지 모든 부분

1) `HEAD` : 대소문자 구분(toLowerCase())X
  - CompareTo() 사전 순 비교
2) `NUMBER` : 정수로 변환하여 숫자값 비교
  - Integer.compareTo()
- HEAD와 NUMBER가 동일할 경우 입력 순서 유지
