### ISSUE TITLE
[13주차_월요일] 술래잡기 체스

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#171]
- 사이트 : 코드트리(CT)
- 문제: [술래잡기 체스](https://www.codetree.ai/training-field/frequent-problems/problems/odd-chess2/description?page=2&pageSize=20)
- 년도: 2020

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 4 x 4 보드에서의 구현 문제라서 신경쓰지 않음

### 💡 풀이 아이디어
- 재귀적으로 경찰(술래)이 이동할 수 있는 모든 경우를 탐색
  `재귀 설계`
  1. 경찰이 도둑을 잡고 점수 계산
  2. 최댓값 갱신
  3. 보드에서 경찰 좌표(잡힌 도둑의 좌표)의 순서를 `0`으로 변경
  4. 도둑들 이동
  5. 다음 경찰의 좌표를 계산 후 재귀 호출
      - 보드를 복사하여 전달
      - 도둑이 있는 곳으로만 이동 가능
- 경찰이 이동한 곳의 순서를 `0`으로 변경하여 도둑들이 순서에 따라 이동할 때 이동하지 않도록 함
  - 도둑들의 번호는 1 ~ 16

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N = 4
- 4 * 4 격자
- 한 턴에 술래가 이동할 수 있는 칸 수 : 총 3칸

=> 술래가 이동할 수 있는 모든 칸을 재귀로 탐색 : 3^(N^2) = 3^16
=> 술래는 총 N * N칸에 위치할 수 있음
=> O(3^16 * (N * N))
=> 완전탐색 가능

### 💡 풀이 아이디어
- 재귀함수 활용 : 술래가 갈 수 있는 최대의 도둑을 잡기 위해서는 모든 탐색을 진행해야 함
- `int[][] g[i][j]` : 도둑들의 번호를 기록하는 배열
- `int[][] prr[n]` : 번호가 n인 도둑의 정보(new int[] {방향, x좌표, y좌표})
- `boolean[] isDied[n]` : 술래에게 잡힌 도둑 정보 저장 배열

**0. 초기 도둑 잡기**
- (0, 0)에 위치한 도둑을 잡고 술래의 방향 구하기
  
  
**1. 술래잡기 재귀함수 호출**
- play(sx, sy, sDir, total, g, prr)
    ```
    - sx, sy : 술래의 좌표
    - sDir :  술래의 방향
    - total : 잡은 도둑말의 점수
    - g : 도둑들 번호 기록 배열
    - prr : 도둑들 정보 기록 배열(방향, x좌표, y좌표) 
    ```
- 1.1 원본배열 복사하기 => copy g & prr
    - 매개변수로 받은 배열은 주소값이 전달되므로 함수 내에서 원본값이 변경됨
    - 따라서 이를 방지하기 위해 원본배열을 복사
    - t = g;
    - trr = prr;
- 1.2 도둑들 움직이기 (복사된 배열을 전달)
    - `movePlayer(sx, sy, t, trr)`
    - 이 함수를 실행하면 복사된 배열인 `t`와 `trr`이 변경되서 도둑들의 움직임을 나타냄
- 1.3 술래 움직이기 (복사된 배열을 전달)
    - 술래 다음 위치 도둑 잡기
    - 재귀함수 호출
    - 위에서 잡은 도둑 원상복귀하고 다른 칸 탐색하기
    ```java
	// 2) 술래 움직이기
	for(int c=1; c<N; c++) {
		int nx = sx + c*dx[sDir];
		int ny = sy + c*dy[sDir];
			
		if(!inRange(nx, ny)) break;
		if(t[nx][ny] == 0) continue;
			
		// 움직일 수 있음
		int pNum = t[nx][ny];
		isDied[pNum] = true;
		t[nx][ny] = 0;
		play(nx, ny, trr[pNum][0], total+pNum, t, trr);
		t[nx][ny] = pNum;
		isDied[pNum] = false;
	}
    ```
- 1.4 술래가 더이상 움직일 곳이 없다면, 현재까지 잡은 도둑값 저장하기

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
N=4x4
술래 번호(k) <=16, 모든 술래 번호 탐색 시 시간초과 -> 재귀

### 💡 풀이 아이디어
1. `class Node(int p, int d)` : 체스의 번호(p), 거리(d) 나타냄
- `Node[][] board`: p, d-1 입력 받기 
- 술래말 초기화 후 도둑말 이동 시작
2. `dfs()` : 재귀 탐색
- `Math.max(ans, score)` : 도둑말 이동하며 점수 갱신
- 술래말이 원래 있던 칸은 비우면서, 이동
3. `find()` : 도둑말 번호를 순서대로 탐색
- `visited(방문처리)` 시간초과 방지
5. `move() `: 체스말 이동
- 이동 가능 조건 : 술래말이 있는 칸X, 경계를 벗어나지X, 
- 새 위치로 이동하면서 기존 위치 업데이트
- `d = (d+1) % 8`: 반시계 방향 45도 회전 
6. `Node[][] copy` : 체스말 이동을 위해 복사 배열 만들기

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 보드판: 4 * 4 
- 술래가 갈 수 있는 최대 횟수: 3
- 술래의 이동 경우의 수: 3^16
- 술래가 위치할 수 있는 칸 수: 16
- O(3^(N^2*N^2)) 가능

### 💡 풀이 아이디어
- 구조
   - 술래 객체 (`Tagger`) : x, y, dir, cnt
   - 도둑말 객체(`Piece`) : idx, x, y, dir, isDie
   - int[][] board : 보드
   - List<Piece> pieces : 도둑말들 저장
1. 도둑말은 작은 순으로 진행하기에 리스트 정렬
2. 초기 도둑말 잡은 후 재귀(dfs) 시작
- `dfs`
   - 도둑말들 움직이기 (`moveThief()`)
   - 현재 술래 방향으로 잡을 수 있는 말 잡기 (최대 3칸의 거리 이동 가능)
      - 잡을 수 있다면 도둑 잡기
        - 이때, tmp 술래말을 새로 생성해 갱신된 정보의 술래를 재귀로 돌릴 dfs로 넘김
        - board, 도둑말 리스트 모두 깊은 복사로 dfs 넘기기
- `moveThief`
   - 죽지않고 술래가 아닌 말들에 대해 진행
   - 이동할 곳이 비었으면 바로 이동
   - 이동할 곳에 다른 말이 있으면 위치 교환   
- 주의할 점
   - 삼성 구현문제인 만큼 초기 설계 깔끔하게 똑바로 하기..
      - 처음엔 말들을 리스트가 아닌 해시맵으로 관리하려했는데 복잡한 생각이였음..
   - dfs 재귀인 만큼 원본배열이 훼손되지 않게 복사 똑바로하기
      - 도둑 리스트 깊은 복제
         - 처음엔 도둑말의 `isDie`필드는 생성자에서 초기화 안해주고 미리 false로 처리했었음.
         - 이렇게되면 새로운 객체를 복사할때 기존 객체의 isDie여부를 알 수 없기에 애초부터 생성자로 같이 받음
      - 술래객체도 새로운 객체로 제대로 복사하기

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: ~~BFS~~  모든 경우를 다 고려한 DFS + 구현
- 시간복잡도: (4 x 4의 격자) * 3(술래의 움직임)

### 💡 풀이 아이디어
항목 | 설명
-- | --
`Chess.class` | 도둑말 클래스 (좌표, 순서, 방향)
`Chess[][] game` | 모든 도둑말이 저장된 체스판
~~`PriorityQueue<Chess>`~~ | ~~모든 도둑말을 순서대로 움직이기 위한 우선순위 큐~~ 리스트로 변환해서 정렬하기
`Chess tagger` | 술래 위치 저장

1. 우선순위 큐에서 말들을 하나씩 꺼내면서 자리 교체하기
   1-2. 8방향 반시계 방향으로 교체할 자리있는지 찾고, 없다면 기존 위치 유지
2. 자리를 모두 교체했다면 다음 순회를 위해 우선순위 큐에 자리 옮겨진 술래들 추가하기
3. ~~술래가 갈 수 있는 8방향 BFS 탐색~~ > 술래는 자신이 잡은 술래말의 방향으로 이동
   3-2. 이때 발견한 가장 큰 도둑말의 순서를 계속해서 갱신
   3-3. BFS 탐색 후 가장 큰 도둑말의 위치로 술래 이동 후 점수 추가
   도둑말이 없다면 게임 종료

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 4 × 4 격자에서 술래 말이 (0, 0)에서 시작해서 최대 3칸 이동
  * 술래가 끝까지 도달할 수 있는 경우의 수: 27
* O(n) = 27 + α (도둑 이동, 객체 복사, ...)



### 💡 풀이 아이디어

* 구조

  * `Node`: 도둑말에 대한 정보 저장
    * `int r, c, dir;` // 위치, 바라보는 방향
    * `boolean isDie;` // 잡혔는지 여부
  * `Node[] nodes`: 도둑말을 배열로 저장 
    * 배열의 크기: 17 (∵ 술래의 idx는 1부터 시작)
  * `int[][] map` : 도둑말의 idx 저장
  * 술래에 대한 정보는 따로 객체로 만들지 않음

* 함수

  * `dfs(int r, int c, int d, int sum)`

    * `r, c, d`: 술래의 정보
    * `sum`: 점수의 합계
    * `map[r][c]`: 잡히는 도둑말의 idx
      * 도둑말이 잡히면 `nodes[target].isDie`의 값만 `true`로 바꿔줌
      * 도둑말이 잡혔다고 해서, `map[r][c]`의 값을 0으로 바꾸지 않음 (나중에 도둑말들이 이동할 때, 인덱스 가 0인 것을 따로 처리해줄 때 복잡해지기 때문)
      * 재귀호출하기 이전에 `nodes`와 `map`에 대한 정보를 복사해 줌
      * 재귀호출 이후, `nodes`와 `map`에 대한 정보를 원상복구해줌

  * `move(int r, int c, int idx, Node[] nodes, int[][] map)`

    * 술래의 위치가 `r, c`이고, 이동하는 도둑말의 번호가 `idx`일 때 도둑말 움직이기

  * `copyMap()`: 2차원 배열을 복사해주는 함수(깊은 복사)

  * `copyNodes()`: 객체 배열을 복사해주는 함수(깊은 복사)
