### ISSUE TITLE
[13주차_화요일] 달이 차오른다, 가자

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#172]
- 사이트 : 백준(BOJ) 
- 문제: [달이 차오른다, 가자](https://www.acmicpc.net/problem/1194)
- 번호: 1194

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 ≤ 미로의 세로 크기, 가로 크기 ≤ 50 
  * 64 * 50 * 50 * 4
* BFS를 통해 갈 수 있는 곳을 파악해야 되므로 방문 배열 체크 잘 하는 것이 중요
  

### 💡 풀이 아이디어

* BFS를 통해 현재 내가 가지고 있는 열쇠 상태에 따라서 갈 수 있는 곳인지 확인
* 문에 대응하는 열쇠를 확인하기 위해 비트마스킹 사용
* 가지고 있는 열쇠에 따라 방문 배열을 확인해주기 위해 방문 배열은 `boolean[][][] v = new boolean[1 << 6][N][M]`으로 선언함
  > `1 << 6`: 현재 가지고 있는 열쇠에 대한 모든 상태값

  > 처음에는 `int[][][] v = new int[6][N][M]`로 선언(내가 마지막으로 가진 키가 k 이고, r, c 지점을 갈 경우)하고, `v`에 가지고 있는 열쇠의 상태(status)를 저장해줬는데, 이렇게 하면 정답은 나오지만, 중복된 값들이 계속 처리돼서 메모리 초과가 발생했습니다!
* `isDoor(map[nr][nc])`: 다음 지점이 문인 경우
  * `(current.status & (1 << map[nr][nc] - 'A') == 0)`
    * 가지고 있는 열쇠 상태로 문을 열수 없다면, continue
* `isKey(map[nr][nc])`: 다음 지점에 열쇠가 있는 경우
  * `nstatus |= (1 << map[nr][nc] - 'a')`
    * 열쇠 상태 업데이트 해주기

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N, M ≤ 50
- 알파벳 개수 6개
   - 비트마스킹 이용 시 : 2^6 = 64
- 3차원 visited: N * M * 64 
   - 50 * 50 * 64=160,000 

### 💡 풀이 아이디어
- 열쇠의 획득에 따라 방문할 수 있는 곳이 달라짐 + 방문처리 또한 달라짐 → `3차원 방문처리` 이용
- 3차원 방문 처리 (`visited[x][y][k]`)
   - k는 획득한 열쇠의 개수로 생각하고 진행
   - 이때, k의 처리를 효율적으로 하기위해 `비트마스킹` 이용
- 다음 이동할 곳이 알파벳인 경우
   - `if (Character.isLowerCase(nxt))` : 소문자일 경우 열쇠이기에 줍기
      - `nk |= (1 << (nxt - 'a'))`
      - 이동할 곳(nxt)의 알파벳 번호를 1로 바꾼 후 현재 들고있는 키(nk)와 or 연산
   - `Character.isUpperCase(nxt)` : 대문자일 경우 문이고, 키가 없는 문은 못감
      - `if ((nk & (1<< (nxt-'A')))==0) continue;`
      - 이동할 곳(nxt)의 알파벳 번호를 1로 바꾼 후 현재 들고있는 키(nk)와 and연산으로 가지고 있는 키인지 확인
- 이후 bfs 진행

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N, M ≤ 50, 열쇠의 개수 6
- 열쇠의 개수에 따라 `BFS`를 진행 &rarr; 50 x 50 x 2^6이므로 가능

### 💡 풀이 아이디어
- 이동할 수 있는 보드에서 최단 거리 찾기 &rarr; `BFS`
- 현재 가지고 있는 열쇠에 따라서 이동할 수 있는 곳이 달라짐 &rarr; 3차원 방문 체크
- 열쇠의 상태를 방문 체크에서 인덱스로 사용하기 위해 `비트 마스킹`을 이용
  ```java
  boolean[][][] visited = new boolean[n][m][1 << 6]; // 가지고 있는 열쇠에 따른 방문 체크
  ```
- BFS
  - `1`에 도착하면 현재 움직임 카운트를 출력 후 종료
  - 다음 좌표의 상태에 따라 이동 결정
    - 경계를 넘어감, 벽, 방문한 곳 &rarr; 이동 불가
    - 열쇠일 경우 &rarr; 열쇠 상태를 변경
      ```java
      newKeys |= (1 << (board[ny][nx] - 'a'));
      ```
    - 문일 경우 &rarr; 해당 문에 대한 열쇠를 가지고 있을 경우만 이동
      ```java
      else if (isDoor(ny, nx) && (keys & (1 << (board[ny][nx] - 'A'))) == 0)
          continue;
      ```
    - 이동
      ```java
      if (!visited[ny][nx][newKeys]) {
          dq.offer(new int[] { ny, nx, newKeys, moveCnt + 1 });
          visited[ny][nx][newKeys] = true;
      }
      ```
- 각종 체크 함수화
  ```java
  // 열쇠 체크
  private static boolean isKey(int y, int x) {
      return 'a' <= board[y][x] && board[y][x] <= 'f';
  }
  
  // 문 체크
  private static boolean isDoor(int y, int x) {
      return 'A' <= board[y][x] && board[y][x] <= 'F';
  }
  
  // 경계 체크
  private static boolean isValid(int y, int x) {
      return 0 <= y && y < n && 0 <= x && x < m;
  }
  ```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N, M <= 50
- 키 개수, 문 개수 <= 6

=> O(N * M * 2^6)
=> 완전탐색 가능

### 💡 풀이 아이디어

- 열쇠 상태 객체 선언
    - dist: 움직인 거리
    - key: 획득 한 키들
    ```java
	static class State {
		int x, y, dist, key;
		public State(int x, int y, int dist, int key) {
			super();
			this.x = x;
			this.y = y;
			this.dist = dist;
			this.key = key;
		}
	}

    ```
- 획득한 열쇠 상태 저장 -> **비트마스킹** 이용
    - 'f' 획득 => new key = key | (1 << 'f' - 'a')
    - 'f' 획득 여부 => key & (1 << 'f' - 'a')
- 열쇠를 획득하고 다시 돌아갈 때 방문처리하기 -> **3차원 방문 배열** 활용
    - `visited[64][N][M]`
    - 열쇠를 획득한 후에 다시 왔던 길을 탐색할 수 있어야 하므로 열쇠마다 방문리스트 생성

- 문 방문 시: 열쇠 가지고 있는지 확인
- 열쇠 방문 시: 열쇠 획득 
```java
	int key = now.key;
	// 문 방문
	if(isDoor(g[nx][ny])) {
	        int hasKey = key & 1 << (g[nx][ny] - 'A');
		// 열쇠 없음
		if(hasKey == 0) continue;
	}
	// 열쇠 방문
	else if(isKey(g[nx][ny])) {
		int newKey = key | (1 << g[nx][ny]-'a');
		if(visited[newKey][nx][ny]) continue;
		// 현재 키 방문 처리
		visited[key][nx][ny] = true;
		// 키 변경
		key = newKey;
	}
				
	// 그외 방문 가능 & 방문 처리
	visited[key][nx][ny] = true;
	q.add(new State(nx, ny, now.dist+1, key));

```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
- 열쇠 정보 객체 선언
```java
    static class Node{
        int x, y, key, step;
        public Node(int x, int y, int key, int step) {
            this.x = x;
            this.y = y;
            this.key = key;
            this.step = step;
        }
    }
```
- BFS를 통해 미로를 탈출하는데 드는 이동 횟수의 최솟값을 출력
- 비트마스킹을 통해 열쇠 획득 상태 저장
```java
               if ('a' <= board[nx][ny] && board[nx][ny] <= 'f') {
                    nkey |= (1 << (board[nx][ny] - 'a')); // 새로운 열쇠 획득
                }

                if ('A' <= board[nx][ny]&& board[nx][ny] <= 'F') {
                    if ((nkey & (1 << (board[nx][ny] - 'A'))) == 0) {
                        continue; // 열쇠 없으면 이동 불가
                    }
                }

                if (!visited[nx][ny][nkey]) { // 새 열쇠 상태로 방문
                    queue.add(new Node(nx, ny, nkey, cur.step + 1));
                    visited[nx][ny][nkey] = true;
                }
```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: BFS + 비트마스킹
- 시간복잡도: 1 ≤ N, M ≤ 50 > `O(N*M*2^6)`
`2^6` : key 의 갯수 6개에 대한 모든 이진수 상태

### 💡 풀이 아이디어
항목 | 설명
-- | --
`char[][] maze` | 각 칸 마다 문자 포함된 미로
`boolean[][][] visited` | [가로][세로][열쇠 유무]

- 모든 열쇠 조합에 따른 방문 상태 (63개)
   ``` text
   000000: 키가 없음 (0)
   000001: 첫 번째 키만 있음 (1)
   000010: 두 번째 키만 있음 (2)
   000011: 첫 번째와 두 번째 키가 있음 (3)
   ...
   111111: 모든 키가 있음 (63)
   ```
- 열쇠와 일치하는지 확인
   ``` java
   // A = 65
   key & 1<<(maze[nx][ny] - 'A')) > 0
   ```
- 열쇠 줍기
   ``` java
   // a = 97
   key |= 1<<(maze[nx][ny] - 'a') 
   ```
