### ISSUE TITLE
[13주차_수요일] 올림픽

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#173]
- 사이트 : 백준(BOJ)
- 문제: [올림픽](https://www.acmicpc.net/problem/8979)
- 번호: 8979

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 1,000 &rarr; 10^3이므로 O(N^3) 이하로 해결

### 💡 풀이 아이디어
- 조건에 맞게 정렬 후 출력
- 공동 점수가 나온다면 이전 등수와 동일
  - 그 사이 등수는 사라짐
```java
// 정렬
Arrays.sort(arr, (o1, o2) -> o2[1] != o1[1] ? o2[1] - o1[1] : o2[2] != o1[2] ? o2[2] - o1[2] : o2[3] - o1[3]);
int rank = 1;
// 등수 결정
for (int i = 0; i < n; i++) {
    if (i > 0 && !isSame(arr[i - 1], arr[i]))
        rank = i + 1;
    if (arr[i][0] == k)
        break;
}
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 1,000
- 완전탐색 가능


### 💡 풀이 아이디어
- 메달 정보에 따라 나라 정렬하기
   - 금은동 정보를 숫자로 치환
   - ex) 금(1) 은(2) 동(1) → 121
   - **이때, 하위 메달 값이 상위 메달 값을 침범하지 않도록 고정 숫자 크게 설정**
   ```java
   private static int medal2Int(int g, int s, int b){
        return g * 1000000 + s * 1000 + b;
    }
   ```
- 정렬한 정보를 바탕으로 동점자에 유의해 순위 매기기
   - tmp변수로 매번 순위를 카운트 해주고 rank변수는 동점자가 아닐때만 업데이트
   - 나라를 돌면서 K나라면 등수 출력

> 나라 정렬 시 숫자 비교하는 방법말고 금은동 compare로 비교하고, 순위 매길땐 같은 객체(금은동 정보같음)인지 판단해서 풀기도 했습니다..! (이 방법이 숫자 값에 따라 오류날 일도 없고 더 좋을거같기도..) 그런데 이때 객체 비교를 위한 equals랑 hashcode 재정의를 IDE가 없으면 힘들거같아서... 숫자변환 방법으로 올립니다!

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 ≤ 국가의 수 ≤ 1,000
* logN * N * N 까지 가능



### 💡 풀이 아이디어

* 금, 은, 동에 따른 순위를 `TreeMap<Node, Integer> map`으로 나타냄
  * `Node`: `int g`, `ing s`, `int b`
    * 금, 은, 동의 개수 저장
    * Comparable을 통해 정렬 사용하기
  * `Node`가 중복되어도, `TreeMap`에서는 중복 제거되는 것을 이용함
* 노드 별로 몇 개 씩 있는지, `value`를 저장하기
  ```java
  if(!map.containsKey(arr[idx - 1])) map.put(arr[idx - 1], 1);
  else map.put(arr[idx - 1], map.get(arr[idx - 1]) + 1);
  ```
* `map` 순회하면서 순위 구하기
  ```java
  for(Node n: map.keySet()) {
      if(current.g == n.g && current.s == n.s && current.b == n.b) {
          result = idx;
          break;
      }
      idx += map.get(n);
  }
  ```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- N<=1000 : `O(N)`


### 💡 풀이 아이디어
- 2차원 배열로 등수를 알고 싶은 국가(K)와 조건문으로 비교
- 비교하는 국가(i) == 등수를 알고 싶은 국가 : continue
```java
        for(int i=1; i<=N; i++){
            if(i==K) continue; // 자기 자신 건너뛰기
            if(board[i][0] > board[K][0]){
                rnk++;
            } else if(board[i][0] == board[K][0] && board[i][1] > board[K][1]){
                rnk++;
            } else if(board[i][0] == board[K][0] && board[i][1] == board[K][1] &&board[i][2] > board[K][2]){
                rnk++;
            }
        }
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 국가의 수 N <= 1000

=> 완전 탐색 가능

### 💡 풀이 아이디어
- Nation 객체 생성 후, Comparable을 상속받아 우선순위 설정
- 순위가 같은 국가들은 같은 랭킹 유지 -> 공동 랭킹이 생기면 중간 랭킹은 사라짐
```java
for(int i=1; i<N; i++) {
	Nation pre = nList.get(i-1);
	Nation now = nList.get(i);
	// 현재 랭킹 유지
	if(pre.g == now.g && pre.s == now.s && pre.b == now.b) {
		arr[i+1] = rank;
		continue;
	}
	// 랭킹 업데이트 될때 사이 랭킹은 사라짐
	rank = i+1;
	arr[i+1] = rank;
}

```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 우선순위큐
- 시간복잡도: `1 ≤ N ≤ 1,000` > `O(N)`
우선순위 큐 정렬 `O(logN)` 으로 시간복잡도는 `O(NlogN)`

### 💡 풀이 아이디어
- `PriorityQueue<Nation>` 를 통해 금 >= 은 >= 동 순으로 내림차순 정렬
   ``` java
   class Nation implements Comparable<Nation> {
        int name;
        int gold;
        int silver;
        int bronze;

        @Override
        public int compareTo(Nation o) {
            if(this.gold == o.gold){
                if(this.silver == o.silver){
                    return o.bronze - this.bronze;
                }
                return o.silver - this.silver;
            }
            return o.gold - this.gold;
        }
    }
   ```
- 이전 국가를 미리 저장한 후 우선순위에서 하나씩 꺼내서 비교
   - 이전 국가와 동일한 순위일 경우 `same +1`
   - 이전 국가보다 매달 순위가 낮을 경우 `rank +1`
   누적된 동일순위 수 만큼 순위가 밀려나기 때문에 `same` 더해주기
- 현재 국가를 이전 국가로 갱신 후 위 과정 반복
