### ISSUE TITLE
[13주차_수요일] 점수따먹기

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#174]
- 사이트 : 백준(BOJ)
- 문제: [점수따먹기](https://www.acmicpc.net/problem/1749)
- 번호: 1749

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N, M <= 200

=> 행렬의 시작점(sx, sy), 끝점(ex, ey)를 모두 찾아야 함 : O(N * M) * O(N * M)
=> 단, sx > ex && sy > ey 이므로 약, O(NM logNM)
=> 완전 탐색 가능


### 💡 풀이 아이디어

- **2차원 배열 누적합** 이용
    - 열 별 누적합
    ```java
	for(int i=1; i<N+1; i++) {
		for(int j=1; j<M+1; j++) {
			g[i][j] += g[i][j-1];
		}
	}
    ``` 
    - 행 별 누적합
    ```java
	for(int i=1; i<N+1; i++) {
		for(int j=1; j<M+1; j++) {
			g[i][j] += g[i-1][j];
		}
	}
    ```

- (sx, sy) ~ (ex, ey) 구간의 누적합 구하기
- `pSum = g[ex][ey] - g[sx-1][ey] - g[ex][sy-1] + g[sx-1][sy-1]`
![image](https://github.com/user-attachments/assets/6897dc4c-3965-4797-9b23-785516b7a6bd)

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 배열의 최대 크기: 199 * 199 (거의 200 * 200)
   * 2차원 배열에서 시작점과 끝 점 찾기 
   * sx > ex && sy > ey 이므로 약, O(NM logNM) (시간복잡도 지영님 내용 참고했습니다 ㅎㅎ !)


### 💡 풀이 아이디어

* 배열의 누적합을 구함 

  * `int[][] S`

    * `S[r][c]`: 배열에서 `(0, 0)` ~`(r, c)`지점까지의 누적합

    ```java
    for(int c = 1; c < M + 1; c++) {
        int current = Integer.parseInt(st.nextToken());
        S[r][c] = S[r - 1][c] + S[r][c - 1] - S[r - 1][c - 1] + current;
    }
    ```

* (rr, cc)과 (r, c)를 직사각형의 좌상, 우하로 지정했을 때, 해당 구간의 합을 구하면서 최댓값 찾기

 
<img src="https://github.com/user-attachments/assets/7e166b9b-5021-4dd8-aa55-c074c3f3b97a"  width="50%"/>

  ```java
  for(int r = 1; r < S.length; r++) {
      for(int c = 1; c < S[0].length; c++) {
          for(int rr = 1; rr < r + 1; rr++) {
              for(int cc = 1; cc < c + 1; cc++) {
                  // arr[rr][cc]에서 arr[r][c] 까지 누적합 구하기
                  // 제일 큰 직사각형
                  int s1 = S[r][c];
  
                  // 아래 직사각형
                  int s2 = S[rr - 1][c];
  
                  // 왼쪽 직사각형
                  int s3 = S[r][cc - 1];
  
                  // 공통 직사각형
                  int s4 = S[rr - 1][cc - 1];
  
                  int sum = s1 - s2 - s3 + s4;
                  max = Math.max(max, sum);
              }
          }
      }
  }
  ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 < N < 200, 1 < M < 200 &rarr; 4 x 10^4이므로 O((N x M)^2) 가능
- 누적 합을 구하고 `완전 탐색`해도 충분

### 💡 풀이 아이디어
- 부분 행렬이기 때문에 선형적으로 누적 합을 구한 후 최댓값을 추출하는 것은 불가 &rarr; 최소한의 누적 합을 구한 후 완전 탐색
  ```java
  int[][] dp = new int[n + 1][m + 1];
  for (int i = 1; i < n + 1; i++)
      for (int j = 1; j < m + 1; j++)
          // 누적 합 → (i, j)까지의 모든 합
          dp[i][j] = read() + dp[i - 1][j] + dp[i][j - 1] - dp[i - 1][j - 1];
  ```
- 부분 행렬의 합은 행렬의 시작 지점 좌표`(k, l)`과 끝 좌표`(i, j)`의 누적 합의 차이로 구할 수 있음
  ```java
  for (int i = 1; i < n + 1; i++)
      for (int j = 1; j < m + 1; j++)
          for (int k = 1; k < i + 1; k++)
              for (int l = 1; l < j + 1; l++) {
                  // 각 부분 행렬의 누적 합을 이용하여 계산
                  max = Math.max(max, dp[i][j] - dp[k - 1][j] - dp[i][l - 1] + dp[k - 1][l - 1]);
              }
  ```
- 이때 누적 합을 더해주는 경우에는 겹치는 부분은 `-`, 누적 합을 빼주는 경우에는 겹치는 부분은 `+`해주어 중복 연산을 피해주기

> 다른 분들 그림이 너무 좋네여...

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 <= N, M <= 200 (`4*10^4`)
- O(N * M) * O(N * M) 가능


### 💡 풀이 아이디어
- 처음 생각한 점화식
   ```java
    long[][][] dp = new long[N + 1][M + 1][3];
              long mx = Long.MIN_VALUE;
              for (int i = 1; i < N + 1; i++) {
                  for (int j = 1; j < M + 1; j++) {
                      dp[i][j][0] = board[i-1][j-1] + dp[i-1][j][0];                                                      // 세로 묶음
                      dp[i][j][1] = board[i-1][j-1] + dp[i][j-1][1];
                      dp[i][j][2] = board[i-1][j-1] + dp[i-1][j][2] + dp[i][j-1][2] - dp[i-1][j-1][2];                    // 가로 묶음
                      long cmx = Math.max(Math.max(board[i-1][j-1], dp[i][j][0]), Math.max(dp[i][j][1], dp[i][j][2]));     // 사각형 묶음
                      mx = Math.max(mx, cmx);
                  }
              }
   ```
    - 처음에 위와 같이 점화식을 세웠었는데, 이 방법은 선형적인 누적 합을 구한 방식이기에 틀림
    - 가장 최대값을 선택하며 dp를 만들어가지만 모든 부분 행렬의 값을 고려하지 못함

- 누적합 이용
   - 시작과 끝 위치를 조정할 수 있는 부분 행렬 합 구하기
   - 현재 자신까지 누적합 - 가로 누적합 - 세로 누적합 + 중복된 값
   1. 배열의 누적합 구해주기 (dp)
   2. 구한 누적합을 바탕으로 부분 행렬의 최댓값 구하기
   ```java
     long mx = Long.MIN_VALUE;
        for (int r1 = 1; r1 < N + 1; r1++) {
            for (int c1 = 1; c1 <= M + 1; c1++) {
                for (int r2 = r1; r2 <= N; r2++) {
                    for (int c2 = c1; c2 <= M; c2++) {
                        long tmp = dp[r2][c2] - dp[r1 - 1][c2] - dp[r2][c1 - 1] + dp[r1 - 1][c1 - 1];
                        mx = Math.max(mx, tmp);
                    }
                }
            }
        }
   ```

> 기본 아이디어는 첫번째랑 같으나 좀 더 누적합을 이용하고 부분 배열을 고려하는걸 잘 생각하기

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
1<= N, M <= 200 : `O((N * M)^2)`
- 시작점 끝점 보다 작아야함.. log...!

### 💡 풀이 아이디어
- 2차원 배열 `누적합을` 이용
- dp 점화식 : `dp[i][j] = board[i][j] + dp[i-1][j] + dp[i][j-1] - dp[i-1][j-1];`
- 부분 배열 최대합을 4중 포문으로 계산 : (r1, c1) ~ (r2, c2)
```java
        int max = Integer.MIN_VALUE;
        for(int i=1; i<=N; i++){
            for(int j=1; j<=M; j++){
                for(int r=1; r<=i; r++){ // (r1, c1) ~ (r2, c2)
                    for(int c=1; c<=j; c++){
                        max = Math.max(max, dp[i][j]-dp[r-1][j] - dp[i][c-1] + dp[r-1][c-1]);
                    }
                }
            }
        }
```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 누적합
- 시간복잡도: `1 < N,M < 200` > 누적합 `O((N*M)^2)`
각 칸에 -10,000 이상 10,000 이하

### 💡 풀이 아이디어
- 누적합으로 부분 면적 합 구하기
A 면접의 합은 `B + C - D`
![image](https://github.com/user-attachments/assets/c609446f-a963-401c-82f6-1fe111379c22)


- 모든 점에 대해 최상단 좌측, 최하단 우측 의 합을 구하고 최댓값 갱신하기
![image](https://github.com/user-attachments/assets/74894138-a495-4682-bd53-0c6166675a82)

> 정말 어질어질한 문제네요... [그림 출처](https://programmingiraffe.tistory.com/162)
