### ISSUE TITLE
[13주차_목요일] 아날로그 시계

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#175]
- 사이트 : 프로그래머스(PG)
- 문제: [아날로그 시계](https://school.programmers.co.kr/learn/courses/30/lessons/250135)
- 번호: 250135
- 레벨: level2

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 단순 구현 문제라서 고려하지 않음

### 💡 풀이 아이디어
- 단위 관련 문제 &rarr; 하나의 단위로 통일 
  - 여기서는 `초`를 기준으로 풀이
- 초침이 시침, 분침을 지날 때를 카운트 
  - 각 초침이 1초 동안 움직이는 각도를 이용하여 체크
  - 현재 초침의 각도와 1초 후 초침의 각도 사이에 초침 or 분침이 있으면 겹쳤음을 결정할 수 있으므로 카운트 증가
- 모든 시간(초)에 대해서 각 침들의 각도를 계산하고 비교
  ```java
  private static double[] calculateAndgles(int time) {
      double[] angles = new double[3];
      double h = time / 3600, m = time % 3600 / 60, s = time % 3600 % 60;
      // 시침의 현재 각도
      angles[0] = (h % 12) * (360d / 12) + m * (360d / 12 / 60) + s * (360d / 12 / 3600);
      // 분침의 현재 각도
      angles[1] = m * (360d / 60) + s * (360d / 60 / 60);
      // 초침의 현재 각도
      angles[2] = s * (360d / 60);
      return angles;
  }
  ```
- 초침이 시침, 분침과 겹치는지 확인
  ```java
  // 시침 겹침 확인
  private static boolean chkHour(double[] now, double[] next) {
      double nowSec = now[2], nextSec = next[2];
      // 1초의 움직임 안에 시침이 포함되는가
      if (nowSec < now[0] && next[0] <= nextSec)
          return true;
      // 59초의 값은 따로 계산 → 원형이기에 각도가 0으로 초기화되기 때문
      if (nowSec == 354d && 354d < now[0])
          return true;
      return false;
  }
  ```
  ```java
  // 분침 겹침 확인
  private static boolean chkMin(double[] now, double[] next) {
      double nowSec = now[2], nextSec = next[2];
      // 1초의 움직임 안에 시침이 포함되는가
      if (nowSec < now[1] && next[1] <= nextSec)
          return true;
      // 59초의 값은 따로 계산 → 원형이기에 각도가 0으로 초기화되기 때문
      if (nowSec == 354d && 354d < now[1])
          return true;
      return false;
  }
  ```
- 초침이 분침, 시침 동시에 겹치는 경우에는 1번만 카운트
  ```java
  if (isHourMatched)
      answer++;
  if (isMinMatched)
      answer++;
  if (isHourMatched && isMinMatched)
      if (nextAngles[0] == nextAngles[1])
          answer--;
  ```
- 시작부터 울릴 수 있는 경우 체크 `0시0분0초`, `12시0분0초`
  ```java
  if (now == 0 || now == 43200)
      answer++;
  ```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 구현 문제로 고려하지 않음


### 💡 풀이 아이디어
- **겹친다는 것은 1초 사이에 어떤 침이 다른 침을 역전되는 일이 발생하는 것**
   - 주어진 시작, 마지막 시간을 모두 초로 변환 후, 1초 단위로 체크하며 침이 역전되는지 확인
   - 초침이 각각 분침, 시침과 역전되는지 확인 (`overlapHour()`, `overlapMin()`)
      - 현재 시침이 분,시침보다 작았는데 커짐과 354에서 0도로 갈때 예외처리
      ```java
       private static boolean overlapHour(Time cur, Time nxt) {
        if(cur.dh > cur.ds && nxt.dh <=nxt.ds) return true;
        return cur.ds == 354 && cur.dh > 354;
       }
      ```
- 시침이 분침과 초침 모두 겹쳤을때, 하나만 겹쳤을 때 판단해서 cnt++
   ```java
    boolean isMinRing = overlapMin(cur, nxt);
    boolean isHourRing = overlapHour(cur, nxt);

    if (isMinRing && isHourRing){               // 시침 분침 모두 겹쳤을때
        if (nxt.dh== nxt.dm) cnt++;             // 시침분침의 위치가 같으면 한번만 카운트
        else cnt+=2;
    } else if (isMinRing || isHourRing) cnt++;
   ``` 
- 예외처리: 처음에 시분초 모두 같이 있을 경우(정오, 정각)
   - if (startTime==0 || startTime==43200) cnt++;` 
- Time객체 만들기
   - 필드로 시, 분, 초, 시분초별 각도 가짐
- `시, 분, 초` 별 분, 초별 움직이는 각도를 잘 생각하기
   - 시침
      - `1시간 : 60도` (360/12)
      - `1분 : 0.5도` (30/60)
      - `1초 : 1/120도` (0.5/60)
      - 각도 : `this.dh = (h % 12) * 30d + m * 0.5 + s * (0.5 / 60);`
         - 시침의 각도는 시,분,초침의 영향을 모두 받음
   - 분침
      - `1분: 6` (360/60)
      - `1초: 0.1` (6/60)
      - 각도: `this.dm = m * 6 + s * 0.1;`
   - 초침
     - `1초: 6` (360/60) 
     - 각도: `this.ds = s * 6;`

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 00:00:00 ~ 23:59:59

=> 완전탐색 가능

### 💡 풀이 아이디어

- 각 침의 각도를 구하기
1. 초시간으로 변경 => h*3600 + m*60 + s
    - start, end 초시간 구하기
2. 정오(낮12시), 자정(밤12) 처리
    - start가 둘 중 하나면 카운트
3. start < end일때 각도를 구해서 카운트 진행
    - 초침의 속도 => 360 / 60 == 6
    - 분침의 속도 => 360 / 60*60 == 1/10
    - 시침의 속도 => 360 / 3600 * 60 == 1/120
```java
        while(st < et) {
            // 현재 각도 계산
            // 초침 -> 1초에 6도 (360도/60초)
            // 분침 -> 1초에 1/10도 (6도 / 60)
            // 시침 -> 1초에 1/120도 (6도 / 60*12)
            double h = (st / 120) % 360;
            double m = (st / 10) % 360;
            double s = (st * 6) % 360;
            
            // 다음 각도
            // 0도가 된다는 것은 360도와 같음
            double nh = reAngle(((st+1) / 120) % 360);
            double nm = reAngle(((st+1) / 10) % 360);
            double ns = reAngle(((st+1) * 6) % 360);
            
            // 초침 == 시침
            if(s < h && nh <= ns) answer++;
            // 초침 == 분침
            if(s < m && nm <= ns) answer++;
            // 시침, 분침이 모두 겹칠때
            if(nh == ns && nm == ns) answer--;
            
            st++;
        }
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

- 0 ≤ `h1`, `h2` ≤ 23
- 0 ≤ `m1`, `m2` ≤ 59
- 0 ≤ `s1`, `s2` ≤ 59
- 00시 00분 00초 ~ 23시:59분:59초: 24 * 60 * 60 = 86,400



### 💡 풀이 아이디어

* 시작 시간부터 끝나는 시간까지 1초씩 증가시키면서 초침이 시침, 분침을 지나가는 순간이 총 몇 번 있는지 세기

* 시작 시간과 끝나는 시간을 모두 초로 바꿔주기 (각도로 쉽게 변환해주기 위해)

* `double phr, pmr, psr`: 이전 시침, 분침, 초침의 각도를 저장할 변수

  * 시침 각도: (i초 / 120.0) % 360
  * 분침 각도: (i초 / 10.0) % 360
  * 시침 각도: (i초 % 60.0) * 6

* 시침과 초침이 겹치는 경우

  ```java
  // 시침과 초침이 겹치는 경우
  if(chr < csr && phr > psr) answer += 1;
  else if(chr == csr) answer += 1;
  // 정각
  else if(phr > psr && csr == 0) answer += 1;
  ```

* 분침과 초침이 겹치는 경우

  ```java
  /// 분침과 겹치는 경우
  if(cmr < csr && pmr > psr) answer += 1;
  else if(cmr == csr) answer += 1;
  else if(pmr > psr && csr == 0) answer += 1;
  ```

* 시침, 분침, 초침이 모두 겹치는 경우

  ```java
  // 모두 겹치는 경우
  if(chr == 0 && cmr == 0 && csr == 0) answer -= 1;
  ```

* answer = (시침과 초침이 겹치는 경우) + (분침과 초침이 겹치는 경우) - (시침, 분침, 초침 모두 겹치는 경우)

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
구현문제라 고려X


### 💡 풀이 아이디어
- 단위 변환 : 초 단위로 변환, 정오, 자정일때 카운트
- 다음 시간의 각도 계산
- 360도 -> 0도 계산 필요
- (초심==시침) + (분침 == 시침) - (시침, 분침 == 초침)

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 수학 구현

### 💡 풀이 아이디어
1. 시침과 초침이 만나는 경우
시간당 60번, 분당 1번씩 초침과 만남
단, 12시가 되면 시간 계산이 겹치므로 12시 이후의 시간은 -1

2. 분침과 초침이 만나는 경우
시간당 59번, 분당 1번씩 만남

3. 현재 시점에서 시침과 초침의 만나는 경우:
시침의 위치는 시, 분, 초침에 의해 결정되며, 시침의 각도가 초침의 각도와 같거나 작을 경우 만남으로 간주하고 1회 추가함
초침의 각도는 초침이 360도를 60초 만에 회전하므로 `360/60 * s`
시침의 각도는 `360/12 * (h%12) + 360/(12*60) * m + 360/(12*60*60) * s`

4. 초침이 분침을 지나는 경우
분침의 위치는 분, 초침에 의해 결정되어 분침의 각도가 초침의 각도보다 작거나 같은 경우 +1
분 + 침 각도는 `360/60 * m` + `360/60/60 * s`

5. 시침, 분침, 초침이 모두 만나는 경우
모두 만나는 순간은 `00시 00분 00초`와 `12시 00분 00초` > 2번 (12시 이상인 경우 중복으로 -1)
