### ISSUE TITLE
[13주차_금요일] 표현 가능한 이진트리

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#176]
- 사이트 : 프로그래머스(PG)
- 문제: [표현 가능한 이진트리](https://school.programmers.co.kr/learn/courses/30/lessons/150367)
- 번호: 150367
- 레벨: Level3
```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ numbers ≤ 10,000
- 1 ≤ numbers의 원소 ≤ 10^15
- O(N^2)가능

### 💡 풀이 아이디어
- 주어진 숫자를 이진트리로 표현할 수 있는지 확인하는 문제
   - 0 : 리프노드로 표현, 순서: 왼쪽부터 탐색
   - 0을 표현하기 위해선 부모노드가 필요하고, **부모노드가 없는 자식은 있을 수 있을 수 없음**
   - 예시 5(101)과 같이 자식(1)이 있는데 부모노드가 0(리프노드)일 수 없음 
- 숫자를 이진수로 표현하기 (`num2bin()`)
   - 이때, 포화 이진 트리를 만들기 위해 `2^N-1`개의 수 필요
   - 부족한 자리수는 0으로 채우기
   ```java
   private static String num2bin(long num) {
        StringBuilder bin = new StringBuilder(Long.toBinaryString(num));
        long len = bin.length();
        int n = 0;
        while ((1L << n) - 1 < len) {           // 2^n-1로 자리를 맞추기 위한 n찾기
            n++;
        }

        while (bin.length() < (1 << n) - 1) {   // 2^n-1로 길이 맞추기
            bin.insert(0, "0");
        }

        return bin.toString();
    }
   ```
- 부모 자식 연결(모순) 확인 (`dfs()`)
   - 부모(루트)가 0인데 자식이 있으면 false
   - 아닐 경우 또 하위 서브트리 확인 dfs 재귀
   - 양쪽 모두 모순이 없을 경우 true
   ```java
   private static boolean dfs(String sub) {
        int root = sub.length() / 2;

        if (sub.length() ==1) return true;

        // 부모가 없는데 자식이 존재하면 이진트리 구성 못함
        if (sub.charAt(root)=='0' && (sub.substring(0, root).contains("1") || sub.substring(root+1).contains("1"))) return false;

        return dfs(sub.substring(0, root)) && dfs(sub.substring(root + 1));
    }
   ```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 ≤ `numbers`의 길이(n) ≤ 10,000
* O(n * n) 이내로 문제 풀이 해야 됨



### 💡 풀이 아이디어

* 숫자 입력 → 이진수 문자열로 변환 → inorder 로 주어진 정보를 가지고 트리를 구성함 → 표현 가능한 이진 트리인지 확인

* 이진수 문자열로 변환

  * 이진수 문자열의 크기는 포화이진트리 크기가 되야함
    * `int getTotalLength(int length)`
      * 현재 문자열의 크기가 `length`인데, 포화이진트리가 되기 위해서는 노드가 몇 개가 되어야 하는지 확인하는 함수
    * 포화이진트리의 크기와 현재 문자열의 길이를 빼서, 해당 크기만큼 `0`을 추가해줌

* inorder 로 주어진 정보를 가지고 트리를 구성함 (`void setTree(String s, int totalLength)`)
<img src = "https://github.com/user-attachments/assets/7a4730e7-88c8-40dd-aa47-e31b3ab2fe8d" width = "70%">

  ```java
  static void setTree(String s, int totalLength) {
      idx = 0;
  
      Queue<int[]> q = new ArrayDeque<>();
      q.add(new int[] {0, totalLength + 1});
  
      while(!q.isEmpty()) {
          int[] current = q.poll();
          int l = current[0], r = current[1];
          if(l == r || r - l == 1) continue;
  
          int middle = (l + r) >> 1;
          tree[idx] = s.charAt(middle - 1);
          idx += 1;
  
          q.add(new int[] {l, middle});
          q.add(new int[] {middle, r});
      }
  }
  ```

* 표현 가능한 이진트리인지 확인 (`boolean check(char[] tree)`)

  * 현재 노드의 값이 0일 때, 자식 노드가 하나라도 1의 값을 가지고 있다면 표현 불가능한 이진트리
  * 확인해야되는 부모 노드의 범위: 0 ~ (마지막 depth - 1) 노드
    * (마지막 depth - 1) 노드까지 검사하는 이유: 마지막 depth의 노드들은 자식이 없기 때문!

  ```java
  int depth = (int) (Math.log(tree.length) / Math.log(2)) + 1;
  int startIdx = (1 << (depth - 1)) - 1;
  
  for(int i = 0; i < startIdx; i++) {
      int currentIdx = i + 1;
      int next1 = currentIdx * 2;
      int next2 = currentIdx * 2 + 1;
  
      next1 -= 1; next2 -= 1;
  
      if(tree[i] == '0' && (tree[next1] == '1' || tree[next2] == '1')) {
          available = false;
          break;
      }
  }
  ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 &le; N &le; 10,000 &rarr; 10^4이므로 O(N^2)까지 가능

### 💡 풀이 아이디어
- 포화 이진트리 : 이진트리의 최대 깊이까지 모든 노드가 채워져 있어야 함## 🤔 시간복잡도 고려사항
- 1 &le; N &le; 10,000 &rarr; 10^4이므로 O(N^2)까지 가능

### 💡 풀이 아이디어
- 포화 이진트리 : 이진트리의 최대 깊이까지 모든 노드가 채워져 있어야 함
  - 해당 문제에서 주어지는 숫자로 포화 이진트리를 만들 수 없을 때는 더미 노드 `0`을 채워줘야 함.
  ```java
  // 포화 이진트리 -> 문자열 길이가 2^n - 1 꼴이 되어야 함
  private String toBinaryString(long number) {
      StringBuilder sb = new StringBuilder(Long.toBinaryString(number));
      int n = 1;
      while (sb.length() > (1 << n) - 1) {
          n++;
      }
      // 빈 부분 채우기
      sb.insert(0, "0".repeat((1 << n) - 1 - sb.length()));
      return sb.toString();
  }
  ```
- 만든 포화 이진트리를 기준으로 중위 순회(`좌 → 루트 → 우`)를 진행하면서 올바른 트리인지 확인
  - 루트 노드가 `0`인데 자식이 노드 중에 `1`이 있으면 False
  ```java
  // 중위 탐색을 진행하면서 불가능한 트리인지 확인
  private boolean chkInOrder(String str, int l, int r) {
      // 리프노드 일 경우는 True
      if (l == r)
          return true;
      int rootIdx = (l + r) / 2;
      // 루트 노드가 0'일 경우에는 자식에 '1'이 있으면 안됨
      if (str.charAt(rootIdx) == '0')
          for (int i = l; i <= r; i++)
              if (str.charAt(i) == '1')
                  return false;
      // 다음 중위 탐색
      return chkInOrder(str, l, rootIdx - 1) && chkInOrder(str, rootIdx + 1, r);
  }
  ```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 주어진 숫자의 개수 : N < 10,000

=> O(N * N) 이내로 생각해보기


### 💡 풀이 아이디어

- 포화 이진 트리 만들기
    - number[i]를 이진수로 변경한 뒤 `2^h - 1` 의 크기에 맞게 앞에 "0"을 추가해줘야 포화이진트리가 됨
    - Long.toBinaryString() 활용 => 10지수를 2진수 문자열로 치환

- 포화 이진 트리에 만족하는지 판단
    - 트리는 부모가 없는데 자식이 존재할 수 없음 => 즉, 부모와 좌우 자식을 재귀적으로 탐색
    - rIdx = now.length() / 2 => 중위순회(왼, 루, 오)이므로 부모는 두 자식의 중간값
    - left = now.subString(0, rIdx), right = now.substring(rIdx+1);

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
N<10000 : `O(N^2)` 이하

### 💡 풀이 아이디어
- 포화 이진트리 표현 가능한지 판단
- `Long.toBinaryString` : 숫자를 이진수로 변환
- `fullBinary` : 포화 이진트리 형태로 확장
- `isValidTree(fullBinary) ? 1 : 0` : 트리 검증하여 규칙에 맞으면 결과 배열에 저장
- `extend` : 숫자의 이진수를 포화 이진트리로 확장하는 함수 (포화 이진트리 노드 개수 2^h-1)
- `isValidTree` : 재귀적으로 포화 이진트리 규칙을 확인
- `isValidSubtree`: 서브트리 검증
- 왼쪽, 오른쪽 서브트리 각각 검증 -> 왼쪽, 오른쪽 모두 유효하면 전체 트리 반환
```java
        boolean leftValid = isValidSubtree(binary, start, mid - 1);
        boolean rightValid = isValidSubtree(binary, mid + 1, end);
```
