### ISSUE TITLE
[14주차_월요일] 색깔 폭탄

### ISSUE THREAD

**Issue by baexxbin** [GreatAlgorithm-Study/AlgorithmStudy#184]
- 사이트 : 코드트리(CT)
- 문제: [색깔 폭탄](https://www.codetree.ai/training-field/frequent-problems/problems/colored-bomb/description?page=2&pageSize=20)
- 년도: 2021

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 2 ≤ 격자의 크기 ≤ 20
* 2 ≤ 폭탄의 종류 ≤ 5
* 20 × 20에서의 BFS이므로 반복이 62,500번 이내라면 시간 충분함!



### 💡 풀이 아이디어

* 문제에서 주어진대로 구현

  * 빈 공간을 0으로 나타내주기 위해 빨간 폭탄의 값을 -2로 설정해줌

* `Deque<Point> step1`: 폭탄 묶음 찾기

  * 폭탄 묶음에 대한 좌표들을 `Deque`에 저장해서 반환함
  * 2차원 배열에서 **행은 N - 1부터**, **열은 0부터 탐색**하며 주어진 조건에 알맞는 폭탄 그룹을 선택할 수 있도록 함
  *  현재까지 가장 큰 폭탄 묶음의 크기(`groupSize`)와 현재 탐색하는 지점에서의 폭탄 묶음의 크기(`currentSize`) 비교
  * 현재 폭탄 묶음이 될 그룹에서 빨간 폭탄의 개수(`redCnt`)와 현재 지점에서의 폭탄 그룹을 구성할 때, 빨간 폭탄의 개수 비교(`currentRedCnt`)

* `void step2()`: 폭탄 터트리기

  * `step1`을 통해 찾은 폭탄 묶음을 통해 폭탄 터트려주기

* `void step3()`: 중력 작용

  * 임시 배열 `tmp`에 변경사항 저장하고, `tmp`를  `map`으로 바꿔주기 
  * 열을 기준으로 하고, 행 탐색
  * 현재 위치에 폭탄이 있으면 큐에 넣어주고, 돌이 나오면 gravity(기준선)을 기준으로 쌓아주기

* `void step4()`: 반시계 방향으로 회전해주기 (지영님이 알려주신 방법)

  ```java
  int[][] tmp = new int[N][N];
  for(int r = 0; r < N; r++) {
      for(int c = 0; c < N; c++) {
          tmp[N - 1 - c][r] = map[r][c];
      }
  }
  
  map = tmp;
  ```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: BFS + 구현
- 시간복잡도: 2 ≤ n ≤ 20
BFS 탐색 시 `O(n*n*4)`

### 💡 풀이 아이디어
항목 | 설명
-- | --
`Bundle.class` | `각 폭탄 좌표 배열`, `빨간폭탄 갯수`, `가장 큰 행`, `가장 작은 열` 필드로 구성
`int[][] bombs` | 폭탄 묶음 배열
`List<Bundle> bundles` | 모든 경우의 폭탄묶음 리스트

1. `find`
연결된 폭탄묶음을 찾기 위해 BFS 탐색 사용
- 각 셀마다 BFS 탐색을 진행하여 `빨간색 폭탄 또는 현재 셀의 색`일 경우에만 연결된 폭탄으로 인정
- 연결된 폭탄을 찾으면 빨간색 폭탄인지, 가장 큰 행인지, 가장 작은 열인지 확인 후 갱신 (폭탄묶음이 여러개일 경우 우선순위를 정하기 위함)
- BFS 탐색 종료 후 2개 이상의 폭탄으로 구성되어 있을 경우 폭탄묶음이기 때문에 `bundles` 에 저장

2. `filter`
동일한 크기의 폭탄묶음이 여러개일 경우 우선순위 비교하기
- `bundles` 여러 폭탄묶음 리스트들을 Comparable 조건에 맞춰서 우선순위 정렬
   ``` java
        @Override
        public int compareTo(Bundle b){
            if(this.bombs.size() == b.bombs.size()){
                if(this.red == b.red){
                    if(this.rows == b.rows){
                        //3. 가장 열이 작은 폭탄 묶음
                        return this.columns - b.columns;
                    }
                    //2. 행이 가장 큰 폭탄 묶음 (행이 빨간색이 아니면서 가장 큰 칸)
                    return b.rows - this.rows;
                }
                //1. 빨간색 폭탄이 가장 적은 묶음
                return this.red - b.red;
            }
            //사이즈가 가장 큰 순서
            return b.bombs.size() - this.bombs.size();
        }
   ```

3. `remove`
폭탄묶음 제거하기 + 폭탄 갯수만큼 점수 카운팅

4. `move`
폭탄 중력작용 + 반시계 방향으로 90도 회전 + 중력작용
- `moveDown` : 중력작용
마지막 행부터 뒤로 순회를 해서 `현재 위치`가 `검은색 돌`이거나 빈공간이면 패스
그렇지 않을 경우 최하단으로 이동하기 위해서 `while` 으로 갈 수 있는 최하단 까지 `인덱스` 범위를 이동
해당 인덱스 위치로 위치 이동

- `rotate` : 반시계 방향으로 90도 회전

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ n ≤ 20
- 구현 문제라 딱히 신경쓰지 않음

### 💡 풀이 아이디어
- 조건에 따라 반복
```java
int score = 0;  // 최종 점수
while (true) {
    PriorityQueue<Group> groups = makeGroups(); // 우선순위 큐를 이용해서 우선순위 부여
    // 터트릴 수 없을 경우에 종료
    if (groups.isEmpty() || groups.peek().list.size() == 1)
        break;
    score += Math.pow(groups.peek().list.size(), 2); // 터트리기 전에 점수 계산
    explode(groups.poll()); // 폭발
    pullToDown();           // 중력 작용
    rotate();               // 반시계 회전
    pullToDown();           // 중력 작용
}
```
- `makeGroups()`: `BFS`를 이용하여 폭탄의 그룹을 만들기
  - 반복문을 거꾸로 올라오면서 처음 만나는 빨간색 외의 폭탄의 좌표를 기준으로 잡음
  ```java
  for (int y = n - 1; y >= 0; y--) {
      for (int x = 0; x < n; x++) {
          // 방문했거나 빨간 폭탄일 경우 건너뜀
          if (visited[y][x] || board[y][x] <= 0)
              continue;
          Group group = new Group(y, x);  // 그룹의 생성자에 기준이 되는 값을 넣음
  ```
  - 빨간색 폭탄의 경우는 방문체크를 따로 해줌 &rarr; 다른 색깔의 폭탄과도 이어질 수 있기 때문에
    - 빨간색 폭탄의 개수도 따로 `Group` 객체에서 관리 &rarr; `redCnt`
- `explode()`: 우선순위가 높은 그룹을 꺼내서 해당 그룹에 저장된 좌표들을 전부 폭파 &rarr; 공백 값`-2`으로 바꿔줌
- `pullToDown()`: 아래서부터 순회하며 공백 값`-2`가 나오면 해당 좌표에서부터 위에 나오는 첫 폭탄과 스왑
  - 위의 좌표에서 돌이 나온다면 해당 스왑은 진행하지 않음
- `rotate()`: 반 시계 방향으로 회전 
  ```java
  private static void rotate() {
      int[][] next = new int[n][n];
      for (int i = 0; i < n; i++)
          for (int j = 0; j < n; j++)
              next[n - 1 - j][i] = board[i][j];
      board = next;
  }
  ```
> 빡구현..! 회전하는 거 저도 지영님 소스 참고했습니다~ 최고 😸

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
2 <= n <= 20 : `구현 가능`


### 💡 풀이 아이디어
- `find()` : `BFS`로 현재 격자에서 크기가 가장 큰 폭탄 묶음을 찾기
  - `redCnt`(빨간색 폭탄 개수) 유의해서 찾고 
  - `우선순위` 정렬(size, redCnt, 기준 행, 기준 열)
  - 검은돌(-1) 제외
  - 점수 획득(group.size * group.size)
- `remove()` : 폭탄 묶음 제거
  - 빈칸 처리(-2)
- `gravity()` : 중력 작용(검돌은 안떨어짐)
- `rotate()`: 반시계 90도 회전 `(x, y) -> (n-1-y, x)`
```java
newBoard[n-1-y][x]=arr[x][y];
```
- 다시 중력 작용
> 저도 회전 지영님 코드 참고 했습니다!

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 20
- M <= 5

=> 단순 구현문제 이므로 완전 탐색 가능


### 💡 풀이 아이디어

```
1. 폭탄 묶음 찾기
2. 폭탄 묶음 점수 계산하기
3. 폭탄 제거하기
4. 반시계 90도 회전하기
5. 중력 작용하기
```

- `findBundle()`: 폭탄 묶음 찾기
   - BFS 탐색으로 덩이리(묶음) 찾기
   - 우선순위 설정 PriorityQueue 활용 : 묶음 크기 -> 빨간폭탄 개수 -> 행 -> 열
   - 폭탄 객체(Bomb)를 선언해서 Comparable로 우선순위 정하기

- `rotate()` : 반시계 90도 회전 => (x, y) -> (N-y-1, x)
- `setGravity()` : 중력 적용하기
    - 마지막행(N-1)부터 반복하며 폭탄인 경우 한칸씩 내리기

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- N <= 20
- M <= 5
- 완전탐색 가능

### 💡 풀이 아이디어
> 저 이거 왜 틀리는지 모르겠습니다.. 혹시 괜찮으시다면 코드리뷰때 잠깐 코드를 같이 살펴봐주실 수 있으실까요...🙂‍↕️
- 의심이 가는건 빨간 폭탄을 처리하며 가장 큰 폭탄 그룹찾기가 의심스럽습니다..

- 가장 큰 폭탄 묶음 (여부)찾기(`findBigBoom()`)
   - 방문하지 않고, 빨간색, 검정이 아닌 색깔폭탄에 한에서만 bfs 수행
      - 빨간폭탄은 bfs내에서 처리하기 때문에 시작점으로 수행하지 않음
      - 보드를 돌면서 bfs를 통해 폭탄 묶음을 찾았다면 true반환 → while문에서 코드 계속 수행여부 판별할 flag로 사용 됨
- 가장 큰 폭탄 묶음 찾기 `bfs()`
   - List<Boom> tmp : 폭탄들의 묶음을 저장할 리스트(빨강 포함)
   - Set<Integer> red : 빨강 폭탄의 여부 판별할 set (빨강좌표를 1차원으로 변경한 값을 키값으로 진행)
   - bfs를 수행하며 같은 색일 경우 tmp에 넣고, 빨강일 경우 red 넣음
   - 크기가 2가 안되거나 빨강으로 이뤄질 경우 false반환
   - 조건 만족하면 checkBigBoom을 통해 가장 큰 폭탄 그룹 갱신
- 가장 큰 폭탄 그룹 갱신 `checkBigBoom`
   - 문제에서 주어진 조건에 따라 가장 큰 폭탄 그룹 갱신
   - 가장 큰 폭탄에 대한 정보는 bBRed, bBoom, bBooms로 전역변수로 관리
- 회전 수행
   - 최종 이뤄져야할 회전은 중력 상태를 2번 겪음
      - 먼저 반시계 90도 돌리고 오른쪽으로 밀기 (== 첫번째 중력작용후 회전 상태)
      - 또 90도 반시계후 오른쪽밀고 시계 90도로 원상복구하면 최종 중력상태 완성
      - rotate90L(); : 왼쪽으로 90도 회전
      - tilt(); : 오른쪽으롤 밀기 (열로 미는것보다 행으로 미는게 쉬울거같아서..)
      - rotate90R(); : 오른쪽으로 90도 회전

> 이상한 설계 고집하지 않기..^^
