### ISSUE TITLE
[14주차_화요일] 죽음의 비

### ISSUE THREAD

**Issue by baexxbin** [GreatAlgorithm-Study/AlgorithmStudy#185]
- 사이트 : 백준(BOJ)
- 문제: [죽음의 비](https://www.acmicpc.net/problem/22944)
- 번호: 22944

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
-  4 ≤ N ≤ 500
 - 0 ≤ K ≤ 10
 - 500 * 500 * 4 = 1,000,000 (완전탐색 가능)
 - 500 * 500 * 10 = 2,500,000 (3차원 visited배열 선언 가능)

### 💡 풀이 아이디어
- 3차원 BFS문제
   - bfs로 진행하되, 그냥 경우(`.`)와 우산을 주울 경우(`U`)에 따라 방문처리, 노드 삽입을 다르게하기
- 다음 위치가 우산일 경우
   - 우산을 줍는 경우에 따라 갈 수 있는 위치와 방문 처리가 다름
   - 우산을 주운 개수에 따라 visited 방문 처리
- 그냥 땅일 경우
   - 우산의 내구성이 있으면 우산 내구성--
   - 우산 없으면 자신의 체력--
- 주의할 점
   - bfs를 수행하면서 설정해준 우산 개수보다 많이 주울 수 있기에 cur.cntU + 1 <= K로 조건처리 잊지말기

> dfs 백트래킹 문제를 내고 싶었는데 bfs문제였네요.. 물론 다른 방법도 가능하지만..

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 4 ≤ N ≤ 500  : `O(N^2)`


### 💡 풀이 아이디어
- `BFS`로 탐색 진행 -> 안전 지대(E)에 도달하면 최소 이동 횟수 반환 
  - `Queue`에 시작점('S') 추가하며 탐색 시작
- 우산이 있을 경우 내구도 초기화하여 새 우산으로 교체
  - 우산 개수(k) 고려X
- `Node` : x, y 좌표, 현재 체력, 우산 내구도, 이동 횟수
- `check[][]` : 현재 위치에서 탐색 가능한 진행 가능 거리 기준 방문
  - (체력 + 우산 내구도)
- 안전 지대에 도달하지 못하면 -1 반환

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 4 <= 한 변의 길이 <= 500
* 0 <= 우산의 개수 <= 10
* 1 <= 현재 체력 <= 10,000
* 1 <= 우산의 내구도 <= 5,000

우산 개수에 따라 방문 배열을 새롭게 만들어 줘야됨 → 3차원 방문 배열을 사용한 BFS: O(n) = 500 * 500 * 10 * 4



### 💡 풀이 아이디어

* `Point`: 현재 있는 지점에서의 정보
  * `r`, `c`: 좌표 정보
  * `k`: 우산을 몇 개 사용했는지
  * `d`: 움직인 거리
  * `p`: 체력
  * `u`: 우산의 내구도
*  처음 시작 지점에도 바로 비가 내리기 때문에 `map[r][c] = '.'`를 해줘야 됨
* 우산이 총 몇 개 있는지 세주기(`uCnt`) → 방문배열의 크기가 됨 (`v[uCnt][N][N]`)
* BFS 탐색 시작
  * 다음 위치에 비가 내리는 경우: `map[nr][nc] == '.'`
    * 우산 내구도 1 줄여주기
    * 우산 내구도가 0이라면 체력 줄여주기
  * 다음 위치에 우산이 있는 경우
    * 우산 내구도 `N - 1`로 재설정
    * `map[nr][nc] = 1`로 바꿔주기
  * 체력이 0이 되었다면 다음 지점으로 못감
> 방문 배열 신경 잘 쓰기 !!!

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: BFS
- 시간복잡도: 4 <= N <= 500
BFS 풀이 시 `O(N*N*4)`

### 💡 풀이 아이디어
-  BFS 탐색을 위해 `Deque<Pos> deque` 에서 꺼내서 탐색 진행
   ``` java
   static class Pos {
        int x;
        int y;
        int hp;
        int distance;   //거리
        int umbrella;   //우산내구도
        int umbrellaCount;   //우산인덱스(전체에서 우산 획득한 갯수)
   }
   ```
- BFS 탐색 시 중복방문을 방지하기 위해 `boolean[][][] visited` 방문 배열 생성
visited[x좌표][y좌표][우산인덱스]
- 하나의 구간 탐색 시 현재 위치가 `E` `U` `.` 에 따라 요구사항 진행
   - `E` : 출구를 찾았으니 탈출
   - `U` : 우산 획득했으므로 내구도 -1 , 우산인덱스++, 현재 위치 `.` 변경
   - `.` : 우산 내구도가 있으면 내구도 감소 or hp 감소
- 만약 현재 hp 가 0 이 된다면 다음 탐색으로 넘어간다
- 현재 위치 방문처리
 각 노드별로 `좌표`, `hp`, `distance`, `umbrella`, `umbrellaCount` 를 저장하는 `Pos` 생성

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 4 ≤ N ≤ 500
- 0 ≤ K ≤ 10
- 1 ≤ H ≤ 10,000
- 1 ≤ D ≤ 5,000

=> 총 탐색 깊이 S = N * N == 500 * 500
=> 1) 단순 4방항 백트래킹 이용 : O(S!) 이므로 시간 초과
=> 2) 우산을 기준으로 이동하는 백트래킹 : O(K!)  이므로 가능 -> 우산 K개를 나열해서 선택하는 순서를 정하는 방법과 같음   
=> BFS 활용 : O(N * N) 가능


### 💡 풀이 아이디어

- 백트래킹을 활용
    - 우산들의 위치 정보 리스틑 생성 + 마지막에 도착점을 추가함
    - 시작점 부터 각 우산까지 이동하면서 가능한 경우 계속 이동 
    - 이동이 가능하다 : (현재 체력 + 우산 내구성)으로 다음 우산까지 이동할 수 있음 
    - 가지치기
        - 현재 이동거리가 결정된 최소값보다 크다면 이동 중단
    - dfs(int x, int y, int depth, int hp, int up)
        - x, y : 현재 위치
        - depth: 현재까지 이동한 거리
        - hp: 현재 체력
        - up: 현재 우산 내구성
    ```java
	for(int i=0; i<K+1; i++) {
		int[] u = uList.get(i);
		if(visited[u[0]][u[1]]) continue;
			
		// 현재 위치 -> 다음 우산 위치의 거리 
		int nDist = calDist(x, y, u[0], u[1]);
		if(nDist > hp+up) continue;
			
		int nhp = hp;
		// 체력이 소모 되는 경우 : 남은 우산 내구성 - 이동할 거리 + 1(다음위치도 우산이므로)
		int tmp = up - nDist + 1;
		if(tmp < 0) {
			nhp += tmp;
		}
		visited[u[0]][u[1]] = true;
		dfs(u[0], u[1], depth+nDist, nhp, D-1);
		visited[u[0]][u[1]] = false;
	}
    ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 4 &le; N &le; 500, 0 &le; K &le; 10 &rarr; 500 x 500 x 10 = 2.5 x 10^6이므로 완전 탐색 충분

### 💡 풀이 아이디어
- `BFS`를 이용한 최단 거리 찾기
- HP가 다 떨어지기 전에 이동해야 함 + HP 대신 소모되는 우산 &rarr; `BFS`의 방문 처리를 현재 가지고 있는 HP + 우산의 합으로
  - 다음 진행하려는 곳이 현재 체력보다 낮은 경우에만 이동 가능
```java
while (!dq.isEmpty()) {
    int[] cur = dq.poll();
    for (int i = 0; i < 4; i++) {
        int ny = cur[0] + dy[i], nx = cur[1] + dx[i];
        int nh = cur[3], nd = cur[4];
        if (isValid(ny, nx)) {
            // 다음 진행이 종료지점일 경우 반환
            if (board[ny][nx] == 'E') {
                System.out.println(cur[2] + 1);
                return;
            }
            // 우산 바꾸기
            if (board[ny][nx] == 'U') {
                board[ny][nx] = '.';
                nd = d;
            }
            // HP 혹은 우산 내구도 감소
            if (nd > 0) {
                nd--;
            } else {
                nh--;
            }
            // 현재보다 낮은 곳으로만 이동
            if (visited[ny][nx] < nh + nd) {
                visited[ny][nx] = nh + nd;  // 현재 HP + 우산 내구도로 방문 처리
                dq.offer(new int[] { ny, nx, cur[2] + 1, nh, nd });
            }
        }
    }
}
```
> 우산 내구도가 줄어드는 것에 대한 설명이 모호하네요..
