### ISSUE TITLE
[14주차_수요일] 꿈틀꿈틀 호석 애벌레 - 효율성

### ISSUE THREAD

**Issue by baexxbin** [GreatAlgorithm-Study/AlgorithmStudy#186]
- 사이트 : 백준(BOJ)
- 문제: [꿈틀꿈틀 호석 애벌레 - 효율성](https://www.acmicpc.net/problem/20181)
- 번호: 20181

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
N <= 10^5 : `O(N)`이하로 해결


### 💡 풀이 아이디어
- 투포인터 + dp
- `dp[i]` :  i번째 먹이까지의 최대 탈피 에너지
  - `dp[left] + sum - K `: 이전까지 탈피 에너지를 누적하여 고려
  - `dp[right] = Math.max(dp[right], dp[right - 1])` : 최대 탈피 에너지값 출력

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 투포인터(슬라이딩 윈도우) + dp
- 시간복잡도: 1<=N<=100,000 > `O(N)`

### 💡 풀이 아이디어
- end~start 범위에 대해 투포인터로 슬라이딩 윈도우 진행
   - 만족도가 k 보다 작으면 start를 움직인다
   - 만족도가 k 보다 크거나 같으면 end 를 움직인다
- dp 로 메모리제이션 하며 최대 누적 에너지 찾기
   - `기존 누적 최대에너지` vs `이전 상태로 돌아가서 현재 구간에 대한 탈피에너지` 
   - 만족도가 k 보다 크거나 같을 경우, 현재 범위에서의 최대 에너지 갱신
   ``` java
   dp[start] = Math.max(dp[start], dp[end] + satisfaction - k);
   ```
   - 만족도가 k 보다 작을 경우, 현재까지의 최대 에너지 갱신
   ``` java
   dp[start] = Math.max(dp[start],dp[start-1]);
   ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 100,000 &rarr; 10^5이므로 O(N logN)까지 가능

### 💡 풀이 아이디어
- `투 포인터를 이용한 누적 합`을 이용 + 최댓값을 유지해야하므로 `DP`를 이용
- `dp[i]`: `i`까지의 얻은 탈피 에너지의 최댓값
- 포인터 `l`에서 `r`까지의 누적 합이 k를 넘을 때, `dp[r]`의 값을 결정
  - `r`은 계속 증가하고, 누적 합이 k를 넘기지 않도록 `l`값을 증가시키면서 `dp[r]` 값을 결정

  ![123](https://github.com/user-attachments/assets/120bffa2-e460-4ae8-ba42-d19a65ffe872)

- 점화식 : $`dp[r] = Math.max(dp[r], dp[l - 1] + sum - k)`$
  ```java
  while (r < n) {
      sum += arr[r];
      dp[r + 1] = dp[r];
      while (sum >= k) {
          dp[r + 1] = Math.max(dp[r + 1], dp[l] + sum - k); // 인덱스를 벗어나게 되므로 dp배열을 하나 늘려서 진행
          sum -= arr[l];
          l++;
      }
      r++;
  }
  ```

> DP 설명하는 거 너무 어렵네요..

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 100,000
- K <= 10^8

=> O(N) or O(NlogN)까지 생각해보기


### 💡 풀이 아이디어

- DP 활용 => `dp[i]` : i번째 나뭇가지까지 탐색했을 때의 최대 에너지
    - K는 충분히 크므로 Long 타입으로 배열 선언
- 투포인터 활용
    - sum : 구간합 저장
    - 시작점: s, 끝점: e
    - e는 계속증가하고, 초반에 이전값(e-1)을 최대로 가져와서 초기화함
    - 구간합의 갑이 K보다 작아질때까지 시작 포인터를 증가시키면서 최대값을 갱신함
    - `dp[e] = max(dp[e], dp[s-1]+sum-K)`

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 ≤ *N* ≤ 100,000이므로 NlogN * 100 정도까지 할 수 있음



### 💡 풀이 아이디어

* 길이가 정해지지 않은 연속된 구간의 합계를 구해야 되므로 투포인터 이용

* 과거의 탈피 에너지와 비교하면서 최대 탈피 에너지를 구해야 되므로 dp 사용

* dp[i]: i지점까지 최선을 다했을 때, 얻을 수 있는 점수

  ```java
  while(e < N + 1) {
      if(sum >= K) {
          tmp = s == 0 ? 0: Math.max(tmp, dp[s - 1]);
          // tmp + sum - K
          // : (s전까지 최선을 다했을 때, 얻을 수 있는 점수) + (s ~ e까지 합계) - K
          // else 부분에서 e++가 되었으므로 dp[e - 1]을 해줘서 sum을 한 범위까지 확인할 수 있도록 함
          dp[e - 1] = Math.max(dp[e - 1], tmp + sum - K);
          result = Math.max(result, dp[e - 1]);
          sum -= arr[s++];
  
      } else {
          sum += arr[e++];
      }
  }
  ```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- N <= 100,000
- K <= 10^8
- O(N) 이하


### 💡 풀이 아이디어
- 슬라이딩 윈도우와 dp 사용
   - 특정 연속 구간에 대한 최대 탈피 에너지를 구해야 함
```java
  long happy = 0;
  int left = 0;
  for (int right = 0; right < N; right++) {
      happy += arr[right];

      while (happy >= K) {
          dp[right + 1] = Math.max(dp[right + 1], dp[left] + happy - K);      // dp[left]는 이전 구간의 최대값(이전 최종 right의 위치)
          happy -= arr[left++];
      }

      dp[right + 1] = Math.max(dp[right], dp[right + 1]);             // 현재까지의 최대값과 갱신된 최대값 비교
  }
```
- 먹이를 계속 먹다가 K이상이되면 멈춤 
   -현재 위치에서 left 포인터 이동하면서 최대 탈피 에너지 구하기
    > 근데 이미 만들어진 윈도우내에서 left줄이면서 happy값 구하면 처음에 들어있는 값이 제일 크니까 제일 처음값이 들어가는거 아닌가...?라는 궁금즘..
- 윈도우 조정 후 현재까지의 최대값과 갱신된 최대값 비교

> DP너무 어려운거같아요ㅠㅠ 어려워서 해설 보면서 푸는데도 핵심 로직들이 정확히 이해가 안가요.....띠로리
