### ISSUE TITLE
[14주차_수요일] 파일 정리

### ISSUE THREAD

**Issue by baexxbin** [GreatAlgorithm-Study/AlgorithmStudy#187]
- 사이트 : 백준(BOJ)
- 문제: [파일 정리](https://www.acmicpc.net/problem/20291)
- 번호: 20291

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 <= 50,000

* NlogN 하면 충분

  

### 💡 풀이 아이디어

* `TreeMap<String, Integer>`
  * key: 확장자명, value: 개수
  *  확장자 순으로 정렬 가능
* 파일명 입력 받으면 `.`을 기준으로 나누고 뒤에 단어 가져오기

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 &le; N &le; 50,000, 3 &le; 파일명의 길이 &le; 100 &rarr; 5 x  10^6 의 완전 탐색 가능

### 💡 풀이 아이디어
- 확장자 명의 카운트, 정렬 &rarr; `TreeMap`
- 문자열을 `.`을 기준으로 split하여 확장자 추출
- 추출한 확장자를 카운트, `TreeMap`에 삽입 &rarr; 사전 순으로 정렬됨
- `TreeMap`의 `keySet()`을 이용해서 확장자 명을 순회하면서 확장자 명, 카운트 출

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 50,000
- 3 ≤ 파일명의 길이 ≤ 100
- 완전탐색 가능

### 💡 풀이 아이디어
- `.`구분자로 확장자 분리해서 해당 확장자 카운트 해주기
- 출력 시 정렬을 해야하기에 Treemap 사용 도전
```java
  for (Map.Entry<String, Integer> entry : map.entrySet()) {
      sb.append(entry.getKey()).append(" ").append(entry.getValue()).append('\n');
  }
```
- `Map.Entry<String, Integer>`
   - 맵의 키와 값을 표현하는 객체

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 50,000

=> 정렬 시간복잡도 : O(NlogN) 가능


### 💡 풀이 아이디어

- TrreMap 활용해서 KeySet() 정렬된 상태로 출력하기
- split() 사용
    - 정규식 문자를 나타내는 `.`, `|`, `&`, `[` 등 으로는 분리 불가
        - 이때는 백슬레시 이용 => `str.split("\\.")`
        ```java
            	for(int i=0; i<N; i++) {
			String[] fName = br.readLine().split("\\.");
			fMap.put(fName[1], fMap.getOrDefault(fName[1], 0)+1);
		}
        ```

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 문자열
- 시간복잡도: 1 <= N <= 50000
TreeMap 으로 풀이 시 `O(logN)` 발생

### 💡 풀이 아이디어
- `TreeMap<String,Integer>`
   - 트리맵을 통해 for문 순회로 <문자열,갯수> 를 저장
   - 저장된 트리맵 `entrySet` 으로 출력

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 3초 제한, N<=50000
- TreeMap `O(logN)` 충분

### 💡 풀이 아이디어
- `TreeMap<String, Integer>`  : 확장자명을 사전순으로 정렬 필요 
  - key 기준 오름차순 정렬되기에 추가 정렬X
  - key : 파일 확장자
- `SubString(lastIndexOf('.') +1)` :  `.` 기준 확장자 명 분리
- `words.getOrDefault(extension, 0)+1`  : 동일한 확장자가 여러 번 등장하면 기존 값을 갱신하며 중복 처리
- `TreeSet` : `entrySet()` 으로 출력
