### ISSUE TITLE
[14주차_목요일] 충돌위험 찾기

### ISSUE THREAD

**Issue by baexxbin** [GreatAlgorithm-Study/AlgorithmStudy#188]
- 사이트 : 프로그래머스(PG)
- 문제: [충돌위험 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/340211)
- 번호: 340211
- 레벨: Level 2

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 좌표크기 N <= 100
- 포인터 개수 P <= 100
- 로봇 개수 X <= 100
- 루트 개수 R <= 100

=> bfs 활용 시
    - 모든 로봇은 최대 N * N까지 움직일 수 있음
    - 각 로봇의 한칸 이동 마다 최단거리를 구해야 함 -> O(N * N) == 10,000
    -  모든 루트를 반복해야 함 => 최대 R-1
    - 즉, O( N * N * (N * N) * (R-1) ) => 시간초과 발생
    
=> **최단거리 구하기 -> 맨하탄 거리 활용 O(1) : `|sx-ex| + |sy-ey|`** 
    - O( N * N * (R-1) ) => 완전탐색 가능


### 💡 풀이 아이디어

- 최단거리는 (시작점) ~ (도착점) 기준으로 맨하탄 거리를 이용해 구한뒤, 다음 이동할 곳을 정한다.
- 로봇 객체 선언
    ```java
    class Robot {
        // 로봇의 현재 위치 : (x, y)
        // 로봇의 목적지 : (ex, ey)
        // sp: 현재 진행중인 포인터
        // rCnt: 진행한 루트 카운터 (rCnt == M이면 모든 루트를 탐색함)

        int x, y, ex, ey;
        int sp, rCnt;
    }
    ```

1) `isDone()`: 모든 로봇이 운송을 마쳤는지 유효성 검사
2) `check()` : 로봇들의 충돌 위험 수 세기
    - `g[][]` : 로봇들의 위치를 저장
    - g[i][j]가 1보다 크다면 2개이상의 로봇이 존재하므로 충돌위험 카운트 증가
    - 단, 이때 이미 운송을 마친 로봇들은 고려하지 않음
3) `move()` : 로봇들 움직이기
    - 운송 중인 로봇들을 반복해서 최단거리로 움직이기
    - 최단거리 구하기 `calDist(sx, sy, ex, ey)` : 맨하탄 거리로 구하기
    - now.rCnt로 현재 탐색 중인 목적지 인덱스 저장 
    - 로봇의 현재위치와 목적지가 같고, now.rCnt가 M과 같다면 운송이 완료되었으므로 isDied[i] = true 처리

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
N<=100, m<=100 `O(N*m*200(이동거리))`


### 💡 풀이 아이디어
1. points 배열로 각 포인트 번호로 (r, c)좌표 입력받아 pointMap에 저장
- `Map<Integer, int[]> pointsMap` : 포인트 번호 → (r,c)
- `Map<String, Integer> timePos ` : 이동 시 매 시간단위로 기록
  - `key`: time-x-y 형태 문자열
  - `value` : 해당 좌표에 등장한 로봇 개수
2. 로봇은 최단 경로 이동 
- 문제 조건 : `r좌표를 먼저 맞추는 이동을 우선`
- r좌표가 일치할 때까지 r 방향으로만 이동
  - r1 < r2 : r++
  - r1 > r2 : r--
- r좌표가 일치하면 c방향으로 이동
3. 충돌횟수 계산
- 이동할 때마다 timePos에 count++
-  timePos.get(key)==2  answer++

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

- 좌표크기 N <= 100
- 포인터 개수 P <= 100
- 로봇 개수 X <= 100
- 루트 개수 R <= 100
- BFS로 구현할 경우
  - 최악의 경우
    - routes에서 점 2개일 때, 최대 거리: 100
    - routes[i]의 길이(거쳐야 되는 지점의 수): 100개
    - 100 × 100 둘레를 25번 이동하는 것과 같음
    - 25 × 400 = 10,000
  - routes의 최대 길이: 100
    - 100 × 10,000 = 1,000,000
  - 로봇마다 간 지점 겹치는 지점인지 확인해주기
    - (로봇이 갈 수 있는 최대 거리: 10,000) × 1,000,000

> 시간초과가 발생할 수 있으나, 다른 아이디어가 떠오르지 않아서 BFS로 구현했습니다!



### 💡 풀이 아이디어

**변수 설명**

* `Point`클래스: 좌표를 나타내기 위해 정의함
* `Point[][][] checkPoints`: bfs 경로를 역추적하기 위해 사용
  * `checkPoints[k][r][c]`: routes[k]에서 시작지점부터 끝지점까지 bfs탐색을 할 때, 직전 경로들을 저장
* `boolean[][][] v`
  * `v[k][r][c]`: 시작지점으로부터 떨어진 거리가 k일 때, (r, c) 지점 위에 있는지 확인
* `HashSet<Integer>[][][] dis`
  * `dis[k][r][c]`: routes[k]의 시작지점에서 (r, c)까지 가는데, 거리가 몇인지 저장



**풀이**

* routes에 주어진 대로 최단거리로 이동할 수 있는 경로 구하기
<div align = "center"> 
<img src = "https://github.com/user-attachments/assets/26a5d3f6-312e-49cb-b08f-9046a61d989f" width = "55%" >
</div>

  * `bfs(int[] goal, int[] current, i)`
    * `int[] goal`: 도착지점, `int[] current`: 현재 지점
    * `int i`: routes의 인덱스
    * `routes[i]`의 `current`에서 `goal`지점까지 가기 위한 최단 경로 구하기 (`checkPoints`에 경로 저장)
  * `back(current[0], current[1], goal[0], goal[1], i, routeDis)`
    * `checkPoints`에 저장된 경로를 통해 최단 경로를 역추적하며, 해당 지점이 시작지점으로부터 얼마나 떨어졌는지 표시하기
    * 표시하면서 `dis[][r][c]`를 확인하고, 해당 지점에 다른 경로가 이동하면서 방문했던 곳이라면 결과값 1 늘리기

<br>

> 제가 풀이한 방식은 효율성이 좋지 않았습니다!!
> <img src = "https://github.com/user-attachments/assets/be3d8f16-ac39-404e-b8d2-700a58254416" width = "50%">

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 구현
- 시간복잡도: n <= 100 , 로봇 수 <= 100

### 💡 풀이 아이디어
항목 | 설명
-- | --
`Robot.class` | `List<Pos> route`:모든 경로, `int start`:시작지점, `int end`:종료지점
`Pos.class` | `x` , `y`
`List<Robot> robotList` | 모든 로봇 리스트

1. 각 로봇들의 `시작지점`과 `종료지점` `시작위치` 초기화
2. 순회를 통해 각 로봇들의 모든 이동경로 저장
   - `saveRoute` : 모든 로봇의 초 마다 경로를 저장
   - 추후에 충돌 횟수를 구할 때 순회 조건을 지정하기 위해 `최장경로`를 가진 로봇의 경로 길이를 저장
3. 경로 충돌 찾기
   - `최장경로` 만큼 순회하여 i 초동안 움직였을 때 모든 로봇들의 충돌 카운팅
   - 로봇 별로 현재 위치 `Pos` 의 `hashCode` 와 `equals` 를 재정의하여 충돌 발생 유무 확인
   ``` java
   class Pos {
        ...
        @Override
        public boolean equals(Object obj) {
            if(obj == null || getClass() != obj.getClass()){
                return false;
            }
            if(this == obj){
                return true;
            }
            Pos pos = (Pos) obj;
            return this.x == pos.x && this.y == pos.y;
        }

        @Override
        public int hashCode() {
            return Objects.hash(x,y);
        }
   }
   ```
   - `Map<Pos, Integer>` 의 `put` 메소드를 통해 충돌 카운팅

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ points의 길이 = n ≤ 100
- 2 ≤ routes의 길이 = 로봇의 수 = x ≤ 100
- 100 * 100 * 100 = 1,000,000 (10^6)

### 💡 풀이 아이디어
- 처음 생각한 방법
  - bfs를 통해 각 로봇의 최단 경로를 구하고, 이때 각 좌표에 대한 visited[i](방문한 시각)을 리스트로 담기
  - 모든 이동이 끝난 후, 방문된 좌표의 리스트 크기 != 해당리스트를 set으로 만든 후 크기가 다르면 충돌이 일어난것으로 처리
  > bfs로 이동할 시 최단거리 뿐만이 아니라 최단거리에 속하지 않은 지점까지 visited[i]처리를 해서 최단경로에 대해서만 알 수 없음..
- 두번째 생각한 방법 (최단경로 역추적)
  - 첫번재 방법에 최단경로를 찾기 위해 역추적 로직을 작성함
  - 근데 중간 포인트들을 거쳐갈때 데이터 중복이 일어나서 예외처리가 애매함..
  > bfs 포기

- 기존에는 특정좌표를 어떤 시간에 방문했는지(좌표 기준)으로 충돌을 판별했다면, 특정 시간에 어떤 좌표를 방문했는지로 판단(시간 기준)
- 최단거리 구하기 (`move`)
   - r,c값으로만 최단거리로 향해가기
   - 최단 거리에 해당하는 지점값 tmp리스트에 넣기
- 모든 지점에 대한 최단거리를 찾았으면 가장 긴 경로(시간) 찾기 (시간기준이므로)
- 시간 별로 충돌확인
   - Set이용, 이때 좌표에 해당하는 키 값은 좌표값을 1차원으로 표현한 값으로 사용 (보드 크기 100 * 100)
   - set : 특정시간에 해당하는 좌표 모음
   - check : 특정시간에 충돌이 일어난 키
- 최종적으로 현재 시간에 충돌난 키의 개수를 더해줌

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ routes의 길이 = 로봇의 수 = x ≤ 100
- 2 ≤ routes[i]의 길이 = m ≤ 100
- 구현 문제라 딱히.. 계산은 안했습니다

### 💡 풀이 아이디어
- 로봇의 움직임이 겹치는 순간을 찾아주면 되는 문제
- 로봇이 움직인 턴마다 어느 곳에 있었는지 저장을 해주면 됨
  - 좌표는 `(r, c)`일 경우 `r * 1000 + c`로 바꾸어 key값으로 사용
  ```java
  HashMap<Integer, HashMap<Integer, Integer>> moves = new HashMap<>(); // 해당 턴에 로봇이 어느 위치에 몇 개 ?
  ```
- 로봇은 항상 `r`값을 움직이고 `c`값을 움직이므로 간단하게 비교하여 계산
  ```java
  while (now[0] != to[0] || now[1] != to[1]) {
      if (now[0] < to[0])
          now[0]++;
      else if (now[0] > to[0])
          now[0]--;
      else if (now[1] < to[1])
          now[1]++;
      else if (now[1] > to[1])
          now[1]--;
      turn++;
      moves.putIfAbsent(turn, new HashMap<>());
      pos = now[0] * 1000 + now[1]; // 해당 좌표를 키 값으로 변환
      moves.get(turn).put(pos, moves.get(turn).getOrDefault(pos, 0) + 1); // 해당 턴에 해당 좌표의 로봇 수 추가
  }
  ```
  ![image](https://github.com/user-attachments/assets/6c6d98c6-f35f-48d3-8d8a-21ded83b38f1)


- 중복된 로봇 카운트
  ```java
  int cnt = 0;
  for (int turn : moves.keySet())
      for (int move : moves.get(turn).keySet())
          if (moves.get(turn).get(move) > 1)
              cnt++;
  ```
