### ISSUE TITLE
[14주차_금요일] 등산코스 정하기

### ISSUE THREAD

**Issue by baexxbin** [GreatAlgorithm-Study/AlgorithmStudy#189]
- 사이트 : 프로그래머스(PG)
- 문제: [등산코스 정하기](https://school.programmers.co.kr/learn/courses/30/lessons/118669)
- 번호: 118669
- 레벨: Level3

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

- 2 ≤ `n`(노드의 개수) ≤ 50,000
- `n` - 1 ≤ `paths`의 길이(간선의 개수) ≤ 200,000
- bfs로 풀이하면 250,000 + α이므로 시간 충분함


<br>

### 💡 풀이 아이디어

**변수 설명**

* `Node` 클래스
  * `int e`: 끝점
  * `int w` : 가중치
  * `int intensity` :시작점에서 `e`까지 갈 때 최대 가중치
* `ArrayList<Node> adj[]`: 간선리스트
  * 주어진 `paths`를 통해 간선리스트를 만듦 
* `TreeSet<Integer> summitSet`: 산봉우리들의 번호를 저장하는 집합
  * 출입구의 크기 순서대로 `intensity`를 비교해야 되므로 `TreeSet`이용
* `Hashset<Integer> gateSet` : 시작 입구들을 저장하는 집합

<br>


**풀이**

* 시작점을 기준으로 bfs를 진행하면 모든 산봉우리들을 탐색하지 못할 수 있음. 따라서 산봉우리들을 기준으로 bfs를 진행함 (산봉우리 ~ 시작점)
* `bfs(int n, int s, HashSet<Integer> gateSet, TreeSet<Integer> summitSet, int[] answer)`
  * `int n`: 방문배열의 크기를 정해주기 위해 사용
    * 방문배열을 큐에 노드를 넣을 때가 아닌, 뺄 때 `true`를 해줘야 됨 (안그러면 intensity가 작은 순서대로 탐색을 못할 수 있음)
  * `int s`: 시작점
  * `HashSet<Integer> gateSet`: 다음 노드가 시작점일 때, bfs를 멈춰야 되므로 필요함
  * `TreeSet<Integer> summitSet`: bfs탐색을 할 때, 다음 노드는 산봉우리가 되면 안되므로 필요함

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: 다익스트라
- 시간복잡도: ` n ≤ 50,000` `paths의 길이 ≤ 200,000`
   - 노드의 갯수(V) = 50,000
   - 등산로의 길이(E) = 200,000
   - 우선순위 큐를 활용한 다익스트라 시간복잡도: `O(E Log V)`

### 💡 풀이 아이디어
등산경로에서 **가장 긴 등산코스** 중 (전체 등산코스에서) **최소 intensity 구하기**
항목 | 설명
-- | --
`List<ArrayList<Node>> graph` | 각 노드의 양방향 그래프
`int[] table` | 최소 intensity 테이블 
`List<Integer> summitList` | 산봉우리 확인용 리스트
`PriorityQueue<Node> pq` | 가까운 거리부터 갈 수 있도록 최소 거리 기준으로 오름차순 정렬을 위한 우선순위 큐

- 다익스트라를 통해 각 노드마다 출발 지점 ~ 산봉우리 까지의 모든 경로를 탐색
   - **한 노드에서 다른 노드로 갈 때 최소 가중치를 찾아서 이동**하고, **다음 노드까지의 최대 등산코스(intensity) 찾기**
   - 산봉우리를 중복해서 방문하지 않도록 현재 노드가 산봉우리라면 패스
   ```java
   if(summitSet.contains(index)){
      continue;
   }
   ```

   - 최장 intensity 중 최소 intensity 구하기
   ``` java
   for(Node next : graph.get(index)){
	int nextIndex = next.index;
	int cost = Math.max(table[index], next.distance);   //현재 지점에서 다음 지점으로 갈 때 가장 긴 등산코스(intensity)를 찾기
	if(table[nextIndex] > cost){    //최소 가중치 찾기
		table[nextIndex] = cost;
		pq.offer(new Node(nextIndex, cost));
	}
   }
   ```
   - 이렇게 하면 최소 intensity 테이블 `table` 에 각 노드별로 출발 지점 ~ 산봉우리 까지의 최소 intensity 가 담기게 됨
- 여러 등산코스 중 최소 intensity 를 찾고, 최소 intensity 가 여러개일 경우 산봉우리가 가장 낮은 걸로 선택

> `contains` 메소드를 List 와 Set 둘다 사용이 가능한데, Set 이 훨씬 빨랐어요. [이 블로그](https://hanul-dev.netlify.app/java/list,-set-%EC%96%B4%EB%96%A4-%EA%B2%83%EC%9D%84-%EC%93%B0%EB%8A%94-%EA%B2%83%EC%9D%B4-%EC%9C%A0%EB%A6%AC%ED%95%9C%EA%B0%80/) 에서 속도차이를 잘 보여주고 있어서 참고했습니다

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- 노드의 개수 N <= 50,000
- 간선의 개수 E < 200,000

=> 인접리스트 BFS 탐색 : O(N + E) 가능

### 💡 풀이 아이디어

- paths를 인접리스트 형태로 변환하기
- 출발점(gate)와 산봉우리(summit)을 Set으로 선언하여 각 노드의 상태를 쉽게 확인하기
- BFS 활용
    - 출발점 부터 산봉우리까지의 경로를 구하려면 돌아오는 코스도 고려해야하므로 복잡해진다
    - 반대로 산봉우리부터 출발점까지 경로를 구하면 산봉우리로 향하는 모든 경로를 탐색할 수 있다.
    - 즉, "산봉우리"부터 탐색 시작
    - 큐를 PriorityQueue로 선언해서 비용이 작은 것 먼저 우선 탐색하도록 해서 intensity의 최솟값을 구한다.
    ```java
        // 큐를 우선순위 큐로 설정하여, 비용이 작은 순부터 우선 탐색하도록 함
        PriorityQueue<int[]> q = new PriorityQueue<>((o1, o2)-> o1[0]-o2[0]);
        boolean[] visited = new boolean[N+1];
        
        // {비용, 노드}
        q.add(new int[] {0, start});
        visited[start] = true;
        
        int intensity = Integer.MAX_VALUE;
        while(!q.isEmpty()) {
            int[] now = q.poll();
            
            // 출입구를 만남
            if(gSet.contains(now[1])) {
                pq.add(new int[] {start, now[0]});
                break;
            }
            
            // 등산로 반복
            for(Node next: g[now[1]]) {
                if(sSet.contains(next.edge)) continue;
                if(visited[next.edge]) continue;
                
                visited[now[1]] = true;
                int max = Math.max(now[0], next.cost);
                q.add(new int[] {max, next.edge});
            }
        }
    ```

> 다혜님 코드를 참고하여 산봉우리부터 탐색 아이디어를 얻었씁니다 ㅎㅎㅎ 감사합니다 👍

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ n ≤ 50,000
- n - 1 ≤ paths의 길이 ≤ 200,000
- 다익스트라를 사용했는데 N^2이려나요.. 졸림 이슈

### 💡 풀이 아이디어
- `출입구 → 산봉우리 → 출입구`는 `출입구 → 산봉우리`로 압축할 수 있음 즉, 동일한 길로 가면 됨
- `출입구 → 산봉우리`로 구하는 것보다 `산봉우리 → 출입구`로 최단 거리로 도착하는 출입구를 찾아주는 것이 효율적
- `등산코스가 여러 개라면 그중 산봉우리의 번호가 가장 낮은 등산코스를 선택`라는 조건이 있기 때문에 산봉우리 배열을 정렬
- 해당 노드가 산봉우리인지, 출입구인지 확인하기 위해서 `Set`자료구조를 사용
- `다익스트라`를 이용해서 산봉우리에서 출입구까지 최단거리로 가는데 우선순위는 만들어진 루트에서 `intensity`가 작은 루트로설정하여 진행
  - `산봉우리 → 산봉우리`를 가는 경로는 제외
- `다익스트라`를 진행하면서 출입구에 해당하는 노드가 나올 시, 탐색 종료 및 최솟값 갱신
  ```java
  // 현재 노드가 출입구라면
  if (gateSet.contains(u[0])) { 
      // 기존의 최솟값보다 작을 시, 산봉우리와 indensity 갱신
      if (result[1] > u[1]) {
          result = new int[] { summit, u[1] };
      }
      break; // 다익스트라 종료
  }
  ```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ n ≤ 50,000
- n - 1 ≤ paths의 길이 ≤ 200,000


### 💡 풀이 아이디어
- 구해야할 값은 `가장짧은 쉬는 구간`
   - 입구에서 봉우리찍고 다시 입구로 가는거 안구해도됨 (왕복)
   - 어짜피 `입구 → 봉우리` 과정에서 구한 가장 짧은 쉬는 구간이 하산할때도 적용됨
   - 다익스트라 (변형) 이용
- 지점 정보 세팅 (`adj`)
   - `출입구`에선 나가는 방향만 가지면 됨
   - `산봉우리`에선 들어오는 방향만 가지면 됨
   - `쉼터에선 양방향 정보 가지기 
- 다익스트라 수행
   - 출입구들을 다 넣고 실행
   - 우선순위 큐로 작은 비용 경로를 우선으로 탐색하되, intensity 갱신시에는 큰 값으로 갱신
      - 제일 최적을 경로를 찾지만 그중 쉬는 구간의 값은 최대값을 찾아야함
- 다익스트라 수행 후, intensity 돌면서 가장 작은 값 찾기

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 2 <= n <= 50000
- 길이 <= 200000


### 💡 풀이 아이디어

1. 출입구, 산봉우리 나눠서 Set 선언
- 산봉우리에 도달할 때마다 해당 산봉우리의 강도를 확인-> 최소 강도를 갱신
2. `우선순위 큐`  : 현재까지의 intensity가 낮은 경로를 우선 탐색
- 시작점 : 모든 출입구, 우선순위 큐에 추가
- 출입구 intensity==0
- 큐에 {노드 번호, 현재 intensity} 데이터를 저장 + intensity가 낮은 순으로 정렬
```java
PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[1] - b[1]);
```
3. `다익스트라` : 각 출입구에서 산봉우리까지의 최소 intensity를 구하기
- 우선순위 큐에서 가장 최소 강도 (curIntensity)를 가진 노드를 꺼내서 이동 가능한 경로 탐색
- 산봉우리 거쳐갈 수 없으니 건너뜀
- 현재 경로에서의 최대 intensity 갱신하며 기존 강도보다 작은 intensity로 업데이트
<img width="640" alt="image" src="https://github.com/user-attachments/assets/03fd7465-dc9b-415a-ae6e-30563ef01bf7" />
<img width="254" alt="image" src="https://github.com/user-attachments/assets/adc606d7-3894-4611-be14-9cef3b3715af" />


> 테스트3에서 계속 오류 나는데.. 왜 그런지 도저히 모르겠습니다 ㅠ_ㅠ 다시 풀어보겠습니다..
