### ISSUE TITLE
[15주차_월요일] 윷놀이 사기단

### ISSUE THREAD

**Issue by jewan100** [GreatAlgorithm-Study/AlgorithmStudy#198]
- 사이트 : 코드트리(CT)
- 문제: [윷놀이 사기단](https://www.codetree.ai/training-field/frequent-problems/problems/woodstick-fraud/)
- 년도: 2019

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 4^10 : 1,048,576
- `DFS + 백트래킹`


### 💡 풀이 아이디어
1. 윷놀이판 경로 초기화
- `board[]` : 말판 경로 초기화
  - 0~32번 노드까지 입력 받음
  - 윷놀이판 이동 경로 설정 
  (1) 파란칸 도착 시(빨간 화살표) index 번호로 이동 경로 설정
  (2)직선 경로를 제외한 이동 경로 설정
  (3)도착 노드와 이어지는 경로 설정
- 점수 계산(윷놀이 1~5칸 이동 가능)
```java
          for(int i=0; i<20; i++){ // 직선 경로 이동 처리
            for(int j=1; j<=5; j++){ // 윷 놀이 1~5칸 이동 가능
                move[i][j] = i+j;
            }
        }
```
2. DFS + 백트래킹으로 점수의 최댓값 구하기 
- 10개의 이동할 수 있는 칸 수가 순서대로 주어질 때 얻을 수 있는 점수의 최댓값을 구하기
  - 말 10번 이동 완료 시 return
  - 도착(32)시 움직이지 않음
  - flag : 시작, 도착 위치 제외하고는 말이 겹칠 수 없음
```java
    boolean flag = true;
            for(int j=0; j<4; j++){ // 겹치지 않아야함
                if(i!=j && horse[j]==next && next !=32){ // 도착시 움직이지 않음
                    flag = false;
                    break;
                }
            }
```
  - dfs 재귀 호출

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 4^10 = 1,048,576 (약 10^6) 
- 완전탐색 가능

### 💡 풀이 아이디어
- 문제 이해
   - 주어진 주사위대로 각 말을 알맞게 조정해서 최대 점수 얻기
   > 처음에 도개걸모 경우 따로 생각하고, 윷일때만 주어진거 이용하는걸로 잘못이해..
- 설계 (`하드 코딩`)
   - 주어진 보드판은 보통 주어지는 이차원배열 형태가 아님
   - 또한 파란 지점에서는 분기 존재
   →  `moveIdx`(보드 역할) : 각 지점의 인덱스를 키로 두고, 각 지점에서 갈 수 있는(도개걸윷모) 거리만큼 인덱스 설정해주기
   →  `score`(점수) : 각 지점의 점수
- dfs(int hidx, int cnt, int total, List<Integer> pos)      // 움직일 말 번호, 주사위 던진 횟수, 현재까지 점수, 말들의 위치
   ```java
   private static void dfs(int hidx, int cnt, int total, List<Integer> pos) {      // 움직일 말 번호, 주사위 던진 횟수, 현재까지 점수, 말들의 위치
        List<Integer> tmpPos = new ArrayList<>(pos);
        int curDice = arr[cnt] - 1;                                     // 현재 주사위 값
        tmpPos.set(hidx, moveIdx.get(tmpPos.get(hidx))[curDice]);       // 선택한 말 이동 (현재 말의 위치에서 주사위 값만큼 이동)
        int curScore = score.get(tmpPos.get(hidx));                     // 말 이동 후 점수

        if (cnt == 9) {                                                 // 주사위 10번 모두 던지면 최종 점수 계산 후 리턴
            ans = Math.max(ans, total + curScore);
            return;
        }

        int nxtDice = arr[cnt + 1] - 1;                                 // 다음 주사위 값
        for (int i = 0; i < 4; i++) {                                   // 4개말 중 선택
            if (tmpPos.get(i)==-1) continue;                            // 이미 도착한 말은 패쓰
            int nxtPos = moveIdx.get(tmpPos.get(i))[nxtDice];           // 선택한 말의 다음 위치
            if (nxtPos !=-1 && tmpPos.contains(nxtPos)) continue;       // 다음 위치에 다른 말이 이미 있으면 패쓰
            dfs(i, cnt + 1, total + curScore, tmpPos);      // 선택한 말로 dfs 수행
        }

    }
   ```
   - 현재 주사위 값을 바탕으로 말 이동
   - 이동한 말의 점수 구하기
   - 에외처리 후(이미 도착, 다른 말 존재) 다음으로 움직일 말 골라서 dfs 수행

> 코드트리 자바9 이전 버전을 사용하군요

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 최대 4^10 이므로 완전 탐색 가능


### 💡 풀이 아이디어
- 하드코딩으로 보드 만들기 
  ```java
  static ArrayList<ArrayList<Integer>> routes = new ArrayList<>(); // 보드
  ```
  ![image](https://github.com/user-attachments/assets/a21d3020-b114-4f5e-9322-7b5eabad81e5)
  > 그림.. 에바네요.. 각 색깔에 따라 routes가 다르다는 걸.. 알려주고 싶었씁니다
- 백 트래킹으로 어떤 이동 칸 수에 어떤 말이 움직일 지 배정
- 모든 말의 이동 순서가 정해지면 이동 칸 수에 따라서 움직임 구현
- 이동할 수 없는 조건(다른 말이 있는 위치)으로 이동한다면 잘못된 이동이므로 백 트래킹
- 이동한 칸에 대한 점수를 합하여 최댓값 계산

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

=> 완전탐색 가능

### 💡 풀이 아이디어

![image](https://github.com/user-attachments/assets/38bc43f1-7d21-4f0a-9dd6-67c058b84cad)


1. initMap으로 윷놀이 맵 생성
2. dfs()로 백트래킹 시작
    - `dfs(depth, score, prr)`
    - depth: 이동한 턴 수
    - score: 총 점수
    - prr : 1~4번말의 위치 배열
    - `findPos()`로 다음 갈 위치 찾기
    - 이동시킬 수 있다면 이동시키고 백트래킹
    2.1 `findPos(현재칸번호, 이동한 횟수, 이동해야할 횟수)`
    ```java
	public static int findPos(int num, int depth, int cnt) {
		if(depth == cnt) return num;
		
		if(num == 20) return g.get(num).next;
		else if(blueSet.contains(num) && depth > 0) {
			return findPos(num+1, depth+1, cnt);
		}
		else {
			return findPos(g.get(num).next, depth+1, cnt);
		}
		
	}
    ```

> 저는 findPos() 부분이 틀린것  같은데 왜틀린지 못잡았습니다 ㅜㅜㅜㅜㅜㅜㅜㅜㅜ 같이 찾아주세요 ㅎㅎㅎ

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 노드의 개수: 31
* 말의 개수: 4

문제에서 구현하라는 대로 구현해도 시간 충분할듯!



### 💡 풀이 아이디어

* 백트래킹을 통해 말이 갈 수 있는 모든 경우 확인하면서 점수 계산하기

* map에 대한 정보를 저장하고, 현재 위치가 10일 때, 20일 때, 30일 때는 다른 방향으로 이동할 수 있도록 하기
