### ISSUE TITLE
[15주차_화요일] 프렉탈 평면

### ISSUE THREAD

**Issue by jewan100** [GreatAlgorithm-Study/AlgorithmStudy#200]
- 사이트 : 백준(BOJ)
- 문제: [프렉탈 평면](https://www.acmicpc.net/problem/1030)
- 번호: 1030

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

- 0 ≤ s(단위 시간) ≤ 10
- 3 ≤ N(바깥 사각형의 크기) ≤ 8
- 1 ≤ K(안쪽 사각형의 크기) ≤ N - 2
- (N - K) mod 2 = 0
- 0 ≤ R1, R2, C1, C2 ≤ Ns - 1
- R1 ≤ R2 ≤ R1 + 49
- C1 ≤ C2 ≤ C1 +49
- 공간복잡도
  - 최악의 경우: 최종적으로 만들어지는 배열을 직접 만들고, 범위에 해당하는 배열 출력하는 경우
    - (8^11) × (8^11) 크기의 배열을 만들어야 됨 → 메모리 초과
- 시간복잡도
  - 전체가 부분으로 이뤄어져 있기 때문에 분할정복으로 구현할 수 있음
  - 재귀호출시 시간초과가 발생하지 않도록 구현하면 됨



### 💡 풀이 아이디어

<img src = "https://github.com/user-attachments/assets/6620f380-35b4-4e42-bd65-d8f39c92d56e">

* `getBlockStatus(int r, int c, int s, int n, int outer, double percent)`를 통해 주어진 R1, R2, C1, C2 범위에 포함된 지점이 0인지 1인지 파악
   * `r`, `c`: 확인할 지점의 좌표
   * `s`:  시간
   * `outer`: 바깥 사각형 크기
   * `percent`: 바깥 사각형과 안쪽 사각형의 비율 (안쪽 사각형에 포함되었는지 확인하기 위해 사용)
   * `int interval`: 바깥 사각형과 안쪽 사각형 사이 간격
   * `int nextRecSize`: `s - 1` 시간일 때 사각형의 크기 `== (outer / n)`
* `isInCenter(int r, int c, int interval, int outer)`
   * `(r, c)` 지점이 큰 사각형 기준으로 중앙에 있는지 확인

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- s <= 10
- N <= 8
- R1 ≤ R2 ≤ R1 + 49
- C1 ≤ C2 ≤ C1 +49

=> 출력하는 최대 격자수 50 * 50 == 2500 = M
=> 분할정복 이용 : O(MlogM)

### 💡 풀이 아이디어

- 만들어질 수 있는 최대 격자는 (8^10) * (8^10) 이므로 격자배열을 만들 수는 없음
- 분할 정복으로 각 시간대의 **전체 격자의 범위**와 **검은색 부분의 범위**를 예상해서 탐색하기
    ```
    <예> N =5, K= 3
    - time = 1일 때, n = 5, k = 3                                
    - time = 2일 때, n = (5 * N), k = (3 * N)               
    - time = 3일 때, n = (5 * N * N), k = (3* N * N)    
    . . .

    (* n은 바깥에 큰 사각형의 한변의 길이, k는 검정색 부분의 한변의 길이) 
    ```
    - 위의 모든 시간 범위에서 검정색 부분은 다음과 같음
        - start = `(n - k) / 2`
        - end = start + k

   - 검정색 부분에 속하면 1을 반환, 그렇지 않으면 주어진 시간 내에 계속 탐색하기
   ```java
	public static int find(int s, int depth, int n, int k, int x, int y) {
		int c = 0;	// 색깔 변수
		
		// 검정색 범위에 속함
		if(n != 0 && inRange(n, k, x % n, y % n)) {
			c = 1;
		} else {
			// 아직 시간이 남아있고 흰색이라면 더 탐색해보기
			if(s > depth) c = find(s, depth+1, N*n, N*k, x, y);
		}
		return c;
	}
   ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 0 ≤ s ≤ 10 &rarr; O(N!)

### 💡 풀이 아이디어
- 분할 정복을 이용해서 비율 별로 검은색 타일이 존재하는 곳을 표시
- 분할 정복으로 모든 타일을 계산 후 출력하려면 8^10 x 8^10의 크기의 배열이 필요하여 `MIL`
- 따라서 `R1, R2, C1, C2`의 사각형이 포함된 분할만 진행하여 체크
- `isNotOverLap`: 서브그리드(분할할 곳)에 출력하려는 사각형이 포함되어 있지 않다면 `true`
  ```java
  private static boolean isNotOverlap(int y, int x, int len) {
      return y + len <= r1 || y > r2 || x + len <= c1 || x > c2;
  }
  ```
- `isBlack()`: 해당 좌표가 검은색 타일에 들어가는지 확인
  ```java
  private static boolean isBlack(int bsy, int bsx, int bLen, int y, int x) {
      return bsy <= y && y < bsy + bLen && bsx <= x && x < bsx + bLen;
  }
  ```
- 분할 정복으로 해결!!
```java
 private static void makeBoard(int depth, int y, int x, boolean tile) {
  int len = (int) Math.pow(n, depth); // 그리드의 길이
  // 해당하지 않으면 스킵
  if (isNotOverlap(y, x, len)) {
      return;
  }
  // 재귀 종료 조건
  if (depth == 0) {
      board[y - r1][x - c1] = tile;
      return;
  }
  int sLen = len / n; // 서브그리드의 길이
  int bsy = y + sLen * (n - k) / 2, bsx = x + sLen * (n - k) / 2; // 검은색 타일이 시작하는 지점 
  int bLen = sLen * k; // 검은색 타일의 길이
  for (int i = y; i < y + len; i += sLen) {
      for (int j = x; j < x + len; j += sLen) {
          makeBoard(depth - 1, i, j, tile | isBlack(bsy, bsx, bLen, i, j)); // 다음 재귀 진행, 검은색 타일 체크
      }
  }
}
```
> 엄청 고민하고 풀었던 문제... 개인적으로 분할 어렵습니다..

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 분할 정복 시간 복잡도 `O(M logM)`
- M : 출력하는 최대 격자수 (50 * 50 == 2500)
  - 0 ≤ s ≤ 10
  - 3 ≤ N ≤ 8
  - 1 ≤ K ≤ N - 2

### 💡 풀이 아이디어
- 프렉탈 평면이 단위 시간이 진행될 때 마다 크기가 증가함
  - 프랙탈 한변 길이 : N^S
- 검정색 영역이 아닌 경우 색을 결정할 수 없음
- 현재 시간에서 해당 위치 어떤 색인지 결정 X
- 색을 결정하려면? 더 작은 블록(상위 패턴)의 좌표로 이동해서 재귀적으로 확인 해줘야함
1)  현재 좌표가 검정 영역에 속하면 색을 바로 반환(1)
```java
        if (s <= r && r < e && s <= c && c < e) {
            return 1;
        }
```

2) 검정 영역에 속하지 않으면 : 좌표를 상위 블록으로 변환하여 재귀적으로 확인
```java
        return isCheck(r % curSize, c % curSize, curSize);
    }
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- s <= 10
- N <= 8
   - N^s(8^10) 크기의 배열을 모두 만들면 메모리 초과
- 분할정복 (O(MlogM)) 

### 💡 풀이 아이디어
- 전체 배열을 만들어 해당하는 부분 출력 불가
   - 분할정복을 통해 출력범위에 해당하는 부분 정답배열에 담기
      - 전체 사각형에서의 `절대 위치`와 분할된 하위 사각형에서 `상대 위치` 잘 고려해서 계산하기
- `recursive(int x, int y, int t, int color)`
   ```java
   private static void recursive(int x, int y, int t, int color) {     // 현재 재귀에서 행, 열, 시간, 색
        int p = (int) Math.pow(N, s - t);                   // 현재 시간에서 평면 크기 (현재 단계에서 한 격자가 차지하는 실제 크기)
        if (!isValid(x*p, x*p+p-1, y*p, y*p+p-1)) return;

        if (t == s) {                                       // 종료조건에서 색 기록
            ans[x - r1][y - c1] = (char) (color + '0');     // x,y좌표를 출력범위에 맞게 조정 후 값 넣기
            return;
        }

        for (int i = 0; i < N; i++) {            // 현재 격자 N*N으로 분열하기 (i,j는 나뉜 하위 격자내 상대좌표)
            for (int j = 0; j < N; j++) {
                int nColor;
                if (color==1) nColor = 1;
                else nColor = (isBlackArea(i) && isBlackArea(j)) ? 1 : 0;
                recursive(x * N + i, y * N + j, t + 1, nColor);     // 하위 좌표값을 전체 큰 사각형에서 본 절대좌표 값으로 변환해 보냄
            }
        }
    }
   ```
    - x,y: 현재 재귀에서 절대위치
    - `isValid()`: 현재 위치가 출력범위를 벗어난다면 재귀 종료
       - x*p, x*p+p-1, y*p, y*p+p-1: 현재 좌표 기준 사각형 꼭짓점 값으로 체크 
    - 종료 조건에 다르면 현재 x,y좌표를 출력범위에 맞게 조정해 색 값 담기
    - N*N으로 분열하기 (분열된 작은 하위 사각형 탐색)
       - i,j는 나뉜 하위 격자내 상대좌표
       - 다음 재귀 시, 하위 좌표값을 절대 좌표값으로 변환해 보내기
- 현재 격자 검정인지 판단 `isBlackArea(int i)` 
    - i: 현재 행의 인덱스
    - ((N - K) / 2): 중앙의 검정 구역 시작점
    - 행(i)을 기준으로 해당 행i가 검정구역 위, 아래 존재하는지 판단
       - 두 구역다 해당하지 않으면 검정구역에 속하는 것
