### ISSUE TITLE
[15주차_수요일] 히스토그램

### ISSUE THREAD

**Issue by jewan100** [GreatAlgorithm-Study/AlgorithmStudy#201]
- 사이트 : 백준(BOJ)
- 문제: [히스토그램](https://www.acmicpc.net/problem/1725)
- 번호: 1725

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```
> [히스토그램에서 가장 큰 직사각형](https://www.acmicpc.net/problem/6549) 입력, 출력 조금만 바꿔서 제출하면 레이팅 줘요!

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 ≤ N ≤ 100,000 (10^5)
   - O(NlogN)이하로 가능
- 각 칸의 높이: 1,000,000,000 (10^9)
   - 넓이를 구할때 10^9보다 커지기에 long형 사용

### 💡 풀이 아이디어
```java
    Deque<Integer> stack = new ArrayDeque<>();
    stack.push(0);                                                  // 0값 먼저 넣어주기

    long mx = 0;
    for (int i = 1; i <= N + 1; i++) {
        while (!stack.isEmpty() && arr[stack.peek()] > arr[i]) {        // push할 막대가 스택의 값보다 작다면, pop하면서 사각형 넓이 계산 (스택은 항상 오름차순으로 유지)
            int idx = stack.pop();
            int h = arr[idx];                                           // 높이
            int w = stack.isEmpty() ? i - 1 : i - stack.peek() - 1;     // 넓이
            mx = Math.max(mx, (long) h *w);
        }
        stack.push(i);
    }
    System.out.println(mx);
```
- 스택 이용 (O(N))
   - **스택은 오름차순으로 유지 됨**(같은 값 가능)
      - 다음 값(`arr[i]`)이 스택 내 값(`arr[stack.peek()]`)보다 크거나 같으면 push
   - push해야하는 다음 값이 스택 내의 값보다 작다면 (스택 오름차순 유지 불가)
      - 다음 값이 들어갈 수 있을때까지 pop하기 (`이때 사각형의 넓이 구하기`)
- 사각형 값 구하기
   - **pop한 값의 높이를 최소로하는 사각형 만들기**
      - 스택은 오름차순으로 들어있기에 현재 pop한 값의 높이를 최소로하는 사각형을 구해갈 수 있음 (pop하는 동안)
      - 즉, 계속 뒤에 pop으로 빠지는 값들은 언제나 이전에 pop된 값보다 작거나 같기에 사각형을 만들 수 있음
- 주의해야할 점
   - 사각형의 넓이(밑변)구하기
   > 처음엔 그냥 i-idx로 했는데, 이건 왼쪽 경계를 고려하지 못한 내용
     - `int w = stack.isEmpty() ? i - 1 : i - stack.peek() - 1;`
       - 스택이 비었을 경우 : 처음부터 길이 셈
       - 왼쪽 값이 있을 경우 : 오른쪽(현재) 값(i) - 왼쪽 값(stack.pee) -1 이용
  - 마지막까지 스택 값이 계산될 수 있도록 맨 마지막에 0 막대 추가해주기

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 1 &le; N &le; 100,000 &rarr; 10^5이므로 O(N logN)으로 진행


### 💡 풀이 아이디어
#### 1. 스택(덱)을 이용한 풀이 &rarr; O(N)
- 스택이 증가하는 혹은 감소하는 방향으로만 저장하는 기법인 _Monotic Stack_(단조 스택)을 이용해서 풀이
- `left[i]`: i번째 높이의 기둥에서 왼쪽으로 가질 수 있는 최대 길이
  ```java
  Deque<Integer> dq = new ArrayDeque<>(); // 왼쪽으로 가질 수 있는 최대 길이를 저장할 스택(덱)
  int[] left = new int[n]; // 각 인덱스 별로 가질 수 있는 왼쪽으로의 최대 길이
  for (int i = 0; i < n; i++) {
      left[i] = 1; // 초기값 = 자기 자신의 너비
      // 스택(덱)에 자신보다 큰 높이의 값이 있다면 해당 너비를 포함할 수 있음
      while (!dq.isEmpty() && arr[dq.peekLast()] >= arr[i])
          left[i] += left[dq.pollLast()]; // i 인덱스의 왼쪽 최대 길이에 합
      dq.offerLast(i); // 사용한 인덱스를 삽입
  }
  ```
- `right[i]`: i번째 높이의 기둥에서 오른쪽으로 가질 수 있는 최대 길이
  - `left[]`의 반대로 진행
- `i번째 기둥의 높이`와 `left[i]`, `right[i]`로 너비를 계산하여 넓이를 구하고 최댓값 갱신
  ![image](https://github.com/user-attachments/assets/3117ea34-1d34-4cad-9681-154b78a8dd6c)
  ```java
  // 인덱스 i에서 갖는 최대 넓이 = i번째 기둥의 높이 x (left[i] + right[i] - 1);
  int max = 0;
  for (int i = 0; i < n; i++)
      max = Math.max(max, arr[i] * (left[i] + right[i] - 1));
  ```

#### 2. 분할 정복을 이용한 풀이 &rarr; O(log N x log N)??, O(N logN)
- 주어진 히스토그램을 3가지의 상태로 분할
  1. 왼쪽 부분의 최대 사각형
  2. 오른쪽 부분의 최대 사각형
  3. 가운데 **경계**를 포함한 최대 사각형
- 이 중 가운데에 해당하는 분할에 한해서 넓이를 계산해주면 됨
```java
private static void recursive(int l, int r) {
    // 종료 조건
    if (l == r) {
        maxArea = Math.max(maxArea, arr[l]);
        return;
    }
    int m = (l + r) / 2;
    int h = arr[m]; // 초기 높이 = 중앙에 있는 기둥의 높이
    maxArea = Math.max(maxArea, arr[m]); // 너비가 1일 경우에 대해 최댓값 갱신
    int toL = m, toR = m; // 해당 기둥을 왼쪽, 오른쪽으로 넓혀가면서 최댓값을 갱신
    // 범위를 넓혀가면서
    while (l < toL && toR < r) {
        // 높이를 최대한으로 유지
        if (arr[toL - 1] < arr[toR + 1]) {
            h = Math.min(h, arr[++toR]);
        } else {
            h = Math.min(h, arr[--toL]);
        }
        maxArea = Math.max(maxArea, h * (toR - toL + 1)); // 넓이 계산
    }

    // 남은 인덱스까지 탐색
    while (toR < r) {
        h = Math.min(h, arr[++toR]);
        maxArea = Math.max(maxArea, h * (toR - toL + 1));
    }
    while (l < toL) {
        h = Math.min(h, arr[--toL]);
        maxArea = Math.max(maxArea, h * (toR - toL + 1));
    }
    recursive(l, m); // 왼쪽 분할
    recursive(m + 1, r); // 오른쪽 분할
}
```
> [풀이 영상](https://youtu.be/v4OX1OTzma4?si=xuMZTJA4hU5kHAaB) 이거 보고 오시면 이해 도움될 거에요!

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- N <= 100,000

=> O(N) or O(NlogN)으로 생각해보기


### 💡 풀이 아이디어

- 분할정복으로 풀기
    - (s, e) 범위에서 가장 큰 직사각형의 넓이를 구하고
    - (s, mid) 범위와 (mid+1, e) 범위를 재귀탐색해서 가장 큰 넓이 구하기
    ```java
                // s와 e가 같다는 것은 크기가 1인것 까지 나눠짐 -> s시작 높이 반환
		if(s == e) return arr[s];
		
		int mid = (s + e) / 2;
                // 가장 큰 사각형의 넓이 값
		long tmp = arr[mid];
		long h = arr[mid];
		int left = mid - 1;        // 현재 기준 사각형의 완쪽
		int right = mid + 1;    // 현재 기준 사각형의 오른쪽
		while(s <= left || right <= e) {
			if(s > left) {    // 더이상 왼쪽으로 못 늘어남
				h = Math.min(h, arr[right]);
				right += 1;
			} else if(right > e) {    // 더이상 오른쪽으로 못늘어남
				h = Math.min(h, arr[left]);
				left -= 1;
			} else if(arr[left] > arr[right]) {    // 왼쪽으로 늘어날 수 있음
				h = Math.min(h, arr[left]);
				left -= 1;
			} else {    // 오른쪽으로 늘어날 수 있음
				h = Math.min(h, arr[right]);
				right += 1;
			}
                       // 현재까지 결정된 가장 큰 직사각형 넓이 저장
			tmp = Math.max(tmp, (right-left-1)*h);
		}
		tmp = Math.max(tmp, Math.max(histogram(s, mid), histogram(mid+1, e)));
    ```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
N<= 10^5 `O(N)`


### 💡 풀이 아이디어
1. `heights[N+1]` : 1차원 배열로 히스토그램 높이들 입력 받기
2. `Stack<Integer> stack` : 막대 높이를 저장
- 스택이 비어있는 경우  :  `w=i`
  - 넓이 = 현재 인덱스(i)
- 스택이 비어있지X 경우  : `w = i - stack.peek()-1`
  - 현재 직사각형의 왼쪽 경계(왼쪽에 남아있는 막대) 결정 : `stack.peek()`
  - 현재 막대와의 간격 만큼만 직사각형을 확장 가능
```java
for(int i=0; i<heights.length; i++) { // 직사각형의 최대 높이 계산
	while(!stack.isEmpty() && heights[i] < heights[stack.peek()]) { // 현재 높이가 스택의 최상단에 있는 높이보다 작으면
		int h = heights[stack.pop()]; // 스택에서 높이를 꺼냄
		int w = stack.isEmpty() ? i : i - stack.peek()-1; 
		max = Math.max(max, (long)h*w);// 꺼낸 높이 기준으로 넓이 계산
	}
	stack.push(i);
}
```
_3. `long max` : 막대의 높이(10^9) * 너비(10^5) -> long_

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 1 ≤ N ≤ 100,000
* O(NlogN) 이하로 문제 풀이 해야 됨



### 💡 풀이 아이디어

* **처음 아이디어 (시간 초과)**

  * 세그먼트 트리를 이용해서 한 지점을 기준으로 사각형을 만들 수 있는 왼쪽 지점과 오른쪽 지점을 고름
  * 구현하고 코드를 보니 `N * N *logN` 의 코드였음

* **두 번째 아이디어 (스택) - `O(NlogN)`**

  * push 하려는 막대의 높이가 `stack.peek()` 보다 작다면 `stack.peek()`이 push 하려는 막대의 높이가 작아질 때까지 사각형의 넓이 구하기
    * 높이: `arr[stack.pop()]`
    * 너비: `현재 막대가 있는 위치 - stack.peek() + 1`
  * push 하려는 막대의 높이가 `stack.peek()`보다 크다면 stack에 넣어주기
