### ISSUE TITLE
[15주차_목요일] 상근이의 여행

### ISSUE THREAD

**Issue by jewan100** [GreatAlgorithm-Study/AlgorithmStudy#202]
- 사이트 : 백준(BOJ)
- 문제: [상근이의 여행](https://www.acmicpc.net/problem/9372)
- 번호: 9372

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* 2 ≤ 국가의 수(N) ≤ 1000
* 1 ≤ 비행기의 종류(M) ≤ 10000
* 국가의 수를 노드, 비행기의 종류를 간선으로 하는 그래프라고 생각할 수 있음
  * 모든 노드를 방문할 수 있도록 간선 선택하기 → bfs
* O(M × M) 까지 가능하지만 bfs로 구현하면 N × O(N + M)



### 💡 풀이 아이디어

* 국가의 수와 비행기의 종류를 입력받은 후 간선 리스트 만들기
* 모든 노드를 순회하면서, 모두 방문할 수 있도록 하기
  ```java
  for(int i = 1; i < n; i++) {
      // !v[i]일 때, bfs 진행
  }
  ```

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 1,000, 1 ≤ M ≤ 10,000 &rarr; 완전 탐색도 가능
- 하지만 트리의 성질을 이용한다면 O(1)

### 💡 풀이 아이디어
- 모든 간선에 대해서 비행기 종류는 다름
- 따라서 모든 노드를 방문하려면 노드의 개수 - 1개의 간선이 필요
- 필요한 비행기 종류는 `N - 1`

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 2 ≤ N ≤ 1,000
- 1 ≤ M ≤ 10,000
- 완전탐색 가능

### 💡 풀이 아이디어
- 비행 스케줄은 항상 연결 그래프
- a와 b를 왕복하는 비행기 M개 주어짐
   - 한 비행기당 간선 하나만 이룰 수 있음
→ 모든 노드를 잇는 연결그래프를 만드려면 간선의 개수는 `노드-1` 개

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- T <= 100
- N <= 1000
- M < 10,000

=> 완전탐색 가능
### 💡 풀이 아이디어

- 최소신장트리를 구하기
    - union()과 find()를 통해 간선들을 연결하면 최소 종류로 비행기를 탈 수 있음
    ```java
            for (int[] edge : edges) {
                int a = edge[0];
                int b = edge[1];
                if (findParent(parent, a) != findParent(parent, b)) {
                    unionParent(parent, a, b);
                    ans++;
                }
            }
            System.out.println(ans);
    ```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- `O(1)`


### 💡 풀이 아이디어
- 주어지는 비행 스케줄은 항상 연결 그래프를 이룸 -> MST(최소 스패닝트리)
- 모든 국가를 연결하는데 필요한 최소 간선의 수 찾기
- 연결된 그래프에서  MST 간선수 : N-1개
