### ISSUE TITLE
[15주차_금요일] 길 찾기 게임

### ISSUE THREAD

**Issue by jewan100** [GreatAlgorithm-Study/AlgorithmStudy#204]
- 사이트 : 프로그래머스(PG)
- 문제: [길 찾기 게임](https://school.programmers.co.kr/learn/courses/30/lessons/42892)
- 번호: 42892
- 레벨: Lv.3

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- 1 <= nodeinfo의 길이 <= 10,000
- 0 <= 노드의 좌표 값 <= 100,000
- 트리의 깊이 <= 1000
   - `O(N^2)` 가능
   - 편향된 트리 구성 가능
- 트리 배열 정렬 : `O(NlogN)`
- 전휘, 후위 순회 : `O(N)`

### 💡 풀이 아이디어
> 트리를 구성한 후 전위, 후위 순위하기

- 트리 구성
   - 트리 형태에 맞게 트리 배열 재구성(노드 값 포함)
   - `Node[] tree`에 좌표, 노드 값 넣은 후 정렬
- Node 구성
   - x, y, n : 좌표와 노드 값 (생성자에서 초기화)
   - Node left, right : (setChild에서 초기화)
- 각 노드의 자식 노드 설정 (`setChild(root, tree[i])`)
   - 만든 tree배열을 통해서는 자신의 left, right 자식을 알기 어려움 (tree배열을 통해서 트리 순회X)
   - Node객체에서 left, right 노드 설정하기
     - node의 자식 자리 비었으면 child로 설정
     - 비지 않았으면 자식자리를 루트로 child 재귀 돌리기 
   ```java
   private static void setChild(Node parent, Node child) {
        if (child.x < parent.x){                            // 왼쪽 노드 정하기
            if (parent.left==null) parent.left = child;     // 왼쪽 자리 비었으면 child로 설정
            else setChild(parent.left, child);               // 비어있지 않으면 왼쪽 노드를 부모로 하는 child 설정
        }else {                                             // 오른쪽 노드 정하기
            if (parent.right==null) parent.right = child;
            else setChild(parent.right, child);
        }
    }
   ```
- 전위, 후위 순위 진행
   - 전위 순회 : 루트 → 왼쪽 → 오른쪽
   - 후위 순회 : 왼쪽 → 오른쪽 → 루트
   - 루트 위치에 따라 리스트에 노드(루트)값 넣기 (`pre.add(node.n)`)
   - 오른쪽, 왼쪽에 따라 해당 값으로 재귀 (`preOrder(node.left, pre)`)
- 답 출력
   > Stream 맨날 피했는데 한 번 공부해봤습니다
   - `toArray()`는 참조형 배열만 생성 가능
   - Integer형 리스트를 int배열로 변환 시(참조타입 리스트 → 기본형 배열) Stream과 mapToInt 사용
      - List<Integer> → int[] 시 기본형 스트림(IntStream) 생성해야함
        - Stream<Integer>를 IntStream으로 변환 시 mapToInt 메서드 사용
      - mapToInt : 각 요소를 int로 변환하는 람다식 (Integer를 int 로 언박싱)
   `ans[0] = pre.stream().mapToInt(i->i).toArray();`

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- nodeinfo의 길이는 1 이상 10,000 이하
- O(N^2)까지 가능하므로 정렬, 순회 전부 가능

### 💡 풀이 아이디어
- `nodeinfo`로 트리를 구성해준 다음 전위 순회, 후위 순회를 하면 되는 문제
- 트리 구성
  - `nodeinfo`를 높이 순으로 정렬을 해서 root를 찾아 줌
  - root에서부터 반복하여 node를 삽입해 트리를 완성 &rarr; 재귀 이용
  ```java
  private void insert(Node root, Node node) {
      // 왼쪽에 삽입되어야 할 경우
      if (root.x > node.x)
          if (root.left == null)
              root.left = node;
          else
              insert(root.left, node); // 재귀 호출
      else if (root.right == null)
          root.right = node;
      else
          insert(root.right, node); // 재귀 호출
  }
  ```
- 완성된 트리를 순회
  ```java
  // 트리 순회
  private void traversal(Node node) {
      answer[0][preIdx++] = node.v; // preOrder
      if (node.left != null)
          traversal(node.left);
      if (node.right != null)
          traversal(node.right);
      answer[1][postIdx++] = node.v; // postOrder
  }
  ```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

-  노드의 개수 N < 10.000
- 좌표값 <= 100,000

=> O(N * N)도 가능 -> 정렬 가능

### 💡 풀이 아이디어

- 트리로 만들어서 왼쪽, 오른쪽 루트 탐색하기
    - 노드 정렬하기 : Y 값 기준 내림차순, X 값 기준 오름차순 정렬
    - `insert(parent.x, child.x)`트리만들기
    ```java
    public static void insert(Node parent, Node child) {
        // 부모의 x값이 자식보다 크다면 -> 왼쪽 자식
        if (child.x < parent.x) {
            if (parent.left == null) {
                parent.left = child;
            } else {
                insert(parent.left, child);
            }
        }
        // 부모의 x값이 자식보다 작다면 -> 오른쪽 자식
        else {
            if (parent.right == null) {
                parent.right = child;
            } else {
                insert(parent.right, child);
            }
        }
    }
    ```
- 전위순회 : 루->왼->오
    ```java
    private static void preOrder(Node node) {
        if (node == null) return;
        preOrderList.add(node.num);
        preOrder(node.left);
        preOrder(node.right);
    }
    ```
- 후위순회: 왼->오->루
```java
    // 후위 순회 : 왼->오->루
    private static void postOrder(Node node) {
        if (node == null) return;
        postOrder(node.left);
        postOrder(node.right);
        postOrderList.add(node.num);
    }
```

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* `nodeinfo의 길이`: 1 ~ 10,000
* 모든 좌표 값: 0 ~ 100,000
* 트리의 깊이: 1,000
* O(n): (nodeinfo의 길이 ^ 2) 이하로 해야 됨
* 후위순회, 전위순회 시간 복잡도: O(n)
* 트리 구성 시간 복잡도: O(n) → 편향트리



### 💡 풀이 아이디어

* `Node` 클래스

  * `int v, x, y`: 값, x좌표, y좌표
  * `Node l, r`: 왼쪽 노드, 오른쪽 노드 

* `makeTree(Node p, Node current)`

  * `p`: 부모 노드, `current` : 자식노드
  * `x`, `y` 좌표를 비교하면서 트리 만들어주기

* `preOrder(Node p, int[][] answer)`

  * 재귀호출을 하며 전위 순회 값 구하기

    ```java
    // 전위순회
    static void preOrder(Node p, int[][] answer) {
        if(p == null) return;
        answer[0][idx++] = p.v;
        preOrder(p.l, answer);
        preOrder(p.r, answer);
    }
    ```

* `postOrder(Node p, int[][] answer)`

  * 재귀호출을 하며 후위 순회 값 구하기

    ```java
    // 후외순회
    static void postOrder(Node p, int[][] answer) {
        if(p == null) return;
        postOrder(p.l, answer);
        postOrder(p.r, answer);
        answer[1][idx++] = p.v;
    }
    ```

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- 시간복잡도 : nodeinfo < 10,000 -> `O(N^2)`이하


### 💡 풀이 아이디어
- 트리 생성 후 전위 순회, 후위 순회 
1) 트리 생성(insertNode)
- Node 클래스
```java
static class Node{
        int x, y, number;
        Node left, right;
        
        Node(int x, int y, int number){
            this.x = x;
            this.y = y;
            this.number = number;
        }
    }
```
- 왼쪽 서브트리, 오른쪽 서브트리 주의하여 트리 생성
```java
static void insertNode(Node parent, Node child) {
        if (child.x < parent.x) { // 왼쪽 서브트리
            if (parent.left == null) {
                parent.left = child;
            } else {
                insertNode(parent.left, child);
            }
        } else { // 오른쪽 서브트리
            if (parent.right == null) {
                parent.right = child;
            } else {
                insertNode(parent.right, child);
            }
        }
    }
```

2) 전위 순회, 후위 순회 
- 전위 순회(부모->왼쪽->오른쪽)
```java
static void preorder(Node node){
        if(node != null){
            answer[0][index++] = node.number; // 부모 노드 방문
            preorder(node.left); // 왼쪽 서브트리 방문
            preorder(node.right); // 오른쪽 서브트리 방문
        }
    }
```
- 후위 순회(왼쪽->오른쪽->부모)
```java
    static void postorder(Node node){
        if(node != null){
            postorder(node.left); // 왼쪽 서브트리 방문
            postorder(node.right); // 오른쪽 서브트리 방문
            answer[1][index++] = node.number; // 부모 노드 방문
        }
    }
```
3) 순회 결과를 answer[] 배열에 저장 후 출력
