### ISSUE TITLE
[7주차_수요일] 스킬트리

### ISSUE THREAD

**Issue by KodaHye** [GreatAlgorithm-Study/AlgorithmStudy#84]
- 사이트 : 프로그래머스(PG)
- 문제: [스킬트리](https://school.programmers.co.kr/learn/courses/30/lessons/49993#fnref1)
- 번호: 49993
- 레벨: level2

```
### 🤔 시간복잡도 고려사항



### 💡 풀이 아이디어
```

**Comment by yeongleej** [comment]
### 🤔 시간복잡도 고려사항

- skill의 길이 <= 26
- skill_tree의 길이 <= 20
- skill_tree의 원소의 길이 <= 26

=> O(26 * 20 * 26) : 완전탐색 가능



### 💡 풀이 아이디어

- 탐색할 skill_tree에 스킬의 개수를 카운트
- dfs 탐색
    - 탐색할 `tree의 0번째 인덱스(tIdx`), `skill의 0번째 인덱스(sIdx)`부터 시작 => 스킬은 0번째부터 차례대로 찾을 수 있어야 함
    - `tree.charAt(tIdx) == skill.charAt(sIdx)`라면 스킬을 찾은 것이므로 둘 다 인덱스 증가 `tIdx+1, sIdx+1`
    - 그렇지 않다면 아직 tree에서 스킬을 못찾았으므로 tree의 인덱스`tIdx+1`만 증가
    - 스킬 인덱스(sIdx)가 탐색할 스킬 개수와 같다면 차례대로 스킬을 모두 찾은 것이므로 탐색 중단

**Comment by icegosimperson** [comment]
### 🤔 시간복잡도 고려사항
- skill 길이 * 원소 길이 * 원소의 길이 = `O(n * p * m)`

### 💡 풀이 아이디어
- skill 한 문자씩 `queue`에 넣음
- 선행 스킬이 아니라면 다음 스킬 확인
- 순서가 맞으면 큐에서 제거
- 순서가 틀리면 중단

**Comment by yeahdy** [comment]
### 🤔 시간복잡도 고려사항
- 알고리즘: Map
- 시간복잡도:  `1 <= skill_trees <= 20` 길이 , `2 <= skill_trees <= 26`
 `O(20*26)`으로 단순 구현으로 가능한 크기

### 💡 풀이 아이디어
- 스킬트리에 skill 있는 말든 상관없이, **skill의 순서가 꼬였지 올바른지가 포인트**
- 스킬트리의 각 문자를 순회하면서 현재 skill의 순서와 일치하지 않을 경우 카운팅 x
   - 초기 순서는 1으로 순서와 일치하지 않았다는 것은 선행스킬을 배우지 않고, 순서가 꼬였다는 뜻

**Comment by KodaHye** [comment]
### 🤔 시간복잡도 고려사항

* `1 <= skill_trees의 길이 <= 20`
* `1 <= 선행 스킬 순서 길이 <= 26`

이므로 별다른 알고리즘을 사용하지 않고 구현해도 시간이 충분할 것이라고 판단 



### 💡 풀이 아이디어

* `HashMap<Character, Integer> hashMap`
* `skill`에서 알파벳 별로 순서 저장
* `idx = 0`부터 `skill.length -1`까지 확인

  ```java
  for(int i = 0; i < skill_tree[i].length(); i++) {
      if(hashMap.get(s.charAt(i) > idx)) // 불가능한 스킬트리
  }
  ```

**Comment by baexxbin** [comment]
### 🤔 시간복잡도 고려사항
- skill 길이 <= 26
- skill_tree 길이 <= 20
- skill_tree 원소 길이 <= 26
- 완전탐색 가능

<br>

### 💡 풀이 아이디어
- skill_tree의 각 단어들에서 skill에 해당하는 알파벳만 추출
  - `if (sk.contains(c)) sb.append(c);`
- 추출된 단어가 skill로 시작하는 서브스트링이면 cnt++
  - `if (skill.startsWith(sb.toString())) cnt++;`

**Comment by jewan100** [comment]
### 🤔 시간복잡도 고려사항
- skill_trees는 길이 1 이상 20 이하인 배열
- skill의 길이는 1 이상 26 이하
- 문자열 완전 탐색

### 💡 풀이 아이디어
- 스킬 순서로 주어진 문자 외에 모든 문자를 지웠을 때, 스킬 순서를 주어진 대로 유지하고 있으면 됨
- `정규 표현식`으로 다른 문자들 제거
  - `"CBD"` 순이라면 &rarr; `"[^CBD]"`로 정규 표현식을 만든 뒤 `replaceAll(regex, "")`을 이용하여 문자 제거
  ```
  "BACDE" → "BCD"
  "CBADF" → "CBD"
  "AECB" → "CB"
  "BDA" → "BD"
  ```
- 남은 문자가 스킬 순서와 동일하면 카운트 &rarr; `startsWith`이나 `indexOf` 써서 확인!!
